### ISSUE TITLE
Stuck in v4

### ISSUE THREAD

**Issue by HyakuAr** [Norbyte/bg3se#103]
I can't seem to be able to make the auto update work and I have no idea why. In the console I'm still in v4 I tried putting the v7 files into BG3ScriptExtender. But I guess I still miss the right DWrite.dll. Any idea to solve it?

**Comment by lexiluboo** [comment]
Same issue!! Would love to know if someone has resolved/figured-it-out???? :(

**Comment by BelegCufea** [comment]
At your own risk, you can try [offline installation](https://bg3se-updates.norbyte.dev/Channels/Release/ManualInstall.zip).
More info in second half of my response in Issue #99.
