### ISSUE TITLE
Warnings in log i cant get rid of?

### ISSUE THREAD

**Issue by SilverBackSpartan** [Norbyte/bg3se#104]
Sorry if i don't know this, i tried searching before but is this normal?
Im running as admin on Dx11, latest update for game and scriptExtender
```
No match found for mapping 'esv::SavegameManager::WarnIfModded'
No match found for mapping 'ecs::ComponentIDRef'
No match found for mapping 'ecs::EventComponentIDRef'
No match found for mapping 'ecs::ReplicationComponentIDRef3'
Library startup took 841 ms
LibraryManager::PostStartupFindLibraries() took 117 ms
bg3se::ecs::EntitySystemHelpersBase::MapComponentIndices(): Could not find index for component: eoc::spell::CastComponent
bg3se::ecs::EntitySystemHelpersBase::MapComponentIndices(): Could not find index for component: eoc::spell::CastComponent
```

**Comment by Norbyte** [comment]
These are normal btw. The ComponentIDRef, EventComponentIDRef, ReplicationComponentIDRef3 ones will always occur for newer bg3.exe versions.
You get the `esv::SavegameManager::WarnIfModded` warning in GOG versions, since achievements are not a thing there.
