### ISSUE TITLE
Mac version?

### ISSUE THREAD

**Issue by awkcrin** [Norbyte/bg3se#105]
If there isn't the possibility of making a version for Mac, would it be possible to explain how to install this version on it?

**Comment by KittyGrim** [comment]
Yes please! There are so many brilliant mods we are currently missing out on.

**Comment by kenjura** [comment]
+1

**Comment by Norbyte** [comment]
tl;dr there are currently no plans for Mac version.

**Comment by awkcrin** [comment]
Make one
