### ISSUE TITLE
Does not come with warranty 

### ISSUE THREAD

**Issue by Eralyne** [Norbyte/bg3se#107]
I ordered this package and the Authentic Morbyte Product ™️ seal was broken when it was delivered. I tried calling customer support and turns out, to my surprise, that there was no warranty! My package was pre-opened and I can't even get my money back!

7/10 pretty good stuff but could be better

**Comment by Norbyte** [comment]
Sorry, warranty is only provided for Script Extender Enterprise™️ licensees :(
