### ISSUE TITLE
Script extender update failed 

### ISSUE THREAD

**Issue by ggwicked88** [Norbyte/bg3se#11]
When I load the game up I get an alert saying 

"Script extender update failed. Script extender not available for game version v4.36.22.274"

I don't understand is the not the latest version of the game?

**Comment by AlexanderI32** [comment]
Same for me. Not working on the same version

**Comment by alexthekid07** [comment]
Are you guys playing the game pirated or something?

**Comment by AlexanderI32** [comment]
Yes, it is pirated.

**Comment by alexthekid07** [comment]
> Yes, it is pirated.

Well you have the answer to your problem... There are versions script extender doesn't work with.

**Comment by PinewoodPip** [comment]
![image](https://github.com/Norbyte/bg3se/assets/53646914/6d7304e7-f90d-4259-8d21-5d46895a3f9c)

**Comment by Sc0D** [comment]
no update ?

**Comment by PinewoodPip** [comment]
> no update ?

Hi,
The game by default automatically updates. If you are not receiving the latest game updates, ensure that they are enabled in `Right-click BG3 in library -> Properties -> Updates -> Automatic Updates`. Restarting the steam client also helps in cases where the update isn't fetched. Updates also require you to have enough disk space.
For other kinds of installs, see [here](https://user-images.githubusercontent.com/53646914/263612936-6d7304e7-f90d-4259-8d21-5d46895a3f9c.png) for help.

Best regards,
Pip

**Comment by MrIMakeVids** [comment]
so what now, the torrent hasent updated yet, and we cant use this, its insanely annoying to get infernal iron but ofc the console doesnt work without this!

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
