### ISSUE TITLE
Script Extender not working for me

### ISSUE THREAD

**Issue by Laina26** [Norbyte/bg3se#117]
Hi, I am trying to use SE with BG3 and im having trouble. I've downloaded and extracted all files correctly, then was told to download console version to check it was working which I did but I don't get a console window at start up. I'm sure I've done everything correctly. Am running Steam version of game with BGMM. Any ideas on what's gone wrong? Thank you :)

**Comment by rcx1** [comment]
Check #99

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
