### ISSUE TITLE
Script Extender Updating

### ISSUE THREAD

**Issue by TheHamberglar3** [Norbyte/bg3se#119]
Hi there, I have a mod that requires v5 (or newer) of script extender and mine will not update further than v2. I have tried completely downloading a new script extender as well as doing it through the Mod Manager itself. Is this something I can somehow update manually or is this a Mod Manager issue?

Thanks!

**Comment by kimkimH2** [comment]
For me with mod manager there will be a "!" or some such on the name of the mod, with a small mouseover saying it needs a later version. I think refreshing mod manager will update it.

**Comment by TheHamberglar3** [comment]
> For me with mod manager there will be a "!" or some such on the name of the mod, with a small mouseover saying it needs a later version. I think refreshing mod manager will update it.

Yeah, the issue was actually the parse manifest issue that other people were having, the error just wasn't showing up for me in game. But I was able to get mine fixed following what people did on that issue
