### ISSUE TITLE
Issue: Cannot queue server commands in game state Uninitialized

### ISSUE THREAD

**Issue by Sceptorro** [Norbyte/bg3se#120]
![Screenshot 2023-10-28 130552](https://github.com/Norbyte/bg3se/assets/149262321/00f1be12-a879-43f8-975d-509423ffe2f7)

**Comment by Norbyte** [comment]
There are 2 prerequisites for using the server console:
1) A savegame (or new game) must be fully loaded
2) You must be the host (otherwise the server is not running in your game)
