### ISSUE TITLE
Script Extender Crash

### ISSUE THREAD

**Issue by n0light** [Norbyte/bg3se#123]
Crash appears after 100% save loading on both Dx11 and Vulkan. Bg3SE v7.
![изображение](https://github.com/Norbyte/bg3se/assets/149384136/2b6c9742-e119-4033-aa9d-2b05f1cce0cc)

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
