### ISSUE TITLE
after Patch 4 some errors

### ISSUE THREAD

**Issue by SwissFred57** [Norbyte/bg3se#125]
got following errors after pacth 4 and SE Mods not working

BG3Ext v8 built on Oct 28 2023 21:30:42
Game version v4.38.82.84 OK
ScriptExtender::Initialize: Starting
No match found for mapping 'ls__GlobalAllocator' [CRITICAL]
No match found for mapping 'ls::FixedString::CreateFromString' [CRITICAL]
No match found for mapping 'ls::FixedString::GetString' [CRITICAL]
No match found for mapping 'ls::FileReader::FileReader' [CRITICAL]
No match found for mapping 'ls__PathRoots' [CRITICAL]
No match found for mapping 'CoreLibSDM::Init'
No match found for mapping 'EoCServer2/EoCClient2' [CRITICAL]
No match found for mapping 'ecl::EoCClient::HandleError' [CRITICAL]
No match found for mapping 'ecl::GameStateEventManager::ExecuteGameStateChangedEvent - Initial' [CRITICAL]
No match found for mapping 'esv::GameStateMachine::Update - Initial' [CRITICAL]
No match found for mapping 'esv::GameStateThreaded::GameStateWorker::DoWork' [CRITICAL]
No match found for mapping 'ecl::GameStateThreaded::GameStateWorker::DoWork' [CRITICAL]
Target mapping action did not succeed for mapping 'ecl::GameStateThreaded::GameStateWorker::DoWork - Outer' [CRITICAL]
No match found for mapping 'esv::SavegameManager::WarnIfModded'
No match found for mapping 'esv::SavegamePostVisit_DisableStoryMerge'
No match found for mapping 'esv::StatsSystem::ThrowDamageEvent'
No match found for mapping 'eoc::DealDamageFunctor::ApplyDamage'
No match found for mapping 'App::Instance'
No match found for mapping 'RPGStats::Load'
No match found for mapping 'ecs::StaticIDRegistrant'
No match found for mapping 'ecs::StaticStringConstructor'
No match found for mapping 'ecs::ComponentReplicationIDRef'
No match found for mapping 'ecs::ComponentIDRef'
No match found for mapping 'ecs::ComponentIDRef2'
No match found for mapping 'ecs::ComponentIDRef3'
No match found for mapping 'ecs::ComponentIDRef4'
No match found for mapping 'ecs::EventComponentIDRef'
No match found for mapping 'ecs::EventComponentIDRef2'
No match found for mapping 'ecs::EventComponentIDRef3'
No match found for mapping 'ecs::ReplicationComponentIDRef'
No match found for mapping 'ecs::ReplicationComponentIDRef2'
No match found for mapping 'ecs::ReplicationComponentIDRef3'
No match found for mapping 'KillLauncher'
No match found for mapping 'eoc::gResourceManager'
ScriptExtender::Initialize: Could not load libraries; skipping scripting extension initialization.
Starting Lua debugger server
Lua debugger listening on 127.0.0.1:9998; DBG protocol version 3
Library startup took 1568 ms

**Comment by ShamHyper** [comment]
+

**Comment by SwissFred57** [comment]
Norbyte is aware of it and will let us know when fixed
make a nice weekend till then

**Comment by qdoomq** [comment]
any news on this cause i have the same problem

**Comment by ShamHyper** [comment]
> any news on this cause i have the same problem

[Problem](https://github.com/Norbyte/bg3se/commit/224aee8c5cb0f85d90c8129803cdd4f6d389e92a) fixed arleady 2 weeks ago. Send your console output with errors.

**Comment by SwissFred57** [comment]
yes indeed is fixed now thanks for point me at the fix

**Comment by qdoomq** [comment]
G3Ext v7 built on Oct  8 2023 18:45:00
Game version v4.39.11.62 OK
ScriptExtender::Initialize: Starting
No match found for mapping 'ls__GlobalAllocator' [CRITICAL]
No match found for mapping 'ls::FixedString::CreateFromString' [CRITICAL]
No match found for mapping 'ls::FixedString::GetString' [CRITICAL]
No match found for mapping 'ls::FileReader::FileReader' [CRITICAL]
No match found for mapping 'ls__PathRoots' [CRITICAL]
No match found for mapping 'CoreLibSDM::Init'
No match found for mapping 'EoCServer2/EoCClient2' [CRITICAL]
No match found for mapping 'ecl::EoCClient::HandleError' [CRITICAL]
No match found for mapping 'ecl::GameStateEventManager::ExecuteGameStateChangedEvent - Initial' [CRITICAL]
No match found for mapping 'esv::GameStateMachine::Update - Initial' [CRITICAL]
No match found for mapping 'esv::GameStateThreaded::GameStateWorker::DoWork' [CRITICAL]
No match found for mapping 'ecl::GameStateThreaded::GameStateWorker::DoWork' [CRITICAL]
Target mapping action did not succeed for mapping 'ecl::GameStateThreaded::GameStateWorker::DoWork - Outer' [CRITICAL]
No match found for mapping 'esv::SavegameManager::WarnIfModded'
No match found for mapping 'esv::SavegamePostVisit_DisableStoryMerge'
No match found for mapping 'esv::StatsSystem::ThrowDamageEvent'
No match found for mapping 'eoc::DealDamageFunctor::ApplyDamage'
No match found for mapping 'App::Instance'
No match found for mapping 'RPGStats::Load'
No match found for mapping 'ecs::StaticIDRegistrant'
No match found for mapping 'ecs::StaticStringConstructor'
No match found for mapping 'ecs::ComponentReplicationIDRef'
No match found for mapping 'ecs::ComponentIDRef'
No match found for mapping 'ecs::ComponentIDRef2'
No match found for mapping 'ecs::ComponentIDRef3'
No match found for mapping 'ecs::ComponentIDRef4'
No match found for mapping 'ecs::EventComponentIDRef'
No match found for mapping 'ecs::EventComponentIDRef2'
No match found for mapping 'ecs::EventComponentIDRef3'
No match found for mapping 'ecs::ReplicationComponentIDRef'
No match found for mapping 'ecs::ReplicationComponentIDRef2'
No match found for mapping 'ecs::ReplicationComponentIDRef3'
No match found for mapping 'KillLauncher'
ScriptExtender::Initialize: Could not load libraries; skipping scripting extension initialization.
Library startup took 1443 ms
Fossilize ERROR: Failed to parse ApplicationInfoFilter, letting recording go through.
Fossilize INFO: Overriding serialization path: "E:\SteamLibrary\steamapps\shadercache\1086940\fozpipelinesv6\steamapprun_pipeline_cache".

**Comment by qdoomq** [comment]
i get this error everytime not sure what to do

**Comment by ShamHyper** [comment]
@qdoomq 
> i get this error everytime not sure what to do

It's strange, if we have the same bg3se version, then why do you have an error?
Try to run the game again, but only with bg3se, without other mods. I think that's the problem.

And just in case, try to download the latest release, maybe yours is outdated - https://github.com/Norbyte/bg3se/releases/download/updater-20231028/BG3SE-Updater-with-Console-20231028.zip


I use this mods and have no errors
![image](https://github.com/Norbyte/bg3se/assets/104412752/05ebaa04-b3c7-4783-b652-d2f96afccd2f)
![image](https://github.com/Norbyte/bg3se/assets/104412752/0c42cf7b-95e9-49f9-aa96-d6ac9072b2db)

**Comment by ShamHyper** [comment]
@qdoomq
Yes, as I didn't notice right away:
> G3Ext v7 built on Oct 8 2023 18:45:00
> Game version v4.39.11.62 OK
You have an old version

**Comment by SwissFred57** [comment]
need version v9
and improveUI 3.13.2

**Comment by qdoomq** [comment]
thank you! apparently it was a config file that was making it stay at version v7

**Comment by ShamHyper** [comment]
@qdoomq
What kind of config are we talking about? The only config that you can get here is this
```json
{
  "CreateConsole": true
}
```
Try replace DWrite.dll from here - https://github.com/Norbyte/bg3se/releases/download/updater-20231028/BG3SE-Updater-20231028.zip . I think this will help. And check out all the mods updates on nexus. If some mods were not updated after 03.10.2023, I think they are broken and cause errors.

I hope we helped you 😉

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
