### ISSUE TITLE
downloaded update but unable to update?

### ISSUE THREAD

**Issue by InkDragon** [Norbyte/bg3se#126]
Likely an edge case here due to me having broken Internet. 

I currently am only able download updates via my phone and transfer them to my PC, for most mods this seems fine. However for the script extender even after downloading the latest version it isn't wanting to register as being on version 8.

I understand if there is no fix for this, but is there anyway to download the extender with console that bypasses the updater?

**Comment by rcx1** [comment]
Try manual install / download. More in the [Releases](https://github.com/Norbyte/bg3se/releases)

**Comment by InkDragon** [comment]
> Try manual install / download. More in the [Releases](https://github.com/Norbyte/bg3se/releases)

Unable to find any information on manual instillation at that link, did use search in page so could have missed it but unlikely.

**Comment by rcx1** [comment]
Try to read it from top to bottom, when you reach the title **Installation** you are in the right spot.

**Comment by SilverBackSpartan** [comment]
I am afraid Inkdragon is right. There is nothing but the updater versions, no manual installation versions.
I can't update from v8 to v9. I had to get the manual version for v8 now i am here for the v9 one.

**Comment by InkDragon** [comment]
> I am afraid Inkdragon is right. There is nothing but the updater versions, no manual installation versions. I can't update from v8 to v9. I had to get the manual version for v8 now i am here for the v9 one.

I found a work around on the nexus: [BG3SE AppData](https://www.nexusmods.com/baldursgate3/mods/3800) has v9 in it. Can confirm it works for me on Windows 10 with my broken Internet(I'm in a place where WiFi is really the only option, and my pc is refusing to detect any networks due to the 22H2 bug).

**Comment by Norbyte** [comment]
FYI, the manual install URL always has the latest version, in this case v9:
https://bg3se-updates.norbyte.dev/Channels/Release/ManualInstall.zip

**Comment by InkDragon** [comment]
> FYI, the manual install URL always has the latest version, in this case v9: https://bg3se-updates.norbyte.dev/Channels/Release/ManualInstall.zip
> 
> Note: This version does not contain an updater, you have to redownload it manually each time a new build comes out.

Thank you! would it be possible to link that on the main page for others to find? I'm sure it'll save others some headache latter on down the line having stuff like that easy to find.
