### ISSUE TITLE
Script extender went back to v7 when v8 was already installed.

### ISSUE THREAD

**Issue by Callipygia** [Norbyte/bg3se#127]
Is version 8 not available? Have not updated to Patch 4.

**Comment by zxiosalt** [comment]
having the same issue here, my mods requiring SE v8 were working last night, but after downgrading to patch 3 again this morning and reinstalling script extender, it doesnt seem to be updating itself. SE console reports it being v7

**Comment by Yegie** [comment]
Same, it overrides a manual install on v8 with v7. Likely a cache issue, but I can't seem to find where it is caching v7. Alternatively it falsely believes v7 is latest and is downgrading v8. Can't find how to disable autoupdate to check this tho.

**Comment by zxiosalt** [comment]
> Alternatively it falsely believes v7 is latest and is downgrading v8. Can't find how to disable autoupdate to check this tho.

someone else linked [this manifest](https://bg3se-updates.norbyte.dev/Channels/Release/Manifest.json) that it is likely grabbing the "latest" version from. in this case it seems to be a build of v7, though i'm not sure why that is. i'm gonna attempt to build the latest version of the source myself and see if i can bypass the updater entirely.

**Comment by Yegie** [comment]
> > Alternatively it falsely believes v7 is latest and is downgrading v8. Can't find how to disable autoupdate to check this tho.
> 
> someone else linked [this manifest](https://bg3se-updates.norbyte.dev/Channels/Release/Manifest.json) that it is likely grabbing the "latest" version from. in this case it seems to be a build of v7, though i'm not sure why that is. i'm gonna attempt to build the latest version of the source myself and see if i can bypass the updater entirely.

The instructions for performing a manual install in here seem to work. Was able to install v8 manually. Have done very minimal testign so far, but no errors are getting printed and the console reports v8 https://github.com/Norbyte/bg3se/issues/124

**Comment by zxiosalt** [comment]
the manual install works for me as well, thanks for pointing it out! hopefully the downgrade issue is fixed soon, but manual updates should be fine until then.

**Comment by alexmahfud** [comment]
hey i'm having this issue bg3 mod manager it still says v7 is downloaded even when i grabbed the latest file from here , any help would be greatly appricated

**Comment by Callipygia** [comment]
> > > Alternatively it falsely believes v7 is latest and is downgrading v8. Can't find how to disable autoupdate to check this tho.
> > 
> > 
> > someone else linked [this manifest](https://bg3se-updates.norbyte.dev/Channels/Release/Manifest.json) that it is likely grabbing the "latest" version from. in this case it seems to be a build of v7, though i'm not sure why that is. i'm gonna attempt to build the latest version of the source myself and see if i can bypass the updater entirely.
> 
> The instructions for performing a manual install in here seem to work. Was able to install v8 manually. Have done very minimal testign so far, but no errors are getting printed and the console reports v8 #124

Downloaded the [](https://bg3se-updates.norbyte.dev/Channels/Release/ManualInstall.zip), still v7, where did you get v8?

**Comment by zxiosalt** [comment]
@Callipygia @alexmahfud try these steps, they worked for me:

1. delete the existing DWrite.dll (and optionally ScriptExtenderSettings.json) from `Baldurs Gate 3/bin`
2. delete any folders/files starting with 7 located in `%localappdata%/BG3ScriptExtender` and its subfolders
3. download v8 from [](https://bg3se-updates.norbyte.dev/Channels/Release/ManualInstall.zip) and extract both dll files into `Baldurs Gate 3/bin`
4. start the game and it should be on the correct version

i believe if it detects cached versions older than v8 it may try to downgrade itself again, hence the deletion of the cache files. hope that helps!

**Comment by Callipygia** [comment]
> @Callipygia @alexmahfud try these steps, they worked for me:
> 
> 1. delete the existing DWrite.dll (and optionally ScriptExtenderSettings.json) from `Baldurs Gate 3/bin`
> 2. delete any folders/files starting with 7 located in `%localappdata%/BG3ScriptExtender` and its subfolders
> 3. download v8 from  and extract both dll files into `Baldurs Gate 3/bin`
> 4. start the game and it should be on the correct version
> 
> i believe if it detects cached versions older than v8 it may try to downgrade itself again, hence the deletion of the cache files. hope that helps!

Got v8 working, had to delete everything in BG3ScriptExtender.

Problem is respec ctd's, anyone with the same issue?

**Comment by Akiric93** [comment]
> > @Callipygia @alexmahfud try these steps, they worked for me:
> > 
> > 1. delete the existing DWrite.dll (and optionally ScriptExtenderSettings.json) from `Baldurs Gate 3/bin`
> > 2. delete any folders/files starting with 7 located in `%localappdata%/BG3ScriptExtender` and its subfolders
> > 3. download v8 from  and extract both dll files into `Baldurs Gate 3/bin`
> > 4. start the game and it should be on the correct version
> > 
> > i believe if it detects cached versions older than v8 it may try to downgrade itself again, hence the deletion of the cache files. hope that helps!
> 
> Got v8 working, had to delete everything in BG3ScriptExtender.
> 
> Problem is respec ctd's, anyone with the same issue?

I deleted everything then tryed applying the file and now nothing is working

**Comment by vapecoder** [comment]
> having the same issue here, my mods requiring SE v8 were working last night, but after downgrading to patch 3 again this morning and reinstalling script extender, it doesnt seem to be updating itself. SE console reports it being v7

Would you mind explaining how you managed to downgrade your game? I have not yet managed to find a way to do so

**Comment by Yegie** [comment]
I did not need to downgrade as I have steam set to not auto update stuff.
That said if you Google steam download depot downgrade or something like
that you'll probably find how to downgrade

**Comment by zxiosalt** [comment]
> > having the same issue here, my mods requiring SE v8 were working last night, but after downgrading to patch 3 again this morning and reinstalling script extender, it doesnt seem to be updating itself. SE console reports it being v7
> 
> Would you mind explaining how you managed to downgrade your game? I have not yet managed to find a way to do so

assuming Windows here: Win+R to open the Run dialog, enter `steam://open/console` and then run all three of the following commands in Steam:
- `download_depot 1086940 1086941 3694534054212424521`
- `download_depot 1086940 1419652 1546445398978025522`
- `download_depot 1086940 1419653 2295385710444616309`

those should download all the required game files for patch 3, but they need to be relocated from the depot folder (`steamapps/content/app_xxxxxx`) to the proper install folder (i.e. `steamapps/common/Baldurs Gate 3/`) and adhere to the game file structure.

NOTE: there is no progress indicator for depot downloads, it will print a message when it completes. one of the depots is around 120-140 GB, so just be patient and wait for it to finish.

**Comment by chamoslee** [comment]
> Same, it overrides a manual install on v8 with v7. Likely a cache issue, but I can't seem to find where it is caching v7. Alternatively it falsely believes v7 is latest and is downgrading v8. Can't find how to disable autoupdate to check this tho.

the cache path is C:\Users\USERNAME\AppData\Local\BG3ScriptExtender

**Comment by Pyr0blad3** [comment]
so bassically for everyone who has not tried checking something in BG3 ModManager, do the following:

go to Tools -> Download and Extract the Script Extender ...
go to Settings -> Open Preferences -> Updater -> Update Channel: Devel -> Select Version: Latest (or which version you want)

**dont forgett to save in the top left corner (disk symbol)!**

now your ScriptExtender should use the latest "Development Version", currently v9. there are 2 branches in the Updater -> Update Channel.
1. Release
2. Devel

Devel stands for Development here.

so my guess would be that there are 2 branches, one is the public branch where scriptextender updates itselfs automatically.
the other one is the development branch where is doesnt update automatically but you can select the versions from it via BG3 Mod Manager.

as v7 is the latest version in the release branch it would answer the question why you all have v7 as your versions currently! idk what happend to v8 but yeah maybe it got removed from the branch or something because it had a bug or idk.

so my tip is just switch in BG3 Mod Manager to the development branch and select latest version, maybe the development branch has a few more bugs in it but it should be more up to date if that is what you all want.

cheers everybody hope i helped a bit!

**Comment by SilverBackSpartan** [comment]
So what about non BGMM users?

**Comment by zxiosalt** [comment]
non BGMM users can still do the manual install as mentioned above, the mod manager just automates the process of downloading and extracting the newest file

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
