### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by Basilisk289** [Norbyte/bg3se#128]
Hi, I'm really new to all of this and I installed the script extended a couple weeks ago for some mods that required it but i decided i wanted to play without any mods, so i want to uninstall (especially now that i'm having a couple issues that i believe are do to the new patch and the script extender)

Can I just go and delete the file i put into my game files? or will it be more complicated than that? Would deleting the game and re-downloading it work as well? The only other mod I have downloaded is the party limit begone mod

**Comment by rcx1** [comment]
Installation:
Download the extender
Extract DWrite.dll to the Baldurs Gate 3\bin directory (eg. C:\Program Files (x86)\Steam\steamapps\common\Baldurs Gate 3\bin)

UnInstallation:
Delete DWrite.dll from the Baldurs Gate 3\bin directory (eg. C:\Program Files (x86)\Steam\steamapps\common\Baldurs Gate 3\bin)

**Comment by Ratigorr** [comment]
If you want to play with mods, needs downloading previous depots from Steam and replace files in game folder.
In Steam console:
1. download Data folder
download_depot 1086940 1086941 3694534054212424521
2. download Bin folder 
download_depot 1086940 1419652 1546445398978025522
