### ISSUE TITLE
Hey I'm getting soft locked in long rests

### ISSUE THREAD

**Issue by cookiealchemie** [Norbyte/bg3se#129]
i go into the long rest, and it does that thing where its like "oh one of your companions are having a dreamful sleep pls wait for them" like this is a multiplayer sesh even tho its not
and i flip over to the other party members and none of them trigger any cutscenes or anything
it might be because of this https://www.nexusmods.com/baldursgate3/mods/3479 but the game also pops up that the script extender isnt working right when i boot up the game, so I came here

**Comment by OpticNebula** [comment]
I think that's something specific with that mod since it happened to me too. Try resting with only four party members total and the re-add them after the rest if you haven't already. It worked for me when I was using that mod!

**Comment by cookiealchemie** [comment]
see i tried that, still having the problem

**Comment by Kinyami** [comment]
After the long rest is completed simply switch to Laezel, that usually fixes the issue

**Comment by BelegCufea** [comment]
Another way is to use group hide icon under the portraits.

**Comment by cookiealchemie** [comment]
still broken :/
i thiiiiink its trying to load a cutscene but its not wanting to work? It keeps saying "some of your companions are in a dreamful sleep" even tho no one is so idk whats wrong i think i softlocked myself

**Comment by cookiealchemie** [comment]
i rly hope its not because the astarion forest sex kind of overrode a visit from the dream guardian, but if that was the case i think this problem wouldve happened sooner, because that weirdness happened pre-patch

**Comment by cookiealchemie** [comment]
oh yeah this only happened after i updated the bg3 mod manager (idk if that also put me on patch 4 or not)

**Comment by cookiealchemie** [comment]
FUCK SHIT WRONG BUTTON

**Comment by rgergon** [comment]
This might be a general issue with certain mods and situations where you have summons around that aren't really around anymore but still "registered" to your party. They kind of stay awake but are not present and block the sleep from going through. There is a solution on how to fix this in:
https://www.nexusmods.com/baldursgate3/mods/1646?tab=posts
Scroll down to Tawaporah's long post. It explains what you need to do. A shorter version is in the comment to that comment. Basically you need the script console, list all companions and delete out manually those that shouldn't be present (most likely some summons). Once done, you can rest normally again.

**Comment by virnik0** [comment]
Check what character is stuck in 'sleepin' state before entering long-rest. In my case, it was often Gale, sometimes Karlach. When this happened, that character was removed from the group during sleep, but never re-added back, which caused it to bug-out during next long-rest.

To fix this, before going to sleep, check if given companion is or isn't in the group:
`_D(Osi.DB_Players:Get(nil))`

Then, if he/she isn't there, add him/her:
`_D(Osi.DB_Players("S_Player_Gale_ad9af97d-75da-406a-ae13-7071c563f604"))`

Refresh the group:
`Osi.PROC_CheckPartyFull()`

And only then go to long-rest. If it doesn't help for some reason, you can try swapping companion to PC character and then back to NPC:
```
MakePlayer("S_Player_Gale_ad9af97d-75da-406a-ae13-7071c563f604")
MakeNPC("S_Player_Gale_ad9af97d-75da-406a-ae13-7071c563f604")
```

**Comment by floralabsinthe** [comment]
I'm having the same issue, I've tried all of the above. I've even removed everyone from my party before long resting, but it just gets stuck forever no matter what I do. Ended up having to delete my save entirely because no matter how early I loaded back, it still wouldn't let me get past a long rest.

**Comment by virnik0** [comment]
> I'm having the same issue, I've tried all of the above. I've even removed everyone from my party before long resting, but it just gets stuck forever no matter what I do. Ended up having to delete my save entirely because no matter how early I loaded back, it still wouldn't let me get past a long rest.

Have you tried disabling all your companions, and then entering camp and long-resting?

Something like:
`SetOnStage("S_Player_Gale_ad9af97d-75da-406a-ae13-7071c563f604", 0)`

Also, check who is in your party. Often times, there are long-dead spawns which are still listed as a party members. Deleting them allows the companion(s) finish the sleeping.

Adjust as needed based on output of `_D(Osi.DB_Players:Get(nil))`:

```
SetOnStage("Elemental_Fire_ConjureElemental_1b120525-c6c5-1a99-6d07-7cc741adace1",0)
Osi.DB_PartOfTheTeam:Delete("Elemental_Fire_ConjureElemental_1b120525-c6c5-1a99-6d07-7cc741adace1")
Osi.DB_Players:Delete("Elemental_Fire_ConjureElemental_1b120525-c6c5-1a99-6d07-7cc741adace1")
Osi.DB_Avatars:Delete("Elemental_Fire_ConjureElemental_1b120525-c6c5-1a99-6d07-7cc741adace1")
Osi.DB_PartOfTheTeam:Delete("Elemental_Fire_ConjureElemental_1b120525-c6c5-1a99-6d07-7cc741adace1")
Osi.DB_IsOrWasInParty:Delete("Elemental_Fire_ConjureElemental_1b120525-c6c5-1a99-6d07-7cc741adace1")
```

**Comment by RubenKelevra** [comment]
Had that, too, with more than 4 party members. Then just click on the portrait of one of the party members which is not sleeping on the ground. This will switch the camera focus and everyone wakes up.

Had that twice, and then it's gone for some reason.

**Comment by cookiealchemie** [comment]
Taking everyone out of my party and doing the long rest alone made it work, somehow. im gonna keep this thread open in case this happens again

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
