### ISSUE TITLE
No installed extender version found?

### ISSUE THREAD

**Issue by LvndMass** [Norbyte/bg3se#131]
I don't know if this is only an issue now because of Patch 4, but when I use the mod manager to install the script expander it says that it installs correctly, but the red no extender pop up is still there. I'm new to modding but the DWrite.dll file is in the bin folder and so is the updater? Do I need to install a new version or is it just patch 4?

**Comment by ICandyChi** [comment]
It hasn't been updated to Patch 4 yet, you need to wait for the update.

**Comment by LvndMass** [comment]
> It hasn't been updated to Patch 4 yet, you need to wait for the update.

Okay thank you so much! I didn't know if I had messed up something haha
