### ISSUE TITLE
I know you're working hard on this and I apologize

### ISSUE THREAD

**Issue by DaelonDuluc** [Norbyte/bg3se#132]
Apologies on behalf of the community for the "demands".

In the meantime, I've moved my mods that require your extender off my list and will bring them back once you confirm update.

Thank you so much for all your hard work.  As an Administration Manager for our programs, I know how hard our staff needs to work to move things forward.

Again.  Many thanks and apologies.

**Comment by Sargonnas77** [comment]
I'd like to add my thanks as well.  Seriously appreciate the effort he and others like him across games put into doing this.  It's not something I'd ever have the patience or talent to do.

**Comment by CynicalLion** [comment]
Thanks so much we are so lucky to have your support and be able to use your work to run mods. I know you are going as fast as you can, and I am so thankful for everything you have done and can do in the future!

**Comment by vapecoder** [comment]
+1 for this post. Your work has enabled so many amazing mods that truly enhance the experience of the game. There are those of us that understand how much work goes in to making something like what you've made, and deeply appreciate the contribution. Thank you

**Comment by ErrantX** [comment]
+1 as well - this mod is the glue that holds the BG3 modding community together and we owe a lot to your hard work. Thank you so much for the effort and energy you've put into this. You are 10/10 the GOAT of the BG3 modding community.

**Comment by gcDragonWarrior** [comment]
I would also like to offer a big thank you for all of your hard work keeping us demanding gamers happy!  Just a quick question, how will I know when the update is available? Will there be a message on Norbytes BG3 Script Extender page letting us know the new version is ready?  I know, I am impatient, but I am also a developer so I really do appreciate all of your hard work on this tool!!! Cheers mate!!!

**Comment by DaelonDuluc** [comment]
Thank you all!  It looks like we are good to go!  I'm so excited.  :)

**Comment by ErrantX** [comment]
> Thank you all! It looks like we are good to go! I'm so excited. :)

I don't see that the file's been updated - where are you seeing that?

**Comment by DaelonDuluc** [comment]
> > Thank you all! It looks like we are good to go! I'm so excited. :)
> 
> I don't see that the file's been updated - where are you seeing that?

I first noticed when my mod-manager indicated it then came to the https://github.com/Norbyte/bg3se page and it was updated to remove the "not updated" notice.

Mine is working swimmingly now! :)

**Comment by timmaculewicz** [comment]
How does this mod's updater work? Does it automatically download the fixes they made? I expected there to be a new release to manually download.

**Comment by DaelonDuluc** [comment]
> How does this mod's updater work? Does it automatically download the fixes they made? I expected there to be a new release to manually download.

It took me a minute to figure out, but, the instructions are pretty thorough since the .dll file has to be uploaded to a specific place in the Steam files, but, yes, when the update happened, my mod-manager automatically let me know that it happened.

**Comment by ErrantX** [comment]
> > > Thank you all! It looks like we are good to go! I'm so excited. :)
> > 
> > 
> > I don't see that the file's been updated - where are you seeing that?
> 
> I first noticed when my mod-manager indicated it then came to the https://github.com/Norbyte/bg3se page and it was updated to remove the "not updated" notice.
> 
> Mine is working swimmingly now! :)

Not to be a bother to you, but what are you using for your mod manager? I'm using Nexus Mod Manager and I've been going to https://github.com/Norbyte/bg3se/releases to grab the latest releases when they come in a zip file I pull DWrite.dll out of and put into my steam folder. I am not seeing a new release to this. This has been a manual process for me, and I'm not seeing the release on this site.

**Comment by DaraAra** [comment]
Thank you for the hard work man, you are the goat

**Comment by captaincrow** [comment]
> > > > Thank you all! It looks like we are good to go! I'm so excited. :)
> > > 
> > > 
> > > I don't see that the file's been updated - where are you seeing that?
> > 
> > 
> > I first noticed when my mod-manager indicated it then came to the https://github.com/Norbyte/bg3se page and it was updated to remove the "not updated" notice.
> > Mine is working swimmingly now! :)
> 
> Not to be a bother to you, but what are you using for your mod manager? I'm using Nexus Mod Manager and I've been going to https://github.com/Norbyte/bg3se/releases to grab the latest releases when they come in a zip file I pull DWrite.dll out of and put into my steam folder. I am not seeing a new release to this. This has been a manual process for me, and I'm not seeing the release on this site.

I am also not seeing v9 under latest releases yet. I update manually, as I don't see an option to update using BG3 Mod Manager.

**Comment by MarredOne** [comment]
I don't understand how you can keep up this much work, but I (as do apparently all real people who use your free tools) appreciate the hell out of it. Stay awesome.

**Comment by Zardizz** [comment]
I am also actually adding a comment here to counterbalance all the twats demanding stuff now and not a second later, for free stuff. You're a saint we don't deserve for having to deal with insane people and still do this. I would lose my mind.

**Comment by venusxx** [comment]
Thanks so much for all your amzing work!

**Comment by Norbyte** [comment]
Thanks everyone!
