### ISSUE TITLE
Please don't think I am completely stupid - or at least don't call me such to my face...

### ISSUE THREAD

**Issue by Jenna11610** [Norbyte/bg3se#134]
I use BG3 mod manager. I downloaded the latest version of the script extended using their program. I also tried it manually. But when I try to launch the game through the mod manager, I get a white screen and nothing else. I never had this problem before the latest patch 4.0. I know I am probably doing something wrong and will HAPPILY admit it if someone could give me an idea what that might be.

Thank you in advance!!

**Comment by craysiii** [comment]
They haven't released a new version for patch 4.0 yet. It seems like the work may be commited, but if you check under releases, its still from 10/28. Just be patient and I'm sure they will release it soon!

**Comment by Jenna11610** [comment]
Actually, I did some testing and it works. I loaded the game through steam instead of BG3MM and it opened with all of my mods. I think my mod manager (or possibly my brain) had a huge spike of temporary insanity!! Please close this for now. Thank you so much everyone!

**Comment by zonkedz** [comment]
Also having this issue. Tried downloading it manually, as well as switching to developer build. Also tried loading through steam and nothing. It won't update to v9. I know a few others also are having this issue, whereas others are automatically having it update to v9 and running mods with no issues :(

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
