### ISSUE TITLE
Script Extender not loading any mods?

### ISSUE THREAD

**Issue by Sasagiso** [Norbyte/bg3se#139]
Hi, I've updated my script extender to the latest version (v9) however none of my script extender mods are functioning. All my other mods load and function perfectly fine.

![image](https://github.com/Norbyte/bg3se/assets/149858817/548a833f-e141-4078-85c6-4327569d621a)

I've fresh installed SE multiple times and the problem still persists, am I doing something wrong? I've also checked my mod loader and made sure my mods have been exported.

Thanks in advance.

**Comment by Natolii** [comment]
Game Update 4 broke the Script Extender.

**Comment by archiezhie** [comment]
I‘m having this problem too, but it seems many people are perfectly fine.

**Comment by Sasagiso** [comment]
Update: This appears to be an issue with Mod Fixer. The issue fixes itself when I remove Mod Fixer and any mod that comes with it.

Could it be a windows thing? Tried my same list of mods on another PC with windows 10 instead of 11 and it worked flawlessly without me needing to remove Mod Fixer + mods with it.

Would rather not have to choose between one or the other :(

**Comment by archiezhie** [comment]
doesn't work out for me after i uninstall mod fixer and every mod that depends on it.

**Comment by Sasagiso** [comment]
> doesn't work out for me after i uninstall mod fixer and every mod that depends on it.

Yeah, it did originally work for me but now has returned to just not working despite anything again.

**Comment by Caerula** [comment]
I also have the same problem. Can someone solve it? A lot of thanks.

**Comment by Sasagiso** [comment]
Problem has been magically fixed. Must've been some wizardry from Norbyte's end. Thanks!
