### ISSUE TITLE
Script Extender Crashes on main save after Patch #1

### ISSUE THREAD

**Issue by Tama-Cat** [Norbyte/bg3se#14]
After trying to continue the save that had been using the Script Extender, after Patch 1 it gets to 60% loading then crashes to desktop almost instantly. Not entirely sure how to go about fixing it, or if it's just due to Patch 1

**Comment by MadMungo** [comment]
I have the same problem here. I tried running the version with console output but the window dissapears when the game crashes.
There are no logs in the game dir.
I sent a couple of crash dumps but only noticed the ref# 6124 after the second one sent.

**Comment by Norbyte** [comment]
Hi,

Can you check if the game crashes without the extender?
The crash reporter cannot properly distinguish between game crashes and extender crashes and frequently gets invoked when in fact it is a game issue.

**Comment by MadMungo** [comment]
Yeah it is still doing it without the extender. I have other playthrough saves that work, these don't have any mods that have been updated since retail patch #1, also they don't change/modify core game files.

**Comment by Tama-Cat** [comment]
I've tried loading my main save with and without the extender. Without it, I can start a new save file just fine with no issues. But the main problem, as stated is with my main one. I had a look through the "Issues" section to see if anyone was having the same problem as me and gave the solution posted in #13 but it was still crashing.

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
