### ISSUE TITLE
BG3SE hangs game at 93%

### ISSUE THREAD

**Issue by sirkingjamz** [Norbyte/bg3se#142]
![image](https://github.com/Norbyte/bg3se/assets/106445283/4c35dd33-fe32-42a5-b1a0-b377b2aef69d)
im only guessing this has to do with patch 4 still? BG3MM pulls the latest v9.0 and when it loads the console it also says v9.0. 
secondly if this is truly v9.0 ill also assume i need to update these mods? 
ill double check if updates are available for these mods and check back here in a bit. fingers crossed its just updates (it is weird to get stuck here for me at least i normally crash trying to load a save not stuck at main menu load screen)

**Comment by sirkingjamz** [comment]
So i checked if the mods needed updates, a few did but it seems unrelated to this, also i find that launching it from the games launcher had some success, or pointing to a release that isnt there, I used 8.0.0.0 with no hash, and BG3MM would error saying "no script extender for v4.1.1.3905231, but not even v9.0 of BG3SE goes that high. Still it seems to work with minimal mods, basically any that don't use SE exclusively. NTL I hope an update is near :) thanks for all the hard work thus far Norbyte and team :)

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
