### ISSUE TITLE
What is a "Fossilization Error" ? 

### ISSUE THREAD

**Issue by AndyManaus** [Norbyte/bg3se#143]
![bg3seerrormesg](https://github.com/Norbyte/bg3se/assets/149883968/f704a9d9-0f52-4029-9493-d45de002b798)
I updated my Script Extender, I updated my game. 
Loading unmodded saves or saves whose mods don't utilize SE seems to work fine, (haven't tested any SE dependent mods, as they have not updated). 

However upon startup I see the following error messages "Fossilize Error", I can play normally, but again, it seems there's no explanations anywhere what that error even is, what does it relate to, what should I do to fix it or how might it impact the game/ the saves. etc. 
Any clarification would be deeply appreciated.

**Comment by AndyManaus** [comment]
Update: I got a grip on what "Fozzilize ERROR" means in the context of games. 
I am still in the dark however wether this has to do with the Script Extender, the game itself (as made by Larian) or something else.
I hope some code-savy individual can shed some light on this situation

**Comment by Norbyte** [comment]
Fossilize has nothing to do with the extender, but every DLL loaded in the game share the same console window, so if the SE console is opened, the debug output of everything loaded is visible in the same window.
This message can be ignored.
