### ISSUE TITLE
Extender stopped working 3/11/23.

### ISSUE THREAD

**Issue by Maksonaza** [Norbyte/bg3se#144]
Tried to replace dwrite.dll with v1- last, and tried manual. Mods than need it stopped working, console doesn't show up. i didn't update game if that matters. v4.1.1.3700362

**Comment by confusedenoch** [comment]
UPDATE YOUR GAME! At least until Hotfix #9 (v4.1.1.3767641)

**Comment by Maksonaza** [comment]
why?

**Comment by Natolii** [comment]
> UPDATE YOUR GAME! At least until Hotfix #9 (v4.1.1.3767641)

Update 4 has since been released which is why The Script Extender Stopped Working.

**Comment by Maksonaza** [comment]
can i find old script extender somewhere?

**Comment by Ilahrien** [comment]
I've been on Patch 2 this whole time as well, and then SE stopped working. I tried lots of things to get it working again, but never managed. Best I got was making the console show up again with the Manual Install, but the mods needing SE still weren't working. I'm on Patch 4 now. In some older threads, there are downloads [here](https://github.com/Norbyte/bg3se/issues/90#issuecomment-1747489079), for me they didn't work. But good luck to you! Do report please if you manage, I miss Patch 2 already.

**Comment by sclient** [comment]
Im not ready to update my game yet, I just want the old version that was working perfectly with HF6, and had no problems being detected by MM, to work. I dont understand why it suddenly needs to break.

**Comment by Maksonaza** [comment]
> I've been on Patch 2 this whole time as well, and then SE stopped working. I tried lots of things to get it working again, but never managed. Best I got was making the console show up again with the Manual Install, but the mods needing SE still weren't working. I'm on Patch 4 now. In some older threads, there are downloads [here](https://github.com/Norbyte/bg3se/issues/90#issuecomment-1747489079), for me they didn't work. But good luck to you! Do report please if you manage, I miss Patch 2 already.

Unfortunately it didn't help. Console showed up, but mods and commands didn't work.
