### ISSUE TITLE
dialogue NOT FOUND

### ISSUE THREAD

**Issue by sleepines** [Norbyte/bg3se#145]
![20231105010645_1](https://github.com/Norbyte/bg3se/assets/143885348/8c0f16ab-efd3-42a6-b72d-ec386bf8dd38)

pls can someone help? what causes this bug? ;_; this too happened after patch 4... not sure where to ask ._.

**Comment by sonofthunder77** [comment]
possibly OIO is not updated? do you use that mod

**Comment by sleepines** [comment]
what is OIO ? i do have mods but idk shortened names

**Comment by sonofthunder77** [comment]
overexplained interaction options? mod author did say prior to updating for
patch 4 yo ucould see this bug

**Comment by sleepines** [comment]
uh i don't have that one, i do use mod that shows approvals but that got an update already..

**Comment by beiminator** [comment]
i had the same problem and it was something messing up with the locale files. This has nothing to do with the script extender at my knowledge. I fix it by uninstalling, renaming the installation directory (something like BG3 fucked up installation) and reinstalling the game fresh ... 

i belive you can also, if you did a backup like i didn't (XD) simply rename the fucked installation, rename the backup as the actual game installation was and repatch. Then install back everything don't override stuff on your bin directory

**Comment by beiminator** [comment]
your files are on the cloud so you cannot backup them and put them back ... But if you saved your progress with some mod installed, the game will look for those modes and ell you "This mods aren't present so your game may have odds behaviors, go fuck yourself!" xD

No sorry, if you install the game fresh with no mods inside you will have to start a fresh campaign. You can reload the old one once all the mods you have installed are ready for patch 4 so you can install them back on the fresh installation. Then and only then your old saves will work

**Comment by sleepines** [comment]
my game syncs with steam cloud but i can def see save game folder on my pc (player profiles-public-) , roughly 5gb worth of saves e.e and yeah i know that warning very well lol, scared the heck outta me the first time ^^' but now i'm used to it..especially if i've removed something i kind of have to ignore it. and i haven't seen any problems before this patch O.o

isn't this SE already ok with patch 4? that's what ppl have said? idk there are just too many broken things with this patch 4 it's hard to know what is causing what ._. (missing kissing scenes, dialogue not found, saves resetting the playtime..)

i've tried to validate game files few times too but idk if it has done anything..re-installing game would be last thing..if there's nothing else to do, like if i knew a certain mod caused it..then i'd remove it or wait for update..

**Comment by Thk54** [comment]
I got this in an entirely unmoded game, so I think this is a base game problem.

**Comment by sleepines** [comment]
that's what i think so too now, i removed all mods i had and still had the issue. i just sent a bug report to Larian , so maybe they can tell me if they know about it and it can be fixed without reinstalling anything *fingers crossed*

**Comment by beiminator** [comment]
> I got this in an entirely unmoded game, so I think this is a base game problem.

well, not if the game crashed when withers shows up and you had trade with withers mod i guess :P

BTW, with a fresh installation, meaning after disinstalling the game, manually delete the bg3 folder that still contains old native mods, i had no problema and stil havent ... exept i'm very much missing Trade With Withers mod ;(
