### ISSUE TITLE
Every mod that requires BG3 SE crashes the game.

### ISSUE THREAD

**Issue by n0light** [Norbyte/bg3se#146]
I have v8 SE version, I didn't update my game with 4th patch that messes SE up, but still can't use any SE relied mods. Every time any mod triggers it's scripts game crashes with such errors:
![WQEwiPFooSs](https://github.com/Norbyte/bg3se/assets/149384136/fa3e18d8-a9db-492e-ab50-af499f6f1a8f)
![_QSjhtzahdY](https://github.com/Norbyte/bg3se/assets/149384136/720220d3-a504-4c29-8f3d-d16d45f49a22)
![279045123-2b6c9742-e119-4033-aa9d-2b05f1cce0cc](https://github.com/Norbyte/bg3se/assets/149384136/d442b3d6-684b-4765-8e83-3bd99e757d5d)

I also tried to use console to figure anything out and that's what I get:
![uqd1N9Ogf3s](https://github.com/Norbyte/bg3se/assets/149384136/a4c7b188-861a-47d2-b0a2-20740e934f5a)

What am I supposed to do to fix it and what could it be?

**Comment by UptightMicrobe** [comment]
Norbyte is working on an update

**Comment by n0light** [comment]
> Norbyte is working on an update

Other users don't seem to have this problem, I'm on working game patch also, as I said - I didn't update to 4th patch.

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
