### ISSUE TITLE
Can't play Multiplayer

### ISSUE THREAD

**Issue by ScottPinguin** [Norbyte/bg3se#147]
Me and my friends are trying were playing just fine but after we clean up some mod to a new save file they can't enter my save, this is the log, there is any fix to that? allready did some stuff to try and fix it but nothing. Help pls

### Compile("C:/Users/Julio VDG/AppData/Local/Larian Studios/Baldur's Gate 3/Temp/Story/story_generated.div","r+")
DeleteAllData
line 1503: error: Osiris fact/proc/query NRD_KillStory does not start with "DB_"/"PROC_"/"QRY_"
line 1505: error: Osiris fact/proc/query NRD_BadCall does not start with "DB_"/"PROC_"/"QRY_"
line 1520: error: Osiris fact/proc/query NRD_KillStory does not start with "DB_"/"PROC_"/"QRY_"
line 1522: error: Osiris fact/proc/query NRD_BadCall does not start with "DB_"/"PROC_"/"QRY_"
line 1537: error: Osiris fact/proc/query NRD_KillStory does not start with "DB_"/"PROC_"/"QRY_"
line 1539: error: Osiris fact/proc/query NRD_BadCall does not start with "DB_"/"PROC_"/"QRY_"
line 1554: error: Osiris fact/proc/query NRD_KillStory does not start with "DB_"/"PROC_"/"QRY_"
line 1556: error: Osiris fact/proc/query NRD_BadCall does not start with "DB_"/"PROC_"/"QRY_"
line 1571: error: Osiris fact/proc/query NRD_KillStory does not start with "DB_"/"PROC_"/"QRY_"
line 1573: error: Osiris fact/proc/query NRD_BadCall does not start with "DB_"/"PROC_"/"QRY_"

10 error(s), 0 warning(s). Compilation ended.

**Comment by mewshina** [comment]
I'm having this issue, as well, but I'm not getting that error. All that happens is none of my friends can join our multiplayer save on my game and vice versa with me on theirs. It simply kicks us out before we fully load in. You must be thinking it's an issue with incompatible mods, then, but that _cannot be._ My friends and I have tried quite literally everything, they even downloaded my data folder and mods folder, respectively. Mind you, before patch 4, we had no issues playing. We are all playing on a Windows 11 desktop PC, have all the same mods in the same order on BG3MM, and everything is up-to-date.

**Comment by LizB0tt** [comment]
Hi, did anyone figure this out yet? I've had this problem for 3 weeks now and I can't figure it out.

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
