### ISSUE TITLE
Disappearing Menu Icons and No Character Models

### ISSUE THREAD

**Issue by pzreich** [Norbyte/bg3se#148]
Hey, not sure if this is an issue with the script extender specifically or another mod, but I'm running into an issue where the buttons on the main menu show up for a moment and then disappear (in order) in rapid succession. I can still click them, but upon loading into my current game, no character models show up, even in the inventory, and talking to a character puts the speech bubble on their icon but no dialogue happens. When I enter in a new game, there is no character to edit. Not really sure how to fix this! Ty for reading this :>
EDIT: This issue persists even after taking all of my other mods out of the mod folder and deleting the modsettings.lsx, so there's more to why I am inclined to think it may be an issue with the script extender

**Comment by dioxias** [comment]
i had this issue as well, for me it was because an old version of a mod (i believe no main menu music?) was installed loose. i deleted `MainMenu.xaml` and `MainMenu_c.xaml` in `Data/Public/Game/GUI/Widgets` , which fixed it for me

**Comment by pzreich** [comment]
@dioxias Thank you for your input! I hadn't downloaded any main menu mods, but according to another commenter the issue was not mod related, but related to the Date folder. Steam relayed that by removing certain files, the game issues would be resolved:
day0.pak
Patch0_Hotfix1.pak
Patch0_Hotfix2.pak
Patch0_Hotfix3.pak
Patch0_Hotfix4.pak
Patch1.pak
Patch2.pak
Patch2_Hotfix1.pak
Patch2_Hotfix2.pak
Patch3.pak
Patch3_Hotfix1.pak
Patch3_Hotfix2.pak
Patch3_Hotfix3.pak
In case anyone has any issues in the future, this fixed it for me!
