### ISSUE TITLE
SE cannot load any mod

### ISSUE THREAD

**Issue by saintxidian** [Norbyte/bg3se#149]
The console show information that SE don't load any mod.

![console](https://github.com/Norbyte/bg3se/assets/37766521/b192e7f5-9c7e-4932-9d1d-d2f8ffb10c9e)
follow is my mod:
![image](https://github.com/Norbyte/bg3se/assets/37766521/178d318c-a570-4ba6-8e1e-c87552d0aff7)

**Comment by kk2349** [comment]
This has not been updated for patch #4 yet. Until SE updates you won't be able to play any mods that require SE

**Comment by saintxidian** [comment]
V9 built on Nov 5 2023 and the log shows game version is OK. I think my SE is newest  and update for patch 4.

> This has not been updated for patch #4 yet. Until SE updates you won't be able to play any mods that require SE

**Comment by Debugga-nb** [comment]
> V9 built on Nov 5 2023 and the log shows game version is OK. I think my SE is newest and update for patch 4.
> 
> > This has not been updated for patch #4 yet. Until SE updates you won't be able to play any mods that require SE

Unless you manually pulled and installed it, you would be incorrect. Even then, you'll probably face a number of bugs, and the issue of the SE required mods still not working, as they will need to update to incorporate the yet unreleased patch 4 changes. 

The correct place to look for new versions is at ["Releases"](https://github.com/Norbyte/bg3se/releases/)
When exploring there, you will note that the newest Release is dated 2023/10/28.

**Comment by saintxidian** [comment]
figure it out

**Comment by saintxidian** [comment]
must login in steam
