### ISSUE TITLE
Multiple Mapping Errors

### ISSUE THREAD

**Issue by Kiljaeh** [Norbyte/bg3se#150]
After updating to v9, I'm getting multiple mapping errors when starting the game.  It allows it to load, but mods are not being loaded correctly for use.
![Capture](https://github.com/Norbyte/bg3se/assets/150106822/4785be8c-d4ad-41e6-a16c-fb4ec4c82552)

**Comment by Kiljaeh** [comment]
Solved.

**Comment by ottapota** [comment]
May I ask how this was solved?  I'm having some of the same issues.
