### ISSUE TITLE
Error code 126

### ISSUE THREAD

**Issue by Zyaku-Eketwi** [Norbyte/bg3se#152]
"Script Extender Updater Error
 Failed to load Script Extender library.
 LoadLibrary() returned error code 126" 

Anyone Knows what happened here this is the error i got while trying to mod a friend

**Comment by beiminator** [comment]
Well i guess you are getting that error after patch 4 so ... maybe that :P

**Comment by Norbyte** [comment]
126 is module not found, typically means that a dependency could not be loaded.
Make sure you have the latest Visual C++ runtime installed: https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by Zyaku-Eketwi** [comment]
> I am receiving the same error. I have the most up-to-date VC++ runtime installed. I even downloaded the link you provided and selected Repair and reboot.

Did the same on my buddies laptop. Seems to do with the console version not communicating properly it seems with certain computers

**Comment by bassomitron** [comment]
I tried getting rid of the console version and only using DWrite.dll and it still gave the same error. Not really sure what the deal is.

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
