### ISSUE TITLE
How much effort to update after patch? Legit question

### ISSUE THREAD

**Issue by dcfreema** [Norbyte/bg3se#153]
This is a legit question, I don't have an ulterior motive. How difficult is it to update after Larian releases a patch? What all is involved?

**Comment by sirkingjamz** [comment]
My assumption after seeing nearly daily access to the files via commits it would seem to be hard and could take a while. For a minute it looked like they were testing a file but posting new files just yesterday means that didnt work and they're testing a new file. whats important is having something that works for everyone not just their test machine and to insure that means closed beta testing. we just have to be patient, plus most mods that need BG3SE are making temp files (if possible) removing the need for it right now (i've also seen a file making a temp file to replace the script extender as a temp fix)

**Comment by dcfreema** [comment]
I absolutely understand the need for patience. I did not intend for this to be a "please hurry up" meaning. I am simply someone who doesn't understand how much work goes into this and was looking for a little bit more understanding.

**Comment by dcfreema** [comment]
Thank you for the peek behind the curtain, Norbyte! Also, thank you for al of the time and work you put into this.
