### ISSUE TITLE
Errors when updating appearances

### ISSUE THREAD

**Issue by firefox1968** [Norbyte/bg3se#156]
I am very new and trying to decipher what mod this is coming from, probably Tav's Hair , but there is a screen shot I captures from BGSE
![Screenshot 2023-11-09 190142](https://github.com/Norbyte/bg3se/assets/150402377/5f6c53dc-d7a8-4dd7-a544-6bfb59345098)

**Comment by Norbyte** [comment]
Hi,
This is a bug in the appearance edit mod, not in SE.

**Comment by firefox1968** [comment]
> Hi, This is a bug in the appearance edit mod, not in SE.

Thank You!!  And thank you for all you're hard work that you do!!
