### ISSUE TITLE
Transmog mod shows multiple SE errors

### ISSUE THREAD

**Issue by Dariy-Darayava** [Norbyte/bg3se#160]
Hello.
While using this mod (https://www.nexusmods.com/baldursgate3/mods/2922?tab=description&BH=2) and I'm getting multiple "bg3se::lua::ReplicateComponent(): Unable to replicate;" errors.
![image](https://github.com/Norbyte/bg3se/assets/75636855/0844c863-72da-4fa8-9465-a5a2eba7af5c)

**Comment by Debugga-nb** [comment]
Patch 4 Release has not yet released.

**Comment by Dariy-Darayava** [comment]
> Patch 4 Release has not yet released.

If that is indeed general problem for patch 4 than thank you for the information! We'll just have to wait for the fix.

**Comment by Norbyte** [comment]
For reference, this was a transmog-specific issue, not an SE issue.
