### ISSUE TITLE
Game not running

### ISSUE THREAD

**Issue by AbHECKS** [Norbyte/bg3se#161]
Hello.
When I install the game as vanilla and put DWrite in the bin folder, it won't run in the launcher.
Steam > Play > LariLauncher > Play > Game not running
However, if I delete DWrite from the bin folder, it runs.
I'm playing on Windows 11, do you have a solution?

**Comment by Debugga-nb** [comment]
Patch 4 Release has not yet released.

**Comment by Debugga-nb** [comment]
> Try installing BG3SE from BG3 Mod Manager and not from nexusmods nor manual download from here.

Running the BG3 Mod Manager tool for installing the SE pulls from releases.

**Comment by AbHECKS** [comment]
Installing BG3SE from BG3 Mod Manager is not working. I tried both Devel mode and Release mode.
Is there a way I can check the Error logs?
Since there is no response when I press Play on launcher, I tried using console mode, but the console doesn't even pop up....

**Comment by AbHECKS** [comment]
> > Try installing BG3SE from BG3 Mod Manager and not from nexusmods nor manual download from here.
> 
> Running the BG3 Mod Manager tool for installing the SE pulls from releases.

Installing BG3SE from BG3 Mod Manager is not working. I tried both Devel mode and Release mode.
Is there a way I can check the Error logs?
Since there is no response when I press Play on launcher, I tried using console mode, but the console doesn't even pop up....

**Comment by bassomitron** [comment]
Nah man, SE is just broken for the majority of people for the time being. Some folks got it to work, but it's a very "your mileage may vary" type of situation. Even those that do get it working have other random problems pop up while playing. Just wait until it's fully updated/compatible with Patch #4.

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
