### ISSUE TITLE
the mods don't work for me

### ISSUE THREAD

**Issue by Kylo213** [Norbyte/bg3se#165]
It doesn't work for me and the mods work as if the Extender Script were not there
![Captura](https://github.com/Norbyte/bg3se/assets/132586844/5d1f7ab9-9392-408d-b9cb-78c077ce6512)
![FFF](https://github.com/Norbyte/bg3se/assets/132586844/dfef202b-f4a1-4e8a-8bbe-2e8976070257)
but the mod manager does detect it for me

It used to work for me but I uninstalled the game and reinstalled it and it stopped working

**Comment by halaziay** [comment]
I'm having the same issue yesterday everything worked for me but a smal update of the game made me i did like you and i reinstalled everything and i have this problem 😭

**Comment by Kylo213** [comment]
> Ayer tuve el mismo problema, todo funcionó para mí, pero una pequeña actualización del juego hizo que no funcionara, me gustaste y reinstalé todo y tengo este problema, pero en mi caso, los mods que necesitan un extensor de script no No trabajo 😭

So do I have to reinstall the game?

**Comment by halaziay** [comment]
> > Ayer tuve el mismo problema, todo funcionó para mí, pero una pequeña actualización del juego hizo que no funcionara, me gustaste y reinstalé todo y tengo este problema, pero en mi caso, los mods que necesitan un extensor de script no No trabajo 😭
> 
> So do I have to reinstall the game?

For me did nothing reintall it, before and after i have the error message

**Comment by Kylo213** [comment]
> I'm having the same issue yesterday everything worked for me but a small update of the game made it don't work, i did like you and i reinstalled everything and i have this problem but in my case mods that need script extender don't work 😭

So do I have to reinstall the game?

**Comment by shirogane5687** [comment]
exactly same problem, how should we fix it?

**Comment by MrPatchy** [comment]
Yep, I had my mods working a few days ago, haven't changed anything, and suddenly mods just don't work. Unfortunately I don't think it is even a SE issue, because non-script extender mods also don't work. Larian has fucked something, quite royally.

**Comment by shirogane5687** [comment]
I think its problem of SE, because when I use offline old version, it works fine

**Comment by SheeraDarkphoenix** [comment]
I can get most of the mods to work, just not all of them. I think once the Updater part is released, it might get the rest of them to work. I have the Script Extender with Console, and those work, just waiting for the updater part of it. All of my mods are updated, same with my mod managers. The mods I have, have always worked with the SE in the past, before the latest patch. When the Updater gets released, it may help with some of mods that used to work before, but don't now. We'll just have to wait and see.

**Comment by Kylo213** [comment]
> I can get most of the mods to work, just not all of them. I think once the Updater part is released, it might get the rest of them to work. I have the Script Extender with Console, and those work, just waiting for the updater part of it. All of my mods are updated, same with my mod managers. The mods I have, have always worked with the SE in the past, before the latest patch. When the Updater gets released, it may help with some of mods that used to work before, but don't now. We'll just have to wait and see.

how did you make it work?

**Comment by SheeraDarkphoenix** [comment]
I made sure to have everything updated, including both Mod Managers. Vortex is for mod updates, BG3MM is for everything else. The BG3MM has an option for both SE and the Updater. I downloaded the SE through both here and Nexus (for Vortex).  Downloaded the part with the console to go with the SE, so when I open the game with either Mod Manager, the console shows up. Vortex and BG3MM are able to use the same mod file as long as they're both set up that way in their Preferences/Settings. For those who use BG3MM, that is my suggestion. Use Vortex to make sure all of your mods are updated (Norbyte put up the suggestion to make sure that your mods are updated) and use BG3MM to keep the SE and the Updater updated.
After I started using both Mod Managers, both with the SE installed (Vortex also has LSLib/Divine that helps with the mods), I noticed a small improvement with collaboration. I am also trying to figure out what mods work and what don't, at the moment, until the complete release, because the Updater is just as important as the SE when it comes to adding the mods into the game. I am not very computer savvy, but I am decent at trying to figure out a puzzle.

**Comment by MrPatchy** [comment]
> I made sure to have everything updated, including both Mod Managers. Vortex is for mod updates, BG3MM is for everything else. The BG3MM has an option for both SE and the Updater. I downloaded the SE through both here and Nexus (for Vortex). Downloaded the part with the console to go with the SE, so when I open the game with either Mod Manager, the console shows up. Vortex and BG3MM are able to use the same mod file as long as they're both set up that way in their Preferences/Settings. For those who use BG3MM, that is my suggestion. Use Vortex to make sure all of your mods are updated (Norbyte put up the suggestion to make sure that your mods are updated) and use BG3MM to keep the SE and the Updater updated. After I started using both Mod Managers, both with the SE installed (Vortex also has LSLib/Divine that helps with the mods), I noticed a small improvement with collaboration. I am also trying to figure out what mods work and what don't, at the moment, until the complete release, because the Updater is just as important as the SE when it comes to adding the mods into the game. I am not very computer savvy, but I am decent at trying to figure out a puzzle.

I've tried both Mod Managers, the game doesn't detect any of my mods. I haven't changed a thing, I had them working friday. I went to play on sunday and none of my mods were detected anymore. Both mod managers detect them fine, but Script extender doesn't load them in the console, non-script extender mods also don't work.

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
