### ISSUE TITLE
take up too much C disk storage

### ISSUE THREAD

**Issue by Nguyen01010101** [Norbyte/bg3se#166]
Just curious, I have 2 "Larian Studios" files that contain the Script Extender log files (their storage is huge). So my question is, should I delete one of the "Larian Studios" file or the files in Script Extender Logs (please give me an answer if you're free)
If I'm doing anything wrong, pls point it out (I have >200 mods for BG3 so it might be a problem, I don't know.)
![image](https://github.com/Norbyte/bg3se/assets/151470545/c80bf8e9-74f2-4f09-b0bf-32aa59f3ecda)

**Comment by FallenStar08** [comment]
Check your bind folder and the file ScriptExtenderSettings.json, post its content if any.

**Comment by Norbyte** [comment]
^ This is caused by manually enabling Osiris runtime logging, which consumes a ton of space.
