### ISSUE TITLE
Script Extender Debug console doesn't finish loading

### ISSUE THREAD

**Issue by rlndhrnndo** [Norbyte/bg3se#168]
Script extender is only logging up to this line in execution when starting up BG3:

![image](https://github.com/Norbyte/bg3se/assets/31855744/cfaa7d5e-777d-485d-88f7-0ac37370dfeb)

And I get this error message when I try to run commands:

![image](https://github.com/Norbyte/bg3se/assets/31855744/f563e23b-f30c-471f-8bd1-c2335892cb5c)

Mods that rely on Script Extender still work fine, but I'm unable to do any console commands.

I'm trying to go through Act 3, and it's nigh unplayable with all the civilian events in queue that are waiting to be processed. I'm basically stuck as every step I do lags the civilians and AI companions. I ws following this reddit thread for Act 3 delay temp fix: https://www.reddit.com/r/BaldursGate3/comments/17shjen/fix_for_act_3_delay_bug_pc_only/ but I can't do it due to the debug console not loading completely.

I tried restarting BG3, Mod Manager, reinstalling Script Extender, restarting the whole PC. But no dice. Still very inconsistent with initializing the Script Extender debug console. Reaching out if anyone knows how to remediate this.

**Comment by archiezhie** [comment]
Same problem here, I don't think Mods that rely on SE work at all. Tried devel 10.0 version too, same issue.
But when I rollback the game to pre patch 4 and SE to 8.0, everything works fine.

**Comment by rlndhrnndo** [comment]
Some mods that rely on SE is working fine (Party Limit Begone, 5e spells, feats extra). But some doesn't work (Minthara mod, Appearance Edit on hotbar, Camp Events)

**Comment by SquishyVhenan** [comment]
glad to see that someone else is having this bug, i feel less crazy. hope it gets fixed soon

**Comment by Mahayu** [comment]
For me it was solved like this:
A windows with title that "Data missmatch " will pop up booting the game, just tick the block "Dont show this mesage again", then everything back to normal.

**Comment by rlndhrnndo** [comment]
Didn't work for me @Mahayu thanks for recommending a remediation though. :)

**Comment by sonder-joker** [comment]
Work after turn off my network.

**Comment by Norbyte** [comment]
This should be fixed in the latest v10 version.

**Comment by rlndhrnndo** [comment]
@archiezhie, having the same issue. Reverted back to the version before the latest and script extender doesn't initialize anymore, but I can load saves again.
![image](https://github.com/Norbyte/bg3se/assets/31855744/7c68c850-4c67-4d31-92cd-09127f217213)

**Comment by rlndhrnndo** [comment]
Also, not working in multiplayer when I try to create a lobby. BG3 closes by itself

**Comment by rlndhrnndo** [comment]
It's now working great. Thanks @Norbyte
