### ISSUE TITLE
Error using Script Extender(Steam)

### ISSUE THREAD

**Issue by DarkestDusk** [Norbyte/bg3se#17]
Do you have any idea why when following the script extender steps of extracting the DWrite.dll to my bin folder, and then adding
WINEDLLOVERRIDES="DWrite.dll=n,b" PROTON_NO_ESYNC=1 %command%
to my launch options on steam, I then get this error code?
It says, "Windows cannot find 'WINEDLLOVERRIDES=DWrite.dll=n,b' Make sure you typed the name correctly, and then try again".
It makes me be unable to use your Script Extender, and I would like to use it to enable some mod(s). Thank you!

**Comment by 3phedra** [comment]
The release page specifically states to not do this on Windows. This is needed for Linux.

**Comment by Norbyte** [comment]
^ See above.
