### ISSUE TITLE
Disable Auto Update and roll back to previous versions?

### ISSUE THREAD

**Issue by Arkmenhah** [Norbyte/bg3se#170]
v10 is making some mods malfunction, and I'd like to roll back to v9 where they worked without any issues.

--------------------------
EDIT SOLVED:

> For reference, you can specify target extender version in build in BG3MM, on the Script Extender settings panel.

You do that by activating Developer Mode on the Script Extender tab, and then on the newly created Updater tab.

**Comment by Kurmudge** [comment]
Agreed. While I appreciate the hard work being done, the fact that we can't control which version we're using is a bit...odd. 10 does break some significant and popular mods, without warning, and I would appreciate being able to manually control which version of bg3se is installed on my system pending modders catching up with evolving events.

**Comment by Norbyte** [comment]
For reference, you can specify target extender version in build in BG3MM, on the Script Extender settings panel.

**Comment by Mars1310** [comment]
I looked in the settings panel but I can find no such tab or anything that mentions the script extender.

**Comment by Ani-ki** [comment]
I'm unfortunately a filthy Vortex user (I'll get better I promise ~~I'm just lazy~~) so is there an efficient way to roll back?

**Comment by Norbyte** [comment]
@Mars1310 Should be here:
![image](https://github.com/Norbyte/bg3se/assets/2243424/7c3fe4af-43ce-4ed6-925b-b197db221a13)
