### ISSUE TITLE
Some character "conditions" missing after latest update

### ISSUE THREAD

**Issue by symphonymarie** [Norbyte/bg3se#172]
This is a bit of a weird one. On one of my games, my character has lost nearly all of her permanent conditions, i.e. the Mind Barrier you get from talking to the brain-in-a-jar. I have two other playthroughs, which seem unaffected. I suspect it might have something to do with getting downed but I can't be sure, that's just the only difference that comes to mind. I just completed the Raphael fight, so it's also possible it's related to that? If so, my suspicion is it would have something to do with his Soul-Stealing ability getting cleared post-combat. (Perhaps this is a new game bug rather than BG3SE? I haven't had this happen before after this battle on previous games.)

Let me know if there is somewhere I should look for a relevant log file and I'll post it!

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
