### ISSUE TITLE
How to resurrect Laezel using an Osi call in the console?

### ISSUE THREAD

**Issue by austin98jr** [Norbyte/bg3se#174]
I have called Osiris within the console by running the following command:
Osi.DB_PartyMembers(“S_Player_Laezel_58a69333-40bf-8358-1d17-fff240d7fb12”)

And no updates to the db are made. I confirmed by re-saving and checking the db afterwards and I still see no updates. Can anyone help with this?

I am trying to add laezel into my party so I can resurrect her as she died outside of my party. Any help on how I can do this would be very helpful. I would also be open to just resurrecting laezel with a call.

**Comment by austin98jr** [comment]
I am trying to add laezel into my party so I can resurrect her as she died outside of my party. Any help on how I can do this would be very helpful.

**Comment by SwissFred57** [comment]
about
Osi.Resurrect(character, resurrectAnimationOverride, resetXPReward)

**Comment by Donolm** [comment]
Using Osi.Resurrect(S_Player_Laezel_58a69333-40bf-8358-1d17-fff240d7fb12, resurrectAnimationOverride, resetXPReward) I'm getting an error below

[string "Osi.Resurrect(S_Player_Laezel_58a69333-40bf-8..."]:1: malformed number near '40bf'

Any suggestions on what I'm doing wrong?

**Comment by SwissFred57** [comment]
must be in quotes ""
"S_Player_Laezel_58a69333-40bf-8358-1d17-fff240d7fb12"

**Comment by Donolm** [comment]
Yep tried that, I get 
[string "Osi.Resurrect("S_Player_Laezel_58a69333-40bf-..."]:1: String expected for argument 3, got nil
stack traceback:
        [C++ Code]: in field 'Resurrect'
        Osi.Resurrect("S_Player_Laezel_58a69333-40bf-8358-1d17-fff240d7fb12", resurrectAnimationOverride, resetXPReward):1: in main chunk
        
Now if I use Osi.Resurrect("58a69333-40bf-8358-1d17-fff240d7fb12") she comes back, but I can't interact with her. Her quest is closed, not sure if that has something to do with it.

**Comment by SwissFred57** [comment]
the correct call is like this

---@overload fun(character:CHARACTER)
---@param character CHARACTER
---@param resurrectAnimationOverride ANIMATION
---@param resetXPReward integer
function Osi.Resurrect(character, resurrectAnimationOverride, resetXPReward) end

Osi.Resurrect("S_Player_Laezel_58a69333-40bf-8358-1d17-fff240d7fb12", "", 100)

for 100 reward XP

**Comment by Donolm** [comment]
Splendidly Osi.Resurrect("S_Player_Laezel_58a69333-40bf-8358-1d17-fff240d7fb12", "", 100) did bring her back, at level 4, which is where we're at... still can't talk to her though which is annoying. Not trying to be difficult, just trying to learn.

**Comment by SwissFred57** [comment]
you could try

Osi.AddToParty("58a69333-40bf-8358-1d17-fff240d7fb12", GetHostCharacter())

**Comment by Donolm** [comment]
No luck, tried that and

osi.MakeNPC("S_Player_Laezel_58a69333-40bf-8358-1d17-fff240d7fb12")
osi.SetHasDialog("S_Player_Laezel_58a69333-40bf-8358-1d17-fff240d7fb12", 1)
osi.SetOnStage("S_Player_Laezel_58a69333-40bf-8358-1d17-fff240d7fb12", 1)

All gave me errors, shame but that's what I get for letting her die by mistake.

**Comment by SwissFred57** [comment]
some calls are using the UUID
try 
osi.MakeNPC("58a69333-40bf-8358-1d17-fff240d7fb12")
osi.SetHasDialog("58a69333-40bf-8358-1d17-fff240d7fb12", 1)
osi.SetOnStage("58a69333-40bf-8358-1d17-fff240d7fb12", 1)
