### ISSUE TITLE
Script extender not found when having game and extender on different drives

### ISSUE THREAD

**Issue by sam-fisco** [Norbyte/bg3se#175]
Game is installed on a separate drive as the mods files and the bin folder. Adding the DWrite.dll file into the steam. Adding the DWrite.dll file to the Script Extender path below resolved the issue. 

Mod folder path: C:\Users\[user]\AppData\Local\Larian Studios\Baldur's Gate 3\Mods
Bin folder path: C:\Program Files (x86)\Steam\steamapps\common\Baldurs Gate 3\bin
Script Extender Path: C:\Users\[user]\AppData\Local\BG3ScriptExtender\ScriptExtender

**Comment by IkaTheFox** [comment]
Can confirm that when the path is not `C:\Program Files (x86)\Steam\steamapps\common\Baldurs Gate 3\bin` the script extender is not loaded. Installing the game in this specific location seems to fix the issue as long as it remains there. 
Curiously it seems to work anyways when using Vortex, but not when using the BG3 Mod Manager, which is a shame when your use case needs specifically to use the latter.

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
