### ISSUE TITLE
Bg3se version 10 causes game to crash on loading save

### ISSUE THREAD

**Issue by Vektor8298** [Norbyte/bg3se#176]
After the script extender updated yesterday (11/26) the game began to crash on loading/creating a new save file. I play on Linux, and I haven't been able to get crash logs from the script extender. I tried enabling all logs as per the docs, and the OsirisLog only shows a "Delete All Data" or something like that.

**Comment by Norbyte** [comment]
Can you try with this version:
[BG3SE-Updater-TB-20231127.zip](https://github.com/Norbyte/bg3se/files/13480438/BG3SE-Updater-TB-20231127.zip)

**Comment by Vektor8298** [comment]
> Can you try with this version: [BG3SE-Updater-TB-20231127.zip](https://github.com/Norbyte/bg3se/files/13480438/BG3SE-Updater-TB-20231127.zip)

Thanks for the quick reply! It does not start now, 
`951.019:0120:0130:err:sync:RtlpWaitForCriticalSection section 000000017006F4C0 "../src-wine/dlls/ntdll/loader.c: loader_section" wait timed out in thread 0130, blocked by 0124, retrying (60 sec)`

**Comment by Norbyte** [comment]
There is an SE bug where none of the module-level scripts and overrides will run if SE is loaded too late.
This bug causes some SE changes to not load at all in v9, and is partially worked around in v10.
There should be a further workaround added with todays patch that should resolve crashing.
In addition, an updated launcher will be released to ensure that the game always waits for SE loading to complete before proceeding.

**Comment by Vektor8298** [comment]
Dear @Norbyte, game work 100% now, after the update, thanks a lot!
