### ISSUE TITLE
Transmog mod incompatibility

### ISSUE THREAD

**Issue by TheDiamondFox42** [Norbyte/bg3se#177]
Unsure if I should post this here or not, but the Dev for the mod in question is quitting modding, so I thought I'd post it here. Currently the mod is unusable, with its transmog system replacing armor instead of designing it. As such, is there a potential fix to the mod that you guys can implement?

Mod link: [Transmog Mod](https://www.nexusmods.com/baldursgate3/mods/2922?tab=description)

**Comment by Millerm92** [comment]
Yeah this is my favorite mod, would love to have it fix. Looking into alternatives

**Comment by Norbyte** [comment]
Transmog has since been updated, closing
