### ISSUE TITLE
Can't listen to Events

### ISSUE THREAD

**Issue by Nerhak** [Norbyte/bg3se#179]
Hi,

I only started modding using the script extender this way today so I might have made mistakes.

I was trying to listen for every events, to find hooks. The Readme tells us to write:

```
Ext.Events.GameStateChanged:Subscribe(function (e)
  _P("State change from " .. e.FromState .. " to " .. e.ToState)
end)
```

but once loaded I get this log

[Extender Runtime 2023-11-29 19-28-17.log](https://github.com/Norbyte/bg3se/files/13504755/Extender.Runtime.2023-11-29.19-28-17.log)

Multiple things seems to not work as intended, 

"
bg3se::esv::lua::OsirisBinding::StoryLoaded(): Not all identity adapters are available - some queries may not work!
bg3se::OsirisWrappers::ResolveNodeVMTsInternal(): Could not locate all Osiris node VMT-s
"

Doesn't seem right, and it doesn't want me to concatenate ToState.
And when doing a new game, I end up in some sort of debug mod with 3 black dudes, 3 whites dudes and dark urges in the center.

If I modify the code to 

```
-- Event Listener
Ext.Events.GameStateChanged:Subscribe(function (e)
  _P("State change from ")
  _P(e.FromState)
  _P(" to ")
  _P(e.ToState)
end)
```

I see States, but I end up still on the debug map with the 7 npcs...

**Comment by Norbyte** [comment]
This was an early bug in older SE versions that has been fixed for a long time now, closing.
