### ISSUE TITLE
No console?

### ISSUE THREAD

**Issue by Sylaous** [Norbyte/bg3se#18]
I download script extender w/ console, but get no console when running the game? How do I open it?

**Comment by paul-m-williams** [comment]
Add file to /bin dirrectory... ScriptExtenderSettings.json

Contents of File...
`{
  "CreateConsole": true
}`

**Comment by Zrylhh** [comment]
I have same problem, just download [BG3SE-Updater-wConsole-v1.zip](https://github.com/Norbyte/bg3se/releases/download/updater-v1/BG3SE-Updater-wConsole-v1.zip) and extract into /bin dirrectory (already have ScriptExtenderSettings.json), but get no console when running the game.

How to get some log ?

**Comment by Zrylhh** [comment]
> I have same problem, just download [BG3SE-Updater-wConsole-v1.zip](https://github.com/Norbyte/bg3se/releases/download/updater-v1/BG3SE-Updater-wConsole-v1.zip) and extract into /bin dirrectory (already have ScriptExtenderSettings.json), but get no console when running the game.
> 
> How to get some log ?

Sorry, it works after reboot my pc.

**Comment by Sylaous** [comment]
> 

I have that already . Still no go.

**Comment by Sylaous** [comment]
[https://github.com/Norbyte/bg3se/issues/18#issuecomment-1699973596](url)
Already have that. Still no go.
