### ISSUE TITLE
Kisses and some other cutscenes are broken (s3 v11, dec1 build)

### ISSUE THREAD

**Issue by Anarios** [Norbyte/bg3se#183]
I just got the latest version of SE (v11, december 1 build) - and my kisses and some endgame cutscenes are still broken.

On a fresh save without any mods - all seems to work fine.

Can't disable mods in my "main" save as it simply doesn't load with mods disabled (I tried dropping all items created\modified by mods - didn't help, do I need to destroy them somehow?)

Anything I can do to debug this? 

Anything I can do to "clear" the mod from save and make it loadable without mods?

**Comment by Anarios** [comment]
May be dropping "mod" items is not enough, and I should destroy them somehow? (drop in chasm?)

**Comment by iiiisy** [comment]
> I just got the latest version of SE (v11, december 1 build) - and my kisses and some endgame cutscenes are still broken.
> 
> On a fresh save without any mods - all seems to work fine.
> 
> Can't disable mods in my "main" save as it simply doesn't load with mods disabled (I tried dropping all items created\modified by mods - didn't help, do I need to destroy them somehow?)
> 
> Anything I can do to debug this?
> 
> Anything I can do to "clear" the mod from save and make it loadable without mods?

You can't remove any mods. I tried to remove tactician plus and unique tav (which can be removed without affecting the save loading) but after the update, I can't remove the mods because the save doesn't load.

**Comment by iiiisy** [comment]
> Enabling-disabling mods several times and loading into different saves seems to have fixed it for me somehow.
> 
> I loaded into main save, a bunch of inspirations appeared for some reason - and after that everything seems to have started working fine.

I'll try this, I'm very disappointed that I can't load my save without the broken mod.

**Comment by Anarios** [comment]
Oh, I have to clarify - after these permutations I was able to load **with** the mods enabled. But the problem with cutscenes is gone now. The indicator that everything "worked" for me is that I get a bunch of inspirations right after loading.
