### ISSUE TITLE
After the new patch 5 the game will not load older saves

### ISSUE THREAD

**Issue by Scarlett718** [Norbyte/bg3se#185]
None of my save files that I created after installing Script Extender will open after patch 5. I press load but either nothing happens, or it loads a save from another character that I didn't play since installing the Extender. Tried uninstalling the game, uninstalling the Extender, updating it. Checked both with mods and without, the issue persists.

**Comment by DankSinatraSr** [comment]
Same here the SE just needs to be updated to the game's current build: patience.

> None of my save files that I created after installing Script Extender will open after patch 5. I press load but either nothing happens, or it loads a save from another character that I didn't play since installing the Extender. Tried uninstalling the game, uninstalling the Extender, updating it. Checked both with mods and without, the issue persists.

**Comment by sonofthunder77** [comment]
I'm just going to add that I think I'm having the same issue as well. I'll give it time, as I can see it was last worked on this morning. My saves just don't load right now.

**Comment by 7Rainbow13** [comment]
I'm in the same boat. Had to remove the script extender entirely to access my unmodded saves. Still can't access my previous modded saves tho. Hopefully, a fix will be out soon.

**Comment by Norbyte** [comment]
As far as I know this is a vanilla game bug, not an SE bug. I get the same with old saves modded where clicking Load does nothing, with and without SE. Strangely, loading a different unmodded save first then loading the modded save in question will work.

**Comment by Scarlett718** [comment]
I figured it out - in my case I reinstalled the game, updated SE, made sure I exported back ALL my mods - the saves wouldn't work even if just one mod was missing. It works correctly now.

**Comment by sonofthunder77** [comment]
Thanks for the feedback and all your hardwork Norbye

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
