### ISSUE TITLE
Does script extender include mod fixer now?

### ISSUE THREAD

**Issue by azulaisasnack** [Norbyte/bg3se#186]
question in the title. I saw many of my mods start removing mod fixer and was curios Thanks!

**Comment by DragonKumera** [comment]
neat!

**Comment by WakeXT** [comment]
Is the actual implementation different in some way?
Seems to have two behaviors when trying to start a new game with some UI-mods and Script Extender v12 installed

when Modfixer is disabled in Vortex I get Durge surrounded by the naked army in LSD-land:
https://i.imgur.com/IkJFufB.jpg

when Modfixer is enabled in Vortex I get a message popup about Script Extender loading during the intro movie and can create new characters just fine:
https://i.imgur.com/WwVt05i.png
https://i.imgur.com/ZzKVHll.png

**Comment by Norbyte** [comment]
For reference, it still does not include mod fixer as of v16.
