### ISSUE TITLE
weird profile sidebar

### ISSUE THREAD

**Issue by kanra2** [Norbyte/bg3se#187]
![20231202150158_1](https://github.com/Norbyte/bg3se/assets/152713104/6389b623-e6d3-412b-9386-4166a69f15c2)
I'm using a test character because I can't acess any of my saves. I removed all mods except the script extender and replacers and this issue only disappears if I remove the DWrite.dll file

is this because the script isn't fully updated or is it a different problem?

**Comment by DankSinatraSr** [comment]
The SE is not compatible with patch 5, but Norbyte refuses to admit it, so it may be a while before it's fixed.

**Comment by kanra2** [comment]
> The SE is not compatible with patch 5, but Norbyte refuses to admit it, so it may be a while before it's fixed.

it is just a bit..I actually managed to enter the game after it updated just bit but I can wait for it to fully update, I'll play on the test save or put time in other games for a while

**Comment by Norbyte** [comment]
This happens if either ImprovedUI or ImprovedUI Assets were not updated to their latest version that fixes Patch 5 incompatibilities.

**Comment by Norbyte** [comment]
> The SE is not compatible with patch 5, but Norbyte refuses to admit it, so it may be a while before it's fixed.

Thanks for the valuable insight, now I know that it is incompatible with patch 5, I must have been delusional the last few days but now that you mentioned that it is indeed patch 5 incompatible I'm beginning to sober up and see the truth ™. Thanks fellow Github user for starting me down on the path to enlightenment.

**Comment by Norbyte** [comment]
Do you have ImprovedUI Assets as well?

**Comment by Norbyte** [comment]
Well, what you can do is try removing dwrite.dll and see if the sidebar issue goes away afterwards.
If it doesn't, its 100% not a SE issue

**Comment by kanra2** [comment]
> Well, what you can do is try removing dwrite.dll and see if the sidebar issue goes away afterwards. If it doesn't, its 100% not a SE issue

as I said in my initial post the problem only goes away if I remove the dwrite.dll file

**Comment by kanra2** [comment]
> Does it happen on new saves, or only existing ones? Can you upload all your mod .paks and your modsettings.lsx somewhere for testing?

https://drive.google.com/file/d/1-sqXagwsDB9bX3Edkj5tVNyrn_pnzHaL/view?usp=sharing here the mods I have and the lsx file!! I have been trying to access my modded saves but nothing happens and even the time played doesn't match my 90th quick save has 95 hours of playtime and the 91st has 41 minutes for some reason

**Comment by yawor666** [comment]
> https://drive.google.com/file/d/1-sqXagwsDB9bX3Edkj5tVNyrn_pnzHaL/view?usp=sharing here the mods I have and the lsx file!! I have been trying to access my modded saves but nothing happens and even the time played doesn't match my 90th quick save has 95 hours of playtime and the 91st has 41 minutes for some reason
some mods reset playtime, happed even before patch 4. i think patch 4 did also reset my playtime

**Comment by kanra2** [comment]
> > https://drive.google.com/file/d/1-sqXagwsDB9bX3Edkj5tVNyrn_pnzHaL/view?usp=sharing here the mods I have and the lsx file!! I have been trying to access my modded saves but nothing happens and even the time played doesn't match my 90th quick save has 95 hours of playtime and the 91st has 41 minutes for some reason
> 
> some mods reset playtime, happened even before patch 4. i think patch 4 did also reset my playtime

hmm...didn't know that!!

**Comment by cdubwisdom** [comment]
I am currently seeing the same issue. Any ideas or updates?

**Comment by kanra2** [comment]
> I am currently seeing the same issue. Any ideas or updates?

No.. It was bugged yesterday and today after I spent hours re adding all my mods 1 by 1 again it was OK! I changed nothing!

**Comment by cdubwisdom** [comment]
I only have like five mods in my game, but I cant remove any as I get the "Missing Mods" Prompt that is currently bugged and wont load my save when I select continue anyway.

When you say you re-added your mods, did you just remove them from the mod manger and redownload them from Nexus ir where ever?

**Comment by kanra2** [comment]
> I only have like five mods in my game, but I cant remove any as I get the "Missing Mods" Prompt that is currently bugged and wont load my save when I select continue anyway.
> 
> When you say you re-added your mods, did you just remove them from the mod manger and redownload them from Nexus or where ever?

I didn't redownload them...I just removed all of them from the load order of the mod manager, checked the modsetting file to see if it was empty and then added 1 mod logged in a not modded save and repeat until all of them where back in the load order
