### ISSUE TITLE
Not auto-updating

### ISSUE THREAD

**Issue by Ralinor** [Norbyte/bg3se#188]
Since BG2MM was saying that I was still running v6 and nothing seemed to change that, I deleted the BG3ScriptExtender folder from appdata/local. I deleted the DWrite.dll file from the /bin folder of the game and extracted what is currently here (I realize they were probably the same file).
I am running the game on steam and it is up to date.
After the first launch of the game, I have an empty BG3ScriptExtender folder back where the original was. Upon relaunching the game, I am continuing to get "No extender version found for game version v4.40.79.877
The FAQ points to there being an issue with me running an old version of the game, but that is not the case. Also, BGMM is also not detecting script extender.
There seem to be no issues with security around the dll file and regsvr indicated this is not a registerable dll (not that I'd had to before, but I'm trying everything I can think of).

Please help.

**Comment by Norbyte** [comment]
Check if you have a `ScriptExtenderUpdaterConfig.json` in your BG3 bin folder, if its configured incorrectly it can cause the updater to stick to a particular game version.
