### ISSUE TITLE
BG3 mod manager says my script extender is missing.... it's not

### ISSUE THREAD

**Issue by thotodile** [Norbyte/bg3se#189]
Per title, downloaded BG3 mod manager and this script extender. Patch 5 is downloaded. Put DWrite.dll in the bin folder just like the directions said and then I installed the most recent 5e spells mod and imported it into the manager, and now I'm getting the error that it's missing the script extender. I tried rebooting the mod manager, didn't work. I tried refreshing the mod manager. Didn't work. Exported to game anyways, and the mod manager said it wouldn't work without the script extender and to go to the tools drop down menu and click on download & extract script extender. So, I did that and that didn't work. not sure if this is a mod manager problem, a 5e spells problem, or a script extender problem but I'd greatly appreciate some help.

**Comment by DanielK1511** [comment]
same issue here

**Comment by elenaleegold** [comment]
> EDIT: I just ignored it and started playing, and the mod seems to be working.
> 
> I'm seeing the same issue on my Steam Deck - trying to load the NoRomanceLimit mod.
> 
> I've followed the steps to add the Script Extender, and loaded the game, but BG3MM still shows Script Extender as missing ([MISSING] Requires ScriptExtender v4 or higher. No installed extender version found.).
> 
> I can confirm that DWrite.dll is in the /bin folder in the correct location, and the Launch Option has been updated.
> 
> After seeing the error I also tried to add it from Tools, but am seeing no changes.
> 
> Any other suggestions?

Hey! Having the exact same issue with NoRomanceLimit. How can you tell the mod seems to be working for you?

**Comment by emryseon** [comment]
I am experiencing this same problem, and I have no clue how to fix it. I installed it directly from the website, then tried installing from BGMM, both to no avail. I have opened the game multiple times to attempt to let it create the files it needs. BGMM still states that the script extender is missing. Any ideas would be appreciated!

**Comment by aaronsprofession** [comment]
Having the same issue so any support would be appreciated!

**Comment by A-Kader94** [comment]
Same issue here aswell

**Comment by Aetheriussama** [comment]
Same issue here 
Any updates?

**Comment by oldmansutton** [comment]
This was literally answered in the second comment.

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.

**Comment by WaluigisGayBoyfriend** [comment]
Hi Hi!!!!! I think I JUST managed to figure out the solution/fix for this for everyone whose not seen a change even after the first suggestion someone gave!!!
I went to export the mods to my game and it gave the pop up it usually does saying which mods were missing script extender and what not and you can tell it "Ok", to copy the mod names to clipboard, or to remove the "broken" or whatnot mods- and my ADHD ass FINALLY just processed the note on the pop up that also says to use the Tools menu to install the mod- so I went to the Tools bar to see what options show up- and one option is "Download & Extract the Script Extender..." 
And even though I also definitely have it downloaded and extracted where it should be- I figured "Why not?" and selected the option from the Tools menu, and it made me reconfirm thats what I wanted to do- and then the Mod Manager proceeded to "download and extract" Script Extender on its own, and immediately all the warnings on my mods saying that it was missing, disappeared-

SO LONG ANSWER SHORT- 
even if you do have the script extender installed, use the mod managers "Tools" menu bar at the top to have the manager find and "reinstall" the script extender on its own.

**Comment by Teasinglewis999** [comment]
> Hi Hi!!!!! I think I JUST managed to figure out the solution/fix for this for everyone whose not seen a change even after the first suggestion someone gave!!! I went to export the mods to my game and it gave the pop up it usually does saying which mods were missing script extender and what not and you can tell it "Ok", to copy the mod names to clipboard, or to remove the "broken" or whatnot mods- and my ADHD ass FINALLY just processed the note on the pop up that also says to use the Tools menu to install the mod- so I went to the Tools bar to see what options show up- and one option is "Download & Extract the Script Extender..." And even though I also definitely have it downloaded and extracted where it should be- I figured "Why not?" and selected the option from the Tools menu, and it made me reconfirm thats what I wanted to do- and then the Mod Manager proceeded to "download and extract" Script Extender on its own, and immediately all the warnings on my mods saying that it was missing, disappeared-
> 
> SO LONG ANSWER SHORT- even if you do have the script extender installed, use the mod managers "Tools" menu bar at the top to have the manager find and "reinstall" the script extender on its own.

Thanks worked for me

**Comment by Sio8888** [comment]
I have the same problem and no, even downloading the extender from the tools option did not fix it. I start the game, no sign of script extender. MM says its missing. I also have the file dwrite manually in the bin folder.

**Comment by mackmcd** [comment]
> I have the same problem and no, even downloading the extender from the tools option did not fix it. I start the game, no sign of script extender. MM says its missing. I also have the file dwrite manually in the bin folder.

Exact same here. Only trying to use CYS potions, and ignoring the error is not solving the problem. The mod still doesn't work.

**Comment by Amaelia** [comment]
Anyone else still getting this error after all this time? I tried to go to tools and download it. I manually installed it and opened BG3. But a mod I downloaded said extender isn’t recognized even tho when I load up bg3 it shows up in the bottom left corner
