### ISSUE TITLE
Game now crashes when I try to load a moded save.

### ISSUE THREAD

**Issue by Taylor-Tauscher** [Norbyte/bg3se#190]
After the most recent patch the game now crashes whenever I try to load my moded save. I have the SE up to date, all mods I was using in the run are installed, and I can still load all my other unmoded saves, but whenever I try to load my moded one the game crashes once the progress bar reaches 75%.

**Comment by kanra2** [comment]
> After the most recent patch the game now crashes whenever I try to load my moded save. I have the SE up to date, all mods I was using in the run are installed, and I can still load all my other unmoded saves, but whenever I try to load my moded one the game crashes once the progress bar reaches 75%.

mine if I'm in the main menu doesn't even load and if I'm in an unmodded save and try to load the modded save it loads me back to the unmodded save

**Comment by ningzo** [comment]
> After the most recent patch the game now crashes whenever I try to load my moded save. I have the SE up to date, all mods I was using in the run are installed, and I can still load all my other unmoded saves, but whenever I try to load my moded one the game crashes once the progress bar reaches 75%.

did you find a solution to this? I'm having the exact same problem crashing at 75% loading. I'm not sure why it's happened, but when I make a new game it works fine and I can load the new save no problem, with the exact same mods - SE mods seem to be working fine too (except transmog but that's a known issue). the crashing seems to be only affecting my pre-patch 5 old saves.

**Comment by kanra2** [comment]
> > After the most recent patch the game now crashes whenever I try to load my moded save. I have the SE up to date, all mods I was using in the run are installed, and I can still load all my other unmoded saves, but whenever I try to load my moded one the game crashes once the progress bar reaches 75%.
> 
> did you find a solution to this? I'm having the exact same problem crashing at 75% loading. I'm not sure why it's happened, but when I make a new game it works fine and I can load the new save no problem, with the exact same mods - SE mods seem to be working fine too (except transmog but that's a known issue). the crashing seems to be only affecting my pre-patch 5 old saves.
> 
> have clean reinstalled the game, deleted and updated all my mods, still no luck.

same!!

**Comment by novaepee** [comment]
same here; having issue with loading a modded save at 75%. 

i subverted this initially by saving in act 1's forest. in act's 1 rosemary trail and act 2's shadow cursed land, i cannot load these without crashing at 75%

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
