### ISSUE TITLE
does not work with patch 5

### ISSUE THREAD

**Issue by Rose-9003** [Norbyte/bg3se#191]
I have tried absolutely everything despite the FAQs saying this is working with patch 5 it must not be, I've tried with and without all my other mods and the script extender is the issue. I try to load a save with SE installed and the game crashes, giving me an error message about the SE. Am I the problem?

**Comment by Kvalyr** [comment]
Script Extender works fine with Patch 5. The issue lies somewhere within your setup.

I wouldn't go as far as to say that **you're** the problem, as you suggest; but I can say for sure that Script Extender is not the problem.

**Comment by Rose-9003** [comment]
How could you say it works fine when it is the reason the game is crashing because the error message states that. I have tried it completely vanilla except SE and it still crashes and sends the same error. I was hoping for some real feedback and help. Thanks anyway though.

**Comment by JosephBelmont** [comment]
Is this the error that you see? 
![image](https://github.com/Norbyte/bg3se/assets/152820083/28c8cbe2-1653-4aa0-8cad-42843da868ca)

**Comment by Rose-9003** [comment]
Yes that was the error that was showing up for me, the reason that I didn't show the error message was because i never ss it initially and now I honestly don't want to risk putting the SE back in because so many people are losing saves and I don't want to risk that just to get the error message again.

**Comment by Rose-9003** [comment]
I tried deleting and redownloading the SE manually and through the bg3 mod manager several 100 times lol. Nothing works so I am simply giving up thanks ya'll.

**Comment by JosephBelmont** [comment]
Don’t give up. I’m facing the same problem as you and I don’t want to corrupt my save with boggus fixes or by download previous versions of mods (I even lost count of which version to download for x or y mod). The only solution now is to wait for an update.

**Comment by Rose-9003** [comment]
Yeah I'll try that out I don't know why it wasn't self updating, I wish it would say somewhere what version it's on because I've been running SE since V6 I believe, and I have an issue with it every time there's a new patch/hotfix. Thank you so much for the feedback.
![Screenshot (2)](https://github.com/Norbyte/bg3se/assets/152760391/0aa8ac56-1b91-4cb7-9e06-38fb33fb33ed)
 :)
