### ISSUE TITLE
"No extender version found for game version v4.40.61.76"

### ISSUE THREAD

**Issue by poppci** [Norbyte/bg3se#197]
![image](https://github.com/Norbyte/bg3se/assets/153003412/c64835ec-ee8b-4cee-891d-ee4b4829229a)

What it says on the box. Not sure exactly how to go about fixing this. 

Downloaded scrip extender via BGMM, set updates to release and latest, but its still giving me this error. Game seems to play through, ok, but I've no access to the patch #5 epilogue content and have a scene missing from the end. IDK if SE is even the way to resolve the greater issue? Sorry if that ends up totally unrelated.

Is this something I'm going to have to wait to be updated to resolve?

**Comment by YC-dude** [comment]
Go to C:\Users\USER\AppData\Local\BG3ScriptExtender\ScriptExtender and delete everything that exists in there launch the game again twice and it should give you the current version.

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
