### ISSUE TITLE
'requires script extender v1 or higher (current version is v11)'

### ISSUE THREAD

**Issue by morrysillusion** [Norbyte/bg3se#198]
this problem has actually been present since i kinda started using mods but everything has run just fine and so i never thought about it. however with some patch 5 issues arising im trying to check out all potential issues and i thought i might as well come here to report this. and see if there is any solution.

this message appears next to some mods on my mod list. sometimes is v2 or another. i loaded up the game with the console and it also says v11 but, for some of these mods they arent loading despite having a newer version.

(edit fixed a typo. also tried to clarify i mean that the mods with those notices arent all loading in my save file)

**Comment by morrysillusion** [comment]
uhhh yes, im not sure if you read my posts totally correct. what im saying is some of those mods say that, and i do have the newest version, but regardless some of those mods are not loading in the game. i guess i didnt word specifically enough-- that the files dont seem to be reading the mods when i try to load up the files. because it is only some of them

**Comment by UruvielNaomi** [comment]
I have a similar notification: one of my mods says: requires script extender v2 or higher, you currently have v11. so not sure what thats showing.

**Comment by FeelFried** [comment]
> I have a similar notification: one of my mods says: requires script extender v2 or higher, you currently have v11. so not sure what thats showing.

that shows that mode requires SE v2 or above and YOU currently HAVE SE v11 and... 11 is ABOVE 2

**Comment by Morabert** [comment]
I've got the same issue
![firefox_GTB2K0SphZ](https://github.com/Norbyte/bg3se/assets/36409264/6263488a-c2a7-42ce-9523-7eaba6651395)
![firefox_kZ3vfM7yQg](https://github.com/Norbyte/bg3se/assets/36409264/44c45dfd-a2c2-414c-8b06-653151b9a403)

**Comment by morrysillusion** [comment]
^ this was the issue i was having, i think i was too unclear about that. sadly all i did recently after patch 5 was reinstalling my mods and reinstalling the script extender which made it stop.
