### ISSUE TITLE
Initial Installation

### ISSUE THREAD

**Issue by C0RLoCK** [Norbyte/bg3se#20]
Hi there, I just decided to install this, and noticed that the zip file for latest release only had the DWrite.dll in the ZIP. Is the scriptextendersettings file separate? Does it populate on its own after running the game? Any info would be appreciated, thank you.

PS: I'm only interested in the enabled achievements, so if this sitting is ON by default, then no worries.

**Comment by LaughingLeader** [comment]
`BG3SE-Updater-wConsole-v1.zip` is the release that comes with the json config file. Achievements are enabled by default.

**Comment by C0RLoCK** [comment]
Ah, thanks very much. My question has been answered, so I'll consider this issue resolved.  =)
