### ISSUE TITLE
Links not downloading current version

### ISSUE THREAD

**Issue by Manwith1d20s** [Norbyte/bg3se#201]
For whatever reason any and all links on here do not download the current v11 of the script extender, only the release from 10/28.  Verified through my mod manager it is not giving the correct version.

**Comment by sephlington** [comment]
Seconding. "Releases" has nothing newer than 10/28, and installing manually following the instructions and trying the BG3 Mod Manager (newly downloaded, v1.0.10.0) also fails to download a usable version - something before v5, if the error message in the mod manager is to be believed.

**Comment by JND94** [comment]
From FAQ:
```
The game was updated and there is no new extender download!

The Script Extender auto-updates; there is no new release on Github when a Script Extender update happens, the game will download and apply it automatically when launching.
When a new release is published on Github, it means there was a change in the updater, not the Script Extender itself.
```
I don't know if there is a technical reason behind doing it this way but it seems to me a rather questionable and shady way to approach it

**Comment by BelegCufea** [comment]
@Manwith1d20s 
Just use the release of downloader with console enabled. It will show on the first line, which version of BG3SE you have.

BTW the thingy you are downloading from this site is donwloader that installs/updates BG3SE in `%Appdatat%/Local/BG3ScriptExtender`.
