### ISSUE TITLE
Assertion Failed Linux

### ISSUE THREAD

**Issue by keyxmakerx** [Norbyte/bg3se#203]
Getting error on PopOS Linux. 

![Screenshot from 2023-12-10 13-19-39](https://github.com/Norbyte/bg3se/assets/2086621/62f5845e-3a2c-4165-ab28-ff8ab3bacc69)

**Comment by keyxmakerx** [comment]
Hm, Seems to happen if I use Vulkan, which I do get better performance on.

**Comment by Norbyte** [comment]
This seems to be a general VK compatibility issue, not an SE issue.
