### ISSUE TITLE
Modded achievements not working

### ISSUE THREAD

**Issue by TzachX** [Norbyte/bg3se#204]
Hi,
I just wanted to get the "2 birds, 1 gnome" achievement, saved before the situation in battle.
It didn't work for me, then I saw that there's no need of using the achievement enabler since the SE got it built in and it creates conflicts, so I removed it.
The console showed "Modded achievements enabled" so I thought it will work, but it didn't. Also tried to save again and use a new save, but it didn't work. Can anyone help?

**Comment by TzachX** [comment]
I checked progression of the Busker achievement on my character and it worked, so I'm quite confused about this particular achievement

**Comment by aeschiel** [comment]
Are all the other achievements not popping up as well? Because I thought I had the same issue before but turns out, I had to select **Improvised Melee** instead of **Throw** for the "2 Birds, 1 Gnome" achievement to get triggered lol
