### ISSUE TITLE
Console loading causes issues

### ISSUE THREAD

**Issue by Reyukka** [Norbyte/bg3se#205]
When the console json is in the bin folder it causes an issue where it will wipe the mod load order when Native Mod Loader, Native camera tweaks, or WASD movement is installed. Problem is fixed by removing json (attempted multiple times to be sure) but I thought it would be a good idea to report it.

**Comment by Malumen** [comment]
As an average user, is the console file necessary, or can I run most things without the console version?

**Comment by Reyukka** [comment]
You can run most things without the console. The only reason I had it in the first place was because one of my mods was requiring it as a step for it to work.
