### ISSUE TITLE
Steam Deck - Script Extender Mods not working

### ISSUE THREAD

**Issue by Avalon-Tzi** [Norbyte/bg3se#206]
Hey everyone,

I'm not sure I'm right here, but asking never hurt.
I've gotten the BG3 Mod Manager to work on the deck, works fine except for it telling me that there's no Script Extender installed, when the DWrite.dll is right where it's supposed to be.

Problem is, that none of the Script Extender requiring mods are working. Game starts just fine, they are in the modsettings.lsx too, they just don't work as if they were not there.

Does anyone have a clue what my problem might be?

**Comment by Norbyte** [comment]
Make sure you followed the Linux-specific part of the setup instructions here:
https://github.com/Norbyte/bg3se/releases/tag/updater-20231028

**Comment by Avalon-Tzi** [comment]
> Make sure you followed the Linux-specific part of the setup instructions here: https://github.com/Norbyte/bg3se/releases/tag/updater-20231028

Hello there.
Thanks, I now know what my mistake was, even though I don't understand it, so I'll post the whole mess here, to maybe help others xD

It USED to work without the Linux specific command as I installed mods on my PC and ported everything over with Syncthing.
Then I installed the mod manager directly on the deck and it didn't work at all anymore, deleted BG3 and reinstalled, didn't work again.
Linux specific commands? Didn't work.

I've now removed the skip launcher commands and whoosh, the Linux specific commands work. They seem to bite each other somehow, hope that can help someone else. :)
I don't know which Proton Version I use for BG3, but I can add that later, as I'm quite sure I don't use auto detect on the Deck anymore.

**Comment by Jfen101** [comment]
Hi, I'm having what seems to be the same issue. Installed on steam deck, other mods working but those reliant on SE won't work. I've stuck the Linux commands into the launch menu but they still won't work. I also don't have skip launcher commands that I put in myself, although steam does skip the launcher on its own.
Wondering if you can share anymore about your fox?

**Comment by Avalon-Tzi** [comment]
> Hi, I'm having what seems to be the same issue. Installed on steam deck, other mods working but those reliant on SE won't work. I've stuck the Linux commands into the launch menu but they still won't work. I also don't have skip launcher commands that I put in myself, although steam does skip the launcher on its own. Wondering if you can share anymore about your fix?

I have just looked into my Steam Deck and saw that I have no specific run configurations for BG3 except now the Linux command for the DWrite.dll.
