### ISSUE TITLE
No extender version found for game version v4.42.16.792

### ISSUE THREAD

**Issue by aksiiy** [Norbyte/bg3se#207]
![Безымянный](https://github.com/Norbyte/bg3se/assets/153871121/1f6f3e39-2029-49e6-92ba-6760d899175f)

Steam version of the game, latest update.
BGMM is also not detecting script extender.
Installing an alternative version without updates is worked. Mods are working.
https://bg3se-updates.norbyte.dev/Channels/Release/ManualInstall.zip
But BGMM continues to not detecting the script extender.

**Comment by Mars1310** [comment]
I have the same issue but with v4.42.51.417. I can use SE v11 but not 12.

**Comment by YC-dude** [comment]
Go to C:\Users\USER\AppData\Local\BG3ScriptExtender\ScriptExtender and delete everything that exists in there launch the game again and it should give you the current version.

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
