### ISSUE TITLE
install SE and occur low FPS, but mod run rightly

### ISSUE THREAD

**Issue by SHUJIANGCHUNSHUI** [Norbyte/bg3se#209]
When i didn't install mod and anything else I can play BG3 in middle picture quality ,  but after I install SE and related mods, the loading page show "Compiling shaders"(I didn't see it before I install SE and related mods), and the game shows very low FPS, but mods run rightly. Is my PC hardware can't afford mods or anything wrong with SE or mods?

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
