### ISSUE TITLE
Script Extender says it's installed, but isn't detected

### ISSUE THREAD

**Issue by Kayda1** [Norbyte/bg3se#211]
I wish I was kidding with this, but the error message is contradicting itself. It says I have the right script extender version installed but also don't have the right version
![image](https://github.com/Norbyte/bg3se/assets/154487677/d075ef8b-10d2-4566-baf3-4f9ea1708a4e)

**Comment by lunarbatexe** [comment]
Yeah samehere. Says I have v12 installed but I need to use v1. Im using what I assume is the most recent updted one (10/28/23).

**Comment by Kandelai** [comment]
Mine says the same, using the 10/28/23 version as well.

**Comment by 2Chloe1** [comment]
Yep, same. Does anyone figured out what's the problem?

**Comment by VexedPuff** [comment]
also having this problem.

**Comment by nikkijeske** [comment]
Yep this is the same issue I'm having.

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
