### ISSUE TITLE
Possibility for Requesting libraries in External folder

### ISSUE THREAD

**Issue by willake** [Norbyte/bg3se#212]
Hello,

I would like to fork bg3se for personal usage. (I want to enable `IO` and other modules to train AI models.)
It will require me to build bg3se. However, there are several external libraries are needed in order to successfully build the program.
Some of them did indicates the version while some of them does not. Also I am struggling to find the libraries.
Is it possible to get the include folder and .lib file from your side. Thank you very much.

**Comment by Norbyte** [comment]
Hi,

I keep a copy of the externals here: https://nb-stor.s3.eu-central-1.amazonaws.com/bg3/External.7z
You may need to rebuild some depending on your MSVC compiler version

**Comment by willake** [comment]
Thank you so much for helping! I wish you a nice holiday :)
