### ISSUE TITLE
BG3SE won't update to v11 unsure if it breaking my mods

### ISSUE THREAD

**Issue by HarleyDavid123** [Norbyte/bg3se#213]
I am unable to update BG3SE to v11, I have the correct files downloaded and installed, yet when I start the game it constantly says "v10", I am not sure if this is breaking 1 of the mods I really want to use "Appearance Edit Enhanced" as suddenly it won't appear in my hot bar or spellbook and I can't even get it to appear in a brand new save with no other mods activated

**Comment by Norbyte** [comment]
Check if you have a `ScriptExtenderUpdaterConfig.json` config file in `Baldurs Gate 3\bin`. If you ever used BG3MM or manually forced it to update to a specific version, that config will contain the v10 version number. Just delete it.
