### ISSUE TITLE
Warning in esv::SavegameManager::WarnIfModded mapping on steam version

### ISSUE THREAD

**Issue by netphils** [Norbyte/bg3se#214]
Noticed this new warning while gaming. Game version is 4.1.1.4251417, maybe because of [Hotfix15](https://store.steampowered.com/news/app/1086940/view/3878226811922849512)?

`No match found for mapping 'esv::SavegameManager::WarnIfModded'`

The maintainer said [it's normal on GOG versions](https://github.com/Norbyte/bg3se/issues/104#issuecomment-1777101556), but my steam version is getting this too.

# Full console output
```
******************************************************************************
*                                                                            *
*                     BG3 Script Extender Debug Console                      *
*                                                                            *
******************************************************************************

BG3Ext v12 built on Dec 14 2023 18:38:21
Game version v4.42.51.417 OK
ScriptExtender::Initialize: Starting
No match found for mapping 'esv::SavegameManager::WarnIfModded'
Library startup took 679 ms
We're already past App load, triggering CoreLibInit
LibraryManager::PostStartupFindLibraries() took 117 ms
Initializing client with target context Load
Modded achievements enabled.
bg3se::ExtensionStateBase::LuaResetInternal(): LUA VM reset.
Initializing client with target context Game
bg3se::ExtensionStateBase::LuaResetInternal(): LUA VM reset.
ecl::ScriptExtender::OnGameStateChanged(): Loaded module
```

**Comment by netphils** [comment]
I also noticed that my achievements aren't behaving properly. I tried to complete some simple achievement, but they aren't showing up on steam. Anything to do with this warning?

**Comment by ArcaneLunaX** [comment]
I tried moving from Vortex to LaughingLeader's Mod Loader as some of my mods weren't being added to Vortex's mod load file , and am now having this issue. It's irritating lol.

**Comment by manymanecki** [comment]
Hey, can we get some confirmation that achievements work, or do not, with that error? I, too, get the same error in the console output and that successfully strays me away from running Honor Mode right now. Thanks.

**Comment by ArcaneLunaX** [comment]
afaik it still is working, though I've heard that the Honor Mode dice doesnt award even if the achievement does when modded. But there's also a mod to just unlock the dice, so you could clear the mode first then install the mod to unlock the dice if it doesnt unlock correctly.

**Comment by Norbyte** [comment]
`esv::SavegameManager::WarnIfModded` is a patch to remove the "achievements are not enabled" message box ingame. Seems like recent BG3 versions have completely removed that dialog, hence why SE doesnt find it.

**Comment by netphils** [comment]
> Hey, can we get some confirmation that achievements work, or do not, with that error? I, too, get the same error in the console output and that successfully strays me away from running Honor Mode right now. Thanks.

I can confirm that old achievements are working fine, but not sure whether new ones does.
