### ISSUE TITLE
It's not a problem, but a doubt

### ISSUE THREAD

**Issue by iiiisy** [Norbyte/bg3se#216]
I haven't started a run in the new honor mode yet because I'm afraid I won't get the new achievement (foehammer). I see some people saying that the new achievement doesn't work for those who use mods (even with SE), so I would like to know if the Script Extender activates this achievement too, or does it really not work and I need to play full vanilla to get this achiev? I'm worried about starting in honor mode, wasting hours, reaching the end after a lot of effort and not getting the achievement.

**Comment by GuyInDogSuit** [comment]
I can't seem to get ANY achievements. So I guess not.

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
