### ISSUE TITLE
Massive load time increase when SE is active

### ISSUE THREAD

**Issue by WakeXT** [Norbyte/bg3se#217]
I was pondering why my saves were loading atrociously slow so I checked without mods first, didn't make a difference.
Since all my UI-mods weren't requiring SE anyway I uninstalled it and the load times went back to normal again.

Time needed to load the same savegame:
With Script Extender active - 8m18s
With Script Extender uninstalled - 24s
Even only enabling SE + Modfixer with no other mods causes long loads too.

The load behavior is rather strange as well when SE is active:
In the console it's at _"ScriptExtender::MergeWrapper() - Started merge_ where it slows down, with the CPU being at full load all those minutes.

Thought SE might be just good to have if other future mods require it and to enable achievements but atm I can't keep it installed because of this issue.

Edit - Well, that didn't work out as I hoped - if SE is uninstalled but mods stay enabled I can't interact with any NPCs, area transitions, can't go to camp etc.
If I disable the UI-mods in Vortex the interactions work again too.

Any idea how to run the game normally (quick load times+interactions/travel working I mean) while still having the UI-mods enabled would be appreciated.

Edit2 - Soo, decided to nuke everything in Vortex, redid the same arrangement of mods in BG3MM and it works fine with loads even go as low as 15s... .
Sucks a bit to lose the Vortex auto search for updates but it is what it is🤷.

**Comment by Norbyte** [comment]
`ScriptExtender::MergeWrapper() - Started merge` is a wrapper around the story merge function of the base game and doesn't really do anything so it's strange that it would take up so much time.

However, if it works without vortex then it might be some kind of strange interaction with vortex, as opposed to an SE thing. I haven't seen/heard this being an issue so far.

**Comment by WakeXT** [comment]
Doesn't seem to be Vortex exclusive.

Nuked BG3 install+mods in trying to get rid of the Durge+naked men issue but after redoing everything, as soon as I add any mod in BG3MM which has to be put in Active Mods I still get the character creation problem.

So far so bad but now I also get the long loading times as the game recompiles(?) the save every load instead of only doing it once and then when you save the next load would load quickly from that point on (as was the case before).

**Comment by Norbyte** [comment]
Mod logic in the game is wonky in general, so yea, toggling honor mode (which is in fact implemented as as "mod" ingame) can do this
