### ISSUE TITLE
Opened and Closed Listener are exchanged

### ISSUE THREAD

**Issue by SwissFred57** [Norbyte/bg3se#218]
it seems like 
function Osi.Opened(item) end
function Osi.Closed(item) end

are exchanged

if i use

Ext.Osiris.RegisterListener("Opened", 1, "after", function(item)

end)

i got the event on Closing a container

**Comment by SwissFred57** [comment]
it seems that when i open an container in Inventory the open and close is inverse if on the ground open close is correct

**Comment by Norbyte** [comment]
This is a vanilla game thing (the Opened/Closed listeners are direct references to the corresponding engine events), i.e. it is not within the scope of SE to change this.
