### ISSUE TITLE
I don't know where this problem come from

### ISSUE THREAD

**Issue by kanra2** [Norbyte/bg3se#219]
I don't know where this problem come from or what could be causing it....so yesterday my game was working perfectly but today my game isn't registering any of the mods despite having exported them to the game 
![Captura de Ecrã (39)](https://github.com/Norbyte/bg3se/assets/152713104/939c62fe-3a60-413d-8aba-1883ee7be563)
![Captura de Ecrã (40)](https://github.com/Norbyte/bg3se/assets/152713104/e9f7d914-73bd-482e-a60b-378e1d19ec87)

**Comment by SwissFred57** [comment]
put them on the left side then Save Order Export order to game and now **Reload All**

**Comment by kanra2** [comment]
> put them on the left side then Save Order Export order to game and now **Reload All**

that didn't work...

**Comment by yawor666** [comment]
did you move the game / player profiles folder? did you change anything in the MM config regarding the path to the game installation folder?
after exporting your mod order to game do you see the mods in the C:\Users\<Username>\AppData\Local\Larian Studios\Baldur's Gate 3\PlayerProfiles\Public\modsettings.lsx file when the game is not running / is running?
i had a similar problem, where one mod (Aether's Black Dye IIRC) was not loading correctly and the game reset the modsettings.lsx to vanilla.
check the game and SE logs for clues

**Comment by kanra2** [comment]
> did you move the game / player profiles folder? did you change anything in the MM config regarding the path to the game installation folder? after exporting your mod order to game do you see the mods in the C:\Users<Username>\AppData\Local\Larian Studios\Baldur's Gate 3\PlayerProfiles\Public\modsettings.lsx file when the game is not running / is running? i had a similar problem, where one mod (Aether's Black Dye IIRC) was not loading correctly and the game reset the modsettings.lsx to vanilla. check the game and SE logs for clues. or remove number 44 on your mod list from the active mods and check again ;)

I didn't change anything and the first thing I did was check modsettings.lsx and everything looked fine

**Comment by yawor666** [comment]
> > did you move the game / player profiles folder? did you change anything in the MM config regarding the path to the game installation folder? after exporting your mod order to game do you see the mods in the C:\Users\AppData\Local\Larian Studios\Baldur's Gate 3\PlayerProfiles\Public\modsettings.lsx file when the game is not running / is running? i had a similar problem, where one mod (Aether's Black Dye IIRC) was not loading correctly and the game reset the modsettings.lsx to vanilla. check the game and SE logs for clues. or remove number 44 on your mod list from the active mods and check again ;)
> 
> I didn't change anything and the first thing I did was check modsettings.lsx and everything looked fine

are the mods in the file when the game is running?

**Comment by kanra2** [comment]
> > > did you move the game / player profiles folder? did you change anything in the MM config regarding the path to the game installation folder? after exporting your mod order to game do you see the mods in the C:\Users\AppData\Local\Larian Studios\Baldur's Gate 3\PlayerProfiles\Public\modsettings.lsx file when the game is not running / is running? i had a similar problem, where one mod (Aether's Black Dye IIRC) was not loading correctly and the game reset the modsettings.lsx to vanilla. check the game and SE logs for clues. or remove number 44 on your mod list from the active mods and check again ;)
> > 
> > 
> > I didn't change anything and the first thing I did was check modsettings.lsx and everything looked fine
> 
> are the mods in the file when the game is running?

yes

**Comment by yawor666** [comment]
what version of the script extender are you using? is it possible, that it got updated to a new one from the development channel?
unfortunately i have no more ideas what is wrong. my problem was after a game update and i resolved it by removing the problematic mod.

**Comment by Norbyte** [comment]
Mods not being loaded like this is unrelated to SE.

Seems like what happens is that the game found an issue in modsettings.lsx. In this case, it discards the entire mod settings file and reverts to default mod settings, i.e. not loading any mod.

**Comment by kanra2** [comment]
> what version of the script extender are you using? is it possible, that it got updated to a new one from the development channel? unfortunately i have no more ideas what is wrong. my problem was after a game update and i resolved it by removing the problematic mod.

v12 (I think, I used the mod manager option to update the script extender)

**Comment by kanra2** [comment]
> Mods not being loaded like this is unrelated to SE.
> 
> Seems like what happens is that the game found an issue in modsettings.lsx. In this case, it discards the entire mod settings file and reverts to default mod settings, i.e. not loading any mod.

yeah I thought so! but I can't figure out what's happening someone told me to see if in player profiles there was a debug folder and delete it but there was no such folder. and the modsetting reverting to default is weird because when I export to game and open the game the file has the mods there.

**Comment by yawor666** [comment]
have you updated any mods? in your screenshot i can see some of them were updated on the 29.12. did the problem occur after those updates?

**Comment by kanra2** [comment]
> have you updated any mods? in your screenshot i can see some of them were updated on the 29.12. did the problem occur after those updates?

I did but I'm not sure because removing those didn't change anything (I tried to go back to just hair mods and yikes all I got was a frozen screen of male character models when I tried to create a new character
![Captura de Ecrã (42)](https://github.com/Norbyte/bg3se/assets/152713104/c0d0a22d-c977-433d-90b5-03866f1bf58f)
)

**Comment by yawor666** [comment]
> > have you updated any mods? in your screenshot i can see some of them were updated on the 29.12. did the problem occur after those updates?
> 
> I did but I'm not sure because removing those didn't change anything (I tried to go back to just hair mods and yikes all I got was a frozen screen of male character models when I tried to create a new character) 
instead of removing the mods did you try to revert to the versions you had before you updated them?

**Comment by kanra2** [comment]
> instead of removing the mods did you try to revert to the versions you had before you updated them?

yup..I only tried removing when that didn't work

**Comment by SwissFred57** [comment]
i had this also some days ago because a Mod referenced a Icon from another Mod
also a Mod could be using the same UUIDS
load Mod after Mod until you find the Mod

**Comment by kanra2** [comment]
> i had this also some days ago because a Mod referenced a Icon from another Mod also a Mod could be using the same UUIDS load Mod after Mod until you find the Mod

I'm currently re-downloading all my mods and doing that

**Comment by SwissFred57** [comment]
i am sad that you dont use one of my Mods Lol

**Comment by kanra2** [comment]
> i am sad that you dont use one of my Mods Lol

what mods have you made?

**Comment by lunarbatexe** [comment]
> put them on the left side then Save Order Export order to game and now **Reload All**

You have literally saved me with that. I was having issues of my own and what you said here works. So thank you!

**Comment by SwissFred57** [comment]
My Mods SwissFred
like tutorial Exit and many more

**Comment by kanra2** [comment]
> My Mods SwissFred like tutorial Exit and many more

I checked and I do have one of yours

**Comment by kanra2** [comment]
I finally re-downloaded and installed everything and after rechecking the modsetting I think I know what the problem was. I didn't notice initially but after I re-installed everything I notice that one mod had a missing section
