### ISSUE TITLE
Game won't launch via mod manager with SE installed

### ISSUE THREAD

**Issue by NoxStellans** [Norbyte/bg3se#221]
I don't know if this is a mod manager issue or an SE issue, but with the SE installed, the game simply won't launch via the mod manager. It only runs as a background process. I'm certain I've installed it in the right place. Do you know what could be causing this? I'll appreciate any help you can offer!

**Comment by BL00R** [comment]
hi there, I'm also having the same problem, did you ever manage to resolve it?

**Comment by NoxStellans** [comment]
Hi, I ended up resolving it by launching directly from Steam. My mods still worked!
