### ISSUE TITLE
game cant launch with launch options 

### ISSUE THREAD

**Issue by ZePugg** [Norbyte/bg3se#223]
having WINEDLLOVERRIDES="DWrite.dll=n,b" PROTON_NO_ESYNC=1 %command% in launch options causes this to appear

anyone have a way to solve this issue

![image_2024-01-03_172139136](https://github.com/Norbyte/bg3se/assets/93382097/5fd6a88a-1e0d-477d-8f0c-9b52eff213e0)

**Comment by Lucifon** [comment]
Having this exact same issue.

**Comment by Lucifon** [comment]
I was able to get it to work by removing the %command% at the end of the Launch Argument.

**Comment by Awiseman69** [comment]
If you are playing on Windows the launch options aren't needed. The options are for Linux only.
