### ISSUE TITLE
I am stuck in a forever sleep

### ISSUE THREAD

**Issue by mulisfish** [Norbyte/bg3se#224]
I have read through multiple threads addressing this bug and as suggested by Tawaporah in https://www.nexusmods.com/baldursgate3/mods/1646?tab=description&BH=3 , I managed to remove an extra party member (damned already dead quasit). Every solution says to reload a previous save and do some stuff _**before**_ you go to sleep, but this happened to my honour mode playthrough and I am still stuck asleep. Is there any way I can save this run?

Also all my party members disappeared the moment I long rested.
![Screenshot 2024-01-08 080812](https://github.com/Norbyte/bg3se/assets/61972556/a4ce4847-c895-409a-9a0d-a2bc9090e2ae)

**Comment by digitaltesla** [comment]
This generally happens when you're above normal party limits, but the fix for it is actually toggling (hide) for your party- with will show up under your list of group members (small button)

**Comment by mulisfish** [comment]
I might be missing something but since all my party members disappeared for some reason I don't have the group list and there's no button to press. Using shift+c or c doesn't work either

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
