### ISSUE TITLE
Failed to apply update

### ISSUE THREAD

**Issue by Maisa85** [Norbyte/bg3se#226]
Hi!

I just got an error message:

"Failed to apply Script Extender update:
Script Extender update failed:
Failed to write manifest file
C:\Users\me\AppData\Local\BG3ScriptExtender\Manifest-Release.json"

I finished playing about an hour ago and this popped now when I launched the game again.
Game itself seems to run fine but I'm too afraid to continue.

Edit: Game is updated, auto updates are on, I just installed latest DWrite.dll again and I still get the error.
Games Main menu window says Script Extender is v.13
Edit2: Manifest-Release.json says version 12.0.0.0 ?

Is that possibly the problem?

Br.Maisa

**Comment by belowzeros** [comment]
not sure why this happens but i've run into it myself in the past and it's been mentioned here before.  i had to change to manually updating my SE.  i don't think anyone has figured out what causes it

**Comment by Maisa85** [comment]
It doesn't seem to affect the game it self, thank goodness. I took backup saves and continued the game anyway. I'm itching to try to change the version number in .json to 13.0.0.0 if the error would go away but that probably just breaks next update. 😅

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
