### ISSUE TITLE
Yo, achievements doesn't work for me for some reason

### ISSUE THREAD

**Issue by Aidayen** [Norbyte/bg3se#227]
I'm using Script Extender enable achievements option in BG3 Mod Manager and after it didn't work I did install Achievement Enabler from Nexus. Still don't get an achievement after killing Zhalk. This is my mod list https://imgur.com/a/2sD3cBz
Can someone help? I don't know where to post so posted there as it's kinda connected to Script Extender theme.

**Comment by Aidayen** [comment]
I turned off the mods and killed Zhalk on the ship and I got the achievement. So I can't really check now what mod is causing the problem. Is there any log which shows what mod causes error?

**Comment by GuyInDogSuit** [comment]
Achievements aren't working for me, either, and I tried the same things you did to remedy it, with no fix. I was testing "Bottoms Up" and "Outsourcing," with no luck.

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
