### ISSUE TITLE
Console does not appear

### ISSUE THREAD

**Issue by OngakuSensei** [Norbyte/bg3se#23]
I downloaded the script extender with console, and I followed the installation instructions to the letter. However, the console window does not appear when I launch the game.

Steam version 4.1.1.3686210

**Comment by Gape-Ape** [comment]
having the same issue, no console window on start-up

**Comment by d3xMachina** [comment]
You need to create a config file "ScriptExtenderSettings.json" in the "bin" folder of the game with the content : 
```
{
"CreateConsole": true,
"EnableAchievements": true
}
```

EnableAchievements is not necessary but you probably want that also.

**Comment by Gape-Ape** [comment]
> You need to create a config file "ScriptExtenderSettings.json" in the "bin" folder of the game with the content :
> 
> ```
> {
> "CreateConsole": true,
> "EnableAchievements": true
> }
> ```
> 
> EnableAchievements is not necessary but you probably want that also.

ah, the files got extracted to a folder in bin directory, once I took em out it worked. Thanks!

**Comment by PerplexedPeach** [comment]
Also have an issue with the console not being accessible. I have ScriptExtenderSettings.json in the bin folder with the following boot logs:
```
BG3Ext v2 built on Sep  4 2023 22:39:05
Game version v4.37.0.362 OK
ScriptExtender::Initialize: Starting
Library startup took 1059 ms
Fossilize ERROR: Failed to parse ApplicationInfoFilter, letting recording go through.
```
This is with [BG3SE-Updater-with-Console-v3.zip](https://github.com/Norbyte/bg3se/releases/download/updater-v3/BG3SE-Updater-with-Console-v3.zip)

**Comment by PerplexedPeach** [comment]
OK nevermind, my expectations of the console was wrong. I thought it would be in game, but the console is in the cmd window that opens up in addition to the game:
![image](https://github.com/Norbyte/bg3se/assets/48222967/c9d32865-b488-442e-bee5-293f1fa31f72)

**Comment by dupajezaipapieza** [comment]
In my case the console shows up for a second and then closes itself.  I have no idea how to fix it up

**Comment by ZenobiaCatnap** [comment]
Hi... have you managed to fix this?


> In my case the console shows up for a second and then closes itself. I have no idea how to fix it up

**Comment by dupajezaipapieza** [comment]
sadly no :((

**Comment by ZenobiaCatnap** [comment]
Aww man :(

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
