### ISSUE TITLE
Possible hotfix 16 issue

### ISSUE THREAD

**Issue by tricckk** [Norbyte/bg3se#233]
Quite a few people seem to be having a problem after hotfix 16 where the game won't recognize quest items. Items such as Nere's head or Shar's spear of darkness will not trigger their respective dialogue options/quest progression. The general thought seems to be that since hotfix 16 changed how quest items interact with player inventory, the script extension isn't compatible anymore. I am not a modder, and I'm new to github so apologies if I'm not posting this correctly. This is just what I've been able to find after a few days of researching on forums and testing each of the mods I have downloaded. I am just wondering if it is possible that the script extender is, in fact, causing this issue and if there are any plans for an update to fix the problem. Thank you so much for your work and time, I'm sure making scripts like this isn't easy so if the answer is no I completely understand.

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
