### ISSUE TITLE
Do we still need ModFixer, or does v12 or 13 of SE handle that for us?

### ISSUE THREAD

**Issue by drysdan** [Norbyte/bg3se#237]
Been asked before, and I've seen mention that it was planned for SE to implement a full replacement of ModFixer's functionality, but I can't seem to find a version-by-version changelog or update notice saying that it has done so, and there's lots of confusion in the ModFixer page discussing if it's still needed or not.

**Comment by Norbyte** [comment]
None of the SE versions include mod fixer (the upcoming v14 doesn't include it either).

However, SE does include a patch to ensure that the use of mod fixer doesn't prevent game updates from applying to story scripts in savegames.

**Comment by drysdan** [comment]
Ok, thanks for the clarification. So the comment back in December on[ issue #186](https://github.com/Norbyte/bg3se/issues/186#issuecomment-1837462051) that a full modfixer replacement would be included in v12 never ended up working out? Or is it still planned for a future version and just got delayed?

**Comment by Adsam112** [comment]
How do I enable this patch or where do i find it if i may ask?

**Comment by Norbyte** [comment]
No mod fixer replacement is included as of v16, and since mod fixer is so prevalent nowadays there it probably won't be included in later versions either.
