### ISSUE TITLE
Current script line isn't working in-game when entered in console: Osi.SetFlag("9ccec403-dc18-661d-ed53-e5472b8145b4", GetHostCharacter())

### ISSUE THREAD

**Issue by maradesu** [Norbyte/bg3se#238]
I'm unable to trigger a dialogue option after Gale reunites with Tara in Act 3, specifically where Tav has the option to ask Gale about his last name. I've seen in some posts that this is the line of script that should be entered prior to speaking with Tara, however, no additional dialogue option is present once entering it: 

**Osi.SetFlag("9ccec403-dc18-661d-ed53-e5472b8145b4", GetHostCharacter())**

To be more specific, this dialogue triggers after Gale finishes speaking with Tara, who also reveals that Gale's last name is Dekarios.

Gale: "Given the length of my time away, I feared she might have given up on me. I should have known better - she'd never do such a thing."
Tav: [Dialogue Option 1] "So, your last name is Dekarios?"

Reference to the specific dialogue can be found here: https://www.youtube.com/watch?v=GdURJqJfbMA&ab_channel=GameryDen

**Comment by Varriount** [comment]
Are you sure this script line is still valid? Game patches since that video was made may have changed that dialogue ID.

**Comment by maradesu** [comment]
> Are you sure this script line is still valid? Game patches since that video was made may have changed that dialogue ID.

That does sound like it could be the case, but I’m not 100% certain. If it is due to that, how do I go about finding out what the updated script line is?

**Comment by SwissFred57** [comment]
still valid

<?xml version="1.0" encoding="utf-8"?>
<save>
	<version major="4" minor="0" revision="9" build="306" lslib_meta="v1,bswap_guids" />
	<region id="Flags">
		<node id="Flags">
			<attribute id="UUID" type="guid" value="9ccec403-dc18-661d-ed53-e5472b8145b4" />
			<attribute id="Name" type="FixedString" value="ORI_Gale_Knows_TaraMentionedDekarios" />
			<attribute id="Description" type="LSString" value="Tara has mentioned Gale's last name -Dekarios" />
			<attribute id="Usage" type="uint8" value="5" />
		</node>
	</region>
</save>

**Comment by maradesu** [comment]
> Your best bet would be to use https://github.com/ShinyHobo/BG3-Modders-Multitool to look for the UUID associated with the localized string associated with the dialogue option, then use that UUID to look for the dialogue option's UUID (I believe they are two separate things)
> 
> An alternate way would be to use https://github.com/Norbyte/lslib to dump and compare two save files - one that has the dialogue option available, and one that doesn't. You would be looking at the contents of the GOALS file.
> 
> Sorry for the vagueness, but I myself don't entirely understand the dialogue system.

I really appreciate this, thank you- I’ll try this out! I don’t understand this either, so no worries.

**Comment by SwissFred57** [comment]
i just tell that the uuid is still valid on the latest patch

**Comment by SwissFred57** [comment]
try this 
Osi.SetFlag("ORI_Gale_Knows_TaraMentionedDekarios_9ccec403-dc18-661d-ed53-e5472b8145b4", GetHostCharacter(), 1, 1)

**Comment by maradesu** [comment]
> try this Osi.SetFlag("ORI_Gale_Knows_TaraMentionedDekarios_9ccec403-dc18-661d-ed53-e5472b8145b4", GetHostCharacter(), 1, 1)

Oh my goodness- thank you SO MUCH! <3 

This worked!!!
