### ISSUE TITLE
Crashing After reinstalling game

### ISSUE THREAD

**Issue by katdiddy** [Norbyte/bg3se#239]
So, I ended up reinstalling BG3 after becoming victim of that glitch were the game doesn't recognize story items in your inventory. The next day of course, a patch comes out. Anyway, since then when I try to load my game or start a new one- this happens. 
![image](https://github.com/Norbyte/bg3se/assets/157332745/2a8b2899-0bfd-4437-8ddd-d14e32668e89)

I've tried reinstalling the Script Extender, going over all my mods that required manual install, but nothing seems to work. Can anyone explain to me whats going on?

**Comment by katdiddy** [comment]
update, if i delete the script extender- i can start a new game. but still, i have mods i wanna use that require it :(

**Comment by Varriount** [comment]
What happens if you uninstall and reinstall the game?

**Comment by katdiddy** [comment]
this is what happened when i uninstalled and reinstalled the game. 
script extender used to work just fine before i did the uninstall/reinstall.

**Comment by Varriount** [comment]
Have you re-downloaded script extender?

**Comment by katdiddy** [comment]
yes i have, and no changes

**Comment by katdiddy** [comment]
which part is the command i need to enter? is it the whole top line? i've never used this program and my programming knowledge minimal at best.
if you need a benchmark for how little i know about this, here is the most i've been able to get out of powershell
![Screenshot 2024-01-23 184312](https://github.com/Norbyte/bg3se/assets/157332745/1c36c182-6439-4dc5-a039-d5730e59d7e2)

**Comment by Varriount** [comment]
The entire thing:
![image](https://github.com/Norbyte/bg3se/assets/524596/18fda579-eb43-41f8-bdbc-d0809d8ef079)

**Comment by katdiddy** [comment]
gosh, i was pretty stupid- i thought you were showing me an example of what doing the command would look like. anyway... prepare for a lot of attachments...
![Screenshot 2024-01-23 203621](https://github.com/Norbyte/bg3se/assets/157332745/2ddbeabe-d30d-452c-b5ab-5836aa174850)
![Screenshot 2024-01-23 203715](https://github.com/Norbyte/bg3se/assets/157332745/57d1d97f-6333-4aa3-a105-82ce8c747a8a)
![Screenshot 2024-01-23 203745](https://github.com/Norbyte/bg3se/assets/157332745/1b1079c8-1af4-4185-b4dc-b975bc2c109b)
![Screenshot 2024-01-23 203802](https://github.com/Norbyte/bg3se/assets/157332745/a28dfbff-fb98-4bea-b53e-64e20422bbbe)
![Screenshot 2024-01-23 203816](https://github.com/Norbyte/bg3se/assets/157332745/921e8e8d-d947-4ac4-bced-808e5197b9be)
![Screenshot 2024-01-23 203835](https://github.com/Norbyte/bg3se/assets/157332745/8d91e076-59f2-496d-90e0-12f8c9882bf2)
![Screenshot 2024-01-23 204022](https://github.com/Norbyte/bg3se/assets/157332745/e29c70a6-5090-4565-9ca9-11d26df9e2cb)
![Screenshot 2024-01-23 204036](https://github.com/Norbyte/bg3se/assets/157332745/445b23fe-944f-4e51-88ec-bed4def0fe52)
![Screenshot 2024-01-23 204045](https://github.com/Norbyte/bg3se/assets/157332745/5021ff74-8393-45ed-a0ef-e2da11fe6758)
![Screenshot 2024-01-23 204350](https://github.com/Norbyte/bg3se/assets/157332745/a415ee30-5663-4921-afbc-d79a858c590f)
![Screenshot 2024-01-23 204402](https://github.com/Norbyte/bg3se/assets/157332745/dc7b14dc-6781-4751-b599-025fcb3132ec)
![Screenshot 2024-01-23 204411](https://github.com/Norbyte/bg3se/assets/157332745/39fb59a3-be4f-4289-9689-a835630d8fd7)
![Screenshot 2024-01-23 204424](https://github.com/Norbyte/bg3se/assets/157332745/cd470210-738a-4b35-ac61-a27ea87a7842)
![Screenshot 2024-01-23 204435](https://github.com/Norbyte/bg3se/assets/157332745/c5ce36df-71ae-4c67-adf8-9b01b8d018a1)
![Screenshot 2024-01-23 204448](https://github.com/Norbyte/bg3se/assets/157332745/5fbefd85-0628-4ee2-b9da-cde4420e2d0f)
![Screenshot 2024-01-23 204500](https://github.com/Norbyte/bg3se/assets/157332745/ccb55060-6508-4499-8977-1210ab4105f7)
![Screenshot 2024-01-23 204509](https://github.com/Norbyte/bg3se/assets/157332745/bdbb7101-d289-483b-90a2-99ff7265dad3)

thanks for the help

**Comment by Varriount** [comment]
You should find a file called "BG3 File Hashes" in your temp folder (that last "Invoke-Item" command will open it, you might need to press "enter" in the terminal).

I am a bit puzzled as to why your save game files are being included, and at those errors in red text. Might be a problem with the code. I'd have given you a whole to run, but Windows disables running PowerShell files by default.

**Comment by katdiddy** [comment]
[BG3 File Hashes.txt](https://github.com/Norbyte/bg3se/files/14032975/BG3.File.Hashes.txt)

Here you go!

**Comment by Varriount** [comment]
So, some things that stand out to me:
  - You have the `NativeMods` extension installed, as well as a large number of other mods.  
    Try:
      - Temporarily deleting the NativeMods extension.
      - Temporarily removing all your installed mods.
      - Re-enable Script Extender
    
    And see whether that fixes things.
  - There is a `ScriptExtenderUpdaterConfig.json` file in the `bin` directory of your BG3 game folder. Could you attach/post the contents of that file? I don't have such a file in my installation, and it may be interfering with the auto-update functionality of Script Extender.
  - Many of the core executables and shared libraries (DLLs) in your installation differ from the ones I have. Since you stated you re-installed the game, it's doubtful this is due to the files being out-of-date. The more likely cause is that it is because I bought BG3 through GOG, while you bought BG3 through Steam. That being said, those differences *could* be a cause.

**Comment by katdiddy** [comment]
[ScriptExtenderSettings.json](https://github.com/Norbyte/bg3se/files/14046199/ScriptExtenderSettings.json)
[ScriptExtenderUpdaterConfig.json](https://github.com/Norbyte/bg3se/files/14046200/ScriptExtenderUpdaterConfig.json)

I don't know what these guys are either. I'll  follow the instructions for your first step and let you know how it goes.

**Comment by Varriount** [comment]
You might try renaming/deleting `ScriptExtenderUpdaterConfig.json`, as it looks like it may be preventing your installation from updating itself.

**Comment by katdiddy** [comment]
I tried deleting the recommended thing, and instead of crashing, the camp loaded to 75 percent- paused for a bit, and then sent me back to the main menu.

**Comment by Varriount** [comment]
So rather than crashing, the game at least starts?

**Comment by katdiddy** [comment]
the game itself can start. the game used to crash upon trying to load my save file. now it just does the 75 thing and sends me back to the main menu. i this is also what happened when i tried to delete script extender all together back when i was trying to troubleshoot this problem by myself.

**Comment by Varriount** [comment]
Hm. Can you upload your save file somewhere?

**Comment by katdiddy** [comment]
new created saves now work, script extender and all! sadly, my old save still doesn't. i was thinking of restarting anyway, i think i can make peace with losing this save. thanks for all your help!

**Comment by Crisal661** [comment]
The mods don't work for me, should I download a new version?

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
