### ISSUE TITLE
Script Extender Error Message - No internet?

### ISSUE THREAD

**Issue by Snarkyfork** [Norbyte/bg3se#24]
![Error](https://github.com/Norbyte/bg3se/assets/41749133/ea799566-8920-4286-a402-f25d5a67b1ab)

Every time I launch the game I get this error saying I am not connected to the internet but I have cleared the "NGX Updater" to connect in my firewall. Is there some hidden process I need to whitelist or is there a "non-updating" version of this mod I can use? The message is rather annoying.

**Comment by Cerberus-tm** [comment]
Hmm is there no way to use this without connecting to the Internet? I'd rather not.

**Comment by d3xMachina** [comment]
From reading the source code it looks like it downloads the BG3SE version compatible with your game version in "%APPDATA%\..\Local\BG3ScriptExtender" at the start.

It downloads ".package" files from [here](https://d3u76crhadhyzl.cloudfront.net/Channels/Release/Manifest.json). (those can be opened with 7zip)

You can disable the update process by setting "DisableUpdates" to true in your config.

You need to at least run it once with the update enabled or it won't work. After updating your game you will probably need to allow the update again.

**Comment by Cerberus-tm** [comment]
@d3xMachina Hey, thanks for looking into it! I'll see whether I can find this config.

I have just updated the game to Patch 2, and now Script Extender seems to give an error and not work at all any more, hmm.

**Comment by Pintaius** [comment]
For if it might be of help I had a similar issue of the game not loading properly after updating to Patch 2 (crash at first loading screen around 93%), and after tinkering a lot with mods and configurations I traced it back to the script extender. The post by @d3xMachina above gave me an idea and I deleted my "%APPDATA%..\Local\BG3ScriptExtender" folder. The game then started normally and (with Internet on) downloaded the contents of that folder again. It now all works even with the Internet off.

**Comment by Cerberus-tm** [comment]
@Pintaius Thank you very much, deleting that folder solved the problem for me!

@d3xMachina I cannot find this config anywhere, do you have any idea where it could be?

**Comment by Norbyte** [comment]
Short version of the manual install method is:
 - Copy `BG3ScriptExtender.dll` and `libprotobuf-lite.dll` to `Baldurs Gate 3\bin`
 - Rename `BG3ScriptExtender.dll` to `DWrite.dll`
 - Profit?

**Comment by greene7979** [comment]
@Norbyte what package should I be downloading for this manual install method as listed above to prevent automatic downloads? The package I'm downloading from this project is only giving me the DWrite.dll and ScriptExtenderSettings.json. I'm having trouble with the instructions above unfortunately.

Can you also confirm what @d3xMachina wrote above that you can disable the update process by setting "DisableUpdates" to true in your config?

Thank you, and I apologize for my poor understanding of your work. You're doing great work for the community!

**Comment by Cerberus-tm** [comment]
Thank you @Norbyte for making this! And for your instructions for the manual installation, it works for me.

Thank you @d3xMachina for the instructions for the settings file, it seems to work!

**Comment by AbsoIuteZER0** [comment]
@Pintaius my BG3ScriptExtender Folder located in "%APPDATA%..\Local\" was empty, is that normal? If not, what kind of content/files are suppose to be in there?

**Comment by XetoKiyaba** [comment]
> @Pintaius my BG3ScriptExtender Folder located in "%APPDATA%..\Local" was empty, is that normal? If not, what kind of content/files are suppose to be in there?

ive got this same issue it refuses to download any files there and wont show a console on launch nothing! post the files it downloads please so we can manually input them

**Comment by TaliZoraVasTyria** [comment]
> Short version of the manual install method is:
> 
> * Copy `BG3ScriptExtender.dll` and `libprotobuf-lite.dll` to `Baldurs Gate 3\bin`
> * Rename `BG3ScriptExtender.dll` to `DWrite.dll` (overwrite the previous DLL you downloaded)
> * Profit?
> 
> Note that this means you need to manually get the package each time a new extender version is required by a mod.

yes please can we have a manual download version as well? my game files script extender also refuse to connect online

**Comment by Cerberus-tm** [comment]
> > Short version of the manual install method is:
> > 
> > * Copy `BG3ScriptExtender.dll` and `libprotobuf-lite.dll` to `Baldurs Gate 3\bin`
> > * Rename `BG3ScriptExtender.dll` to `DWrite.dll` (overwrite the previous DLL you downloaded)
> > * Profit?
> > 
> > Note that this means you need to manually get the package each time a new extender version is required by a mod.
> 
> yes please can we have a manual download version as well? my game files script extender also refuse to connect online

@d3xMachina Gave a link above, where you can get the 'offline' packages, which worked for me:

https://d3u76crhadhyzl.cloudfront.net/Channels/Release/Manifest.json

You should probably check what version your game is, to get the right version of the package.

**Comment by XetoKiyaba** [comment]
@Cerberus-tm 
> https://d3u76crhadhyzl.cloudfront.net/Channels/Release/Manifest.json
> 
> You should probably check what version your game is, to get the right version of the package.

that just shows a bunch of text from a json file with nowhere to download anything for me

**Comment by Norbyte** [comment]
Note: The manifest URL has changed, https://bg3se-updates.norbyte.dev/Channels/Release/Manifest.json is the new one.

**Comment by AbsoIuteZER0** [comment]
For those confused on how to get "BG3ScriptExtender.dll" and "libprotobuf-lite.dll" for the manual install, the link Norbyte posted above me takes you to a wall of text. Look carefully and you'll see several links next to the "URL" sections. Choose and highlight one of the links, right click, open the link, and it'll download the package for you. After that just follow Norbyte's instructions above on how to manual install it.

**Comment by Norbyte** [comment]
In case you still get errors from the updater, can you try with this version and post the console output?
If it still fails, set `"IPv4Only": true` in `ScriptExtenderUpdaterConfig.json` and see if it has any effect.
[BG3SE-Updater-v4-Debug.zip](https://github.com/Norbyte/bg3se/files/12651389/BG3SE-Updater-v4-Debug.zip)

Alternatively an updaterless version is available here (essentially the same as manually getting the .package and renaming the dll):
https://bg3se-updates.norbyte.dev/Channels/Release/ManualInstall.zip
(Note: You have to update this one manually each time a new build comes out.)

**Comment by TaliZoraVasTyria** [comment]
> In case you still get errors from the updater, can you try with this version and post the console output? If it still fails, set `"IPv4Only": true` in `ScriptExtenderUpdaterConfig.json` and see if it has any effect. [BG3SE-Updater-v4-Debug.zip](https://github.com/Norbyte/bg3se/files/12651389/BG3SE-Updater-v4-Debug.zip)
> 
> Alternatively an updaterless version is available here (essentially the same as manually getting the .package and renaming the dll): https://bg3se-updates.norbyte.dev/Channels/Release/ManualInstall.zip (Note: You have to update this one manually each time a new build comes out.)

ok so i just download the manuainstall, extract it and put it to the bin folder? the file name is already dwrite.dll so I guess I don't have to rename it?

**Comment by AbsoIuteZER0** [comment]
Question, I noticed that a lot of my C Drive memory is being consumed by newly created files in the "Extender Logs" located in **C:\Users\Zero\AppData\Local\Larian Studios\Baldur's Gate 3\Extender Logs**. Is this because of the Script Extender or something else (and how do I disable it)?

**Comment by Cerberus-tm** [comment]
> Question, I noticed that a lot of my C Drive memory is being consumed by newly created files in the "Extender Logs" located in **C:\Users\Zero\AppData\Local\Larian Studios\Baldur's Gate 3\Extender Logs**. Is this because of the Script Extender or something else (and how do I disable it)?

I don't even have this folder.

**Comment by TaliZoraVasTyria** [comment]
ok a bit unrelated to the no internet issue, but patch 4 just dropped, do I need to manually download the script extender again or leave it be if there's no update to the script extender itself?

**Comment by komori** [comment]
> ok a bit unrelated to the no internet issue, but patch 4 just dropped, do I need to manually download the script extender again or leave it be if there's no update to the script extender itself?
> 
> PS: ah shoot...even after updating manually I still got this error from bg3 mod manager ![image](https://user-images.githubusercontent.com/145265764/270002580-2cc560be-f933-4adf-a9af-9a4311454549.png)

Getting the exact same issue as you. Been trying various versions of the script extender with no luck.

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
