### ISSUE TITLE
No console window popping up

### ISSUE THREAD

**Issue by Yartonator** [Norbyte/bg3se#241]
When I launch the game after extracting to my bin folder, it shows "Script Extender loaded, built on..." and all that but there is no additional window that pops up or anything when I launch the game, am I missing something?

**Comment by SwissFred57** [comment]
ScriptExtenderSettings.json in the bin folder of BG3
content of json file

  {
  "CreateConsole": true,
  "EnableAchievements": true
}

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
