### ISSUE TITLE
modsettings.lsx overwrites itself clean on debug console??

### ISSUE THREAD

**Issue by nonbinaryLoophole** [Norbyte/bg3se#247]
so I followed all the instructions to ensure that the mods worked alongside the game.

but as of late whenever I export my load order to the game to overwrite the modsettings file, it will overwrite itself to a clean slate as the Current Load Order with none of my mods loaded into the game itself. the game works fine vanilla on its own, but it makes most of my saves unplayable and impossible for me to finish my current playthroughs [ one of which is already in act 3 that I have patiently been playing towards for the past couple of months ]. 

do review if this is a script extender issue or a mod manager issue, so i can direct this problem to the rightful place. :(

**Comment by Varriount** [comment]
This sounds more like a mod manager issue. As far as I know, Script Extender doesn't touch `modsettings.lsx`.

**Comment by Norbyte** [comment]
This is vanilla game behavior and the extender has no control over that. If modsettings.lsx has references to mod names/paths/UUIDs that the game considers to be invalid or missing, it'll nuke the entire modsettings.lsx file.
