### ISSUE TITLE
every one is fleeing me 

### ISSUE THREAD

**Issue by Igloo526** [Norbyte/bg3se#250]
Hi in the act 1 every npc is fleeing and i don't know why in the console there only this error:
bg3se::esv::lua::OsirisCallbackManager::RunHandler(): Osiris event handler failed: [string "AGtT_Birthsigns/Actions/OnStatusApplied.lua"]:7: attempt to index a nil value (global 'CLUtils')
stack traceback:
        AGtT_Birthsigns/Actions/OnStatusApplied.lua:7: in field 'OnStatusApplied'
        AGtT_Birthsigns/BootstrapServer.lua:51: in function <AGtT_Birthsigns/BootstrapServer.lua:50>
thanks for the response

**Comment by Igloo526** [comment]
Yeah I suspect even a game bug BC it happend after a goblin attacked the ziefling with the telescope

**Comment by SwissFred57** [comment]
https://www.nexusmods.com/baldursgate3/mods/6242
is the problem

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
