### ISSUE TITLE
Camp chests on honor multiplayer 

### ISSUE THREAD

**Issue by 1eonadawn** [Norbyte/bg3se#251]
Hi! I use the script extender to get achievements back after modding cosmetics, and ever since adding it I seem to be only getting one camp chest in honour mode multiplayer, belonging to the guest. Any suggestions? Ty

**Comment by Varriount** [comment]
This is likely not a bug with Script Extender, birthday whatever mods you've used. Script Extender merely provides a way for mods to interface with the game.

**Comment by 1eonadawn** [comment]
Gotcha! I wasn't sure. It was just the only ~mod I've added recently and I haven't had this problem before, so I figured I'd try here before looking elsewhere. Thanks! I'll have to peek into what else might be doing this

**Comment by nonchip** [comment]
@1eonadawn and you left this open because...?

**Comment by 1eonadawn** [comment]
Closed, sorry
