### ISSUE TITLE
downloaded and placed it in game, now it wont open

### ISSUE THREAD

**Issue by sijeuegnhs8udhg8uhr** [Norbyte/bg3se#252]
The game keeps crashing since I've placed the file in and it wont open, I even took it out and it still doesn't work, what do I do

**Comment by killwort** [comment]
Same problem. I can add that after launch bg3.exe process hangs in memory with really small footprint (like 20kb)

**Comment by Varriount** [comment]
What operating systems are you running, and which executable are you running?

**Comment by killwort** [comment]
Either dx11 and vulkan exe don't work.
OS win11 (10.0.22621).

That's how it displayed in task manager:
![изображение](https://github.com/Norbyte/bg3se/assets/4142887/60e7a38a-0c54-4740-9934-6c7e7f250c29)

I've tried running wireshark to see if there's any network activity - there's none.
Also no files seems to be downloaded (obviously it cannot be done without going to network)

**Comment by Varriount** [comment]
Can you rename and run the bat file linked to in [this] (https://github.com/Norbyte/bg3se/issues/244#issuecomment-1913440737) comment, then upload the generated file? That will give a better idea of why your game might not be starting.

**Comment by killwort** [comment]
I've tried to download package manually, unpacked it into game folder, but without DWrite.dll it just won't load, and with DWrite.dll the game does not start.

**Comment by killwort** [comment]
Tried to build loader/updater from source and run under debugger, no luck as there's no info on external libraries used. 
I've downloaded curl, glm, jsoncpp, tinycrypt from github repos and they had at least compatible headers.
As for ziplib - [the version I found](https://github.com/frk1/ziplib) seems to be incompatible as it uses 1-byte characters (std::string) and calling code uses MBCS (std::wstring).

If you give me advice on getting all the dependencies and possible following compilation pitfalls, I'll be glad to run the game under debugger and see where it fails (probably waits for something indefinetely)

**Comment by Varriount** [comment]
I would try temporarily removing `bin\NativeMods\BG3AchievementEnabler.dll`, `bin\ScriptExtenderSettings.json`, and `Data\Mods\GustavDev\ScriptExtender\Config.json`, and see if that clears anything up.

**Comment by killwort** [comment]
OK, it works w/o mentinoned files. I added them back one by one and the winner is BG3AchievementEnabler!

**Comment by killwort** [comment]
More intresting is that by the docs https://www.nexusmods.com/baldursgate3/mods/668 it works with native mod loader which uses bink2w64.dll proxying.

**Comment by killwort** [comment]
Anyway I threw away BG3AchievementEnabled as script extender has a setting for that
"EnableAchievements": true

**Comment by Varriount** [comment]
@killwort It may be that you need to update `BG3AchievementEnabler.dll`, or that it only worked with a specific version of Script Extender.

**Comment by killwort** [comment]
Dunno, I just threw it away. It seems it is not compatible with SE anyway and SE has the same functionality.

**Comment by Lrigh1** [comment]
Yup! Can confirm, after hours of headaches, I thought it was this mod, but it was actually this mod conflicting with achieve enabler.
