### ISSUE TITLE
Script Extender wont update to V2

### ISSUE THREAD

**Issue by RogerRabbit10** [Norbyte/bg3se#255]
Stuck on V13, can't seem to figure out how to get it to go to V2 so my camp events continue to work

**Comment by Norbyte** [comment]
I'm not sure I understand, V13 is newer than V2
13 > 2

**Comment by RogerRabbit10** [comment]
I misunderstood and thought it was .13 not 13

**Comment by RogerRabbit10** [comment]
disregard
