### ISSUE TITLE
Loaded successfully prompt

### ISSUE THREAD

**Issue by SaiBork** [Norbyte/bg3se#256]
Slightly different to 232

The "Script Extender was loaded successfully, have a nice day" prompt comes up with a new game.

You only have about 2 seconds to click this. If you don't click it, it will be stuck on screen throughout the intro.
- If you press ESC it cancels the intro and you can then get rid of the prompt.

The prompt is in front of the intro, darkening the intro and well, the prompt is in front of the intro, but not on a layer high enough to be able to click the Accept button.

Can you see if there is a way for the prompt to either auto-accept so it doesnt stay when the intro starts, or put it on a higher layer so if you are too late pressing the button, you can still get rid of it when the intro starts?

![image](https://github.com/Norbyte/bg3se/assets/1523083/ded43b9f-6d6a-4c9b-8b02-39acd23f8875)

**Comment by Norbyte** [comment]
Hi,

SE just replaces the text of the dialog, normally you would see the "We were unable to create a working story. Your main adventure might be invalid etc etc." message here, so it is not an SE-specific issue sadly.

**Comment by SaiBork** [comment]
> Hi,
> 
> SE just replaces the text of the dialog, normally you would see the "We were unable to create a working story. Your main adventure might be invalid etc etc." message here, so it is not an SE-specific issue sadly.

Tested with mods and without your file, it does indeed do the same. Game bug.

**Comment by BalduredAtMyGate** [comment]
I am having the same problem but the game crashes. Old mods that worked before is creating this message for me and yes i have updated them to the latest version.
