### ISSUE TITLE
Problem with v2

### ISSUE THREAD

**Issue by Moonfaerie** [Norbyte/bg3se#26]
I downloaded v2 but my mod manager tells me that v1 is installed.  I clicked the v2 download and have 3 copies of the zip file.  the .dll says it was last modified  on Aug 15, which would be v1 I believe.

So where is v2 then?

**Comment by senthhh** [comment]
Same problem

downloaded and extracted from file to bin directory: BG3SE-Updater-wConsole-v2.zip

log:
BG3Ext v1 built on Aug 27 2023 17:54:31
Game version v4.36.69.438 OK

**Comment by Delphiniuswastaken** [comment]
I am having the same exact problem.

I have tried to re-download the file multiple times and the console will only show that it's v1.

**Comment by Norbyte** [comment]
There is a new launcher version out that should help debug these issues; can you check it out?
https://github.com/Norbyte/bg3se/releases

**Comment by senthhh** [comment]
> There is a new launcher version out that should help debug these issues; can you check it out? https://github.com/Norbyte/bg3se/releases

unfortunately no changes. in the build log from a different date, but version 1. also a mod that requires version 2 does not work



BG3Ext v1 built on Aug 24 2023 13:25:57
Game version v4.36.69.438 OK
bg3se::ExtensionStateBase::LoadConfigs(): Module 'Daughter of Lolth - Chosen Path is targeting version v2 that' doesn't exist's more recent than the current version!
STARTUP ERROR: Module "Daughter of Lolth - Chosen Path" requires extension version 2; current version is v1

**Comment by Norbyte** [comment]
Ah, I see the issue.
Extender v2 requires game version v4.36.86.210 (i.e. Patch 2) or later.

**Comment by senthhh** [comment]
> Ah, I see the issue. Extender v2 requires game version v4.36.86.210 (i.e. Patch 2) or later.
update bg3 to v4.36.86.210, now bg3ext v2. Thanks a lot

BG3Ext v2 built on Sep  4 2023 22:39:05
Game version v4.36.86.210 OK

**Comment by Delphiniuswastaken** [comment]
I'm just going to say it.

I hate the problem was that my game was not updated. When I triple checked it before trying to mod things.

Now that I have re-downloaded the game via Steam it is working.

Thank you so much.

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
