### ISSUE TITLE
Game crashing after recent update

### ISSUE THREAD

**Issue by dlykely** [Norbyte/bg3se#262]
Also getting the same issue as others posted here. A workaround i tried was i reinstalled mod fixer but i'm not sure if the bug with mod fixer where quest items aren't being recognized by the quests is still there. Some of the character creation option bars are also out of frame like this one on the hair color option. Not sure if this is because of script extender's absence or related to other mods or the recent update. Waiting patiently for the creator's script extender update <3 <3
![image](https://github.com/Norbyte/bg3se/assets/160250270/12e52126-b04f-4d9f-aa68-269a80ebacf4)

**Comment by ut316ab** [comment]
That has to do with the Improved UI mod, it has nothing to do with the script extender.

**Comment by DaelonDuluc** [comment]
It's not a bug.  The team will get the script extender updated soon.  It's the update.  This happens every time.  Just be patient.  :)

**Comment by mrcellal** [comment]
apparently the author of improved UI is at work, but will fix after. So today sometime?

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
