### ISSUE TITLE
Hey Team!  Patch #6

### ISSUE THREAD

**Issue by DaelonDuluc** [Norbyte/bg3se#265]
I know y'all will get the update in in the next couple of days at the latest.

I just wanted to take a moment to thank you for all that you do and know that there are plenty of us that have been through this before with you and know you can be depended on to make everything work perfectly as soon as possible.

Anything you need we're here for you.

Thanks so much for all you do!

**Comment by Saturnnd** [comment]
We should donate

**Comment by j3nesis87** [comment]
Does Norbyte have a Kofi? Happy to sling them a few quid.

**Comment by moore1emu** [comment]
i was trying to find a place to donate, anyone know how?

**Comment by Jephry5** [comment]
I would definitely donate as well!

**Comment by zapmasters** [comment]
Same, where to donate??

**Comment by Saturnnd** [comment]
At least we can give gime here stars for his project i keeplooking for the donation
https://github.com/Norbyte?tab=repositories

**Comment by neb10ben** [comment]
Thanks for your dedication love you all ♥ GL in being the best around ♥

**Comment by pineapplestars** [comment]
Definitely, thank you so much for all the hard work! It must be super stressful but it's very much appreciated <3

**Comment by jeffstokes72** [comment]
Yeah I'd happily Pateron this project or something too

**Comment by AstarionsAngel** [comment]
So I'm having issues as well since patch 6 came out, do we have any idea when this issue will be fixxed?
![image_2024-02-16_125627453](https://github.com/Norbyte/bg3se/assets/160282155/d62c733b-c9c5-420d-807c-fd868eb3d1f8)

**Comment by curtlandia** [comment]
Dude do you really have to ask? You posted this in an issue thread where the literal creator is saying he is working on it.

**Comment by Dhermann27** [comment]
> So I'm having issues as well since patch 6 came out, do we have any idea when this issue will be fixxed? 

Boo this man! Boooooo!

**Comment by iiiisy** [comment]
Now it is possible to start a new save with the mods, but has anyone tested whether, when saving and exiting, it is possible to return to the save without the crash?

**Comment by Grieverff** [comment]
[AstarionsAngel](https://github.com/AstarionsAngel) 
I'm not sure what I did.but I updated the Improved UI Release Ready mod on nexus, then deleted it DWrite.dll and ScriptExtenderSettings.json, launched the game.then I added the file again DWrite.dll and created a new ScriptExtenderSettings.json.After that, the game starts and BG3ModManager does not swear at the remaining files for mods.I'm not sure if the mods work as they should, but at least the game doesn't crash

**Comment by johnsully83** [comment]
Appears to be fixed (at least for my mods) as of this commit:
https://github.com/Norbyte/bg3se/commit/ea154c9b3b59415928943f6814a8a076dbfd664d

**Comment by johnsully83** [comment]
it updates as you launch, you don't explicitly download any update.  It's possible there are still more issues, there have been updates rolling out all day, but this last change was the first time i could load a game fully, and from what I can tell most of my mods seem to be working fine (Party Limit Begone, 5e Spells, Level30 all confirmed to be working)

**Comment by callistowrites** [comment]
> > Appears to be fixed (at least for my mods) as of this commit: [ea154c9](https://github.com/Norbyte/bg3se/commit/ea154c9b3b59415928943f6814a8a076dbfd664d)
> 
> So sorry if I sound dumb as heck, but where do I download the updated version, or is it the same one and it updates when you launch type thing?

Your BG3MM should update it automatically, but if you're concerned, when you're in the mod manager you can click 'Tools' and click 'download and install script extender' (ctrl + shift + alt +T)

**Comment by Dhermann27** [comment]
> You do realize that this is "free" and that the creators are in no way obligated to make you happy? Just deal with it and stop acting like a baby who didn't get their baa-baa. Sheesh. Whatever happened to patience? It's been less than 12 hours and seems to be fixed.

I meant "Boo the commenter." Not "Boo the author for taking a very reasonable amount of time to make a major update." Have a good day friend.

**Comment by SWUSpeedy** [comment]
Yup, seems to be working now.  Or at least, I'm able to load the save; it doesn't crash at 50% with the script extender error.

**Comment by Grieverff** [comment]
[johnsully83](https://github.com/johnsully83)
I recommend that you remove the Party Limit mod, it is too laggy, it is better to simply select the number of your companions through the console.

**Comment by affectingly** [comment]
> [johnsully83](https://github.com/johnsully83) I recommend that you remove the Party Limit mod, it is too buggs it is better to simply select the number of your companions through the console.

Yeah, I'd also remove anything else that helps manage party membership. I think because they changed the way you can recruit different members (You can just add someone and choose who to dismiss at the same time) that that code has changed too significantly for it to be working appropriately. So aside from party limit, the load stone mod that lets you add/dismiss on the go.

**Comment by tri-jesseface** [comment]
Thank you so much for your help. If anyone's found a KOFI I'd love to contribute.

**Comment by jeffstokes72** [comment]
I silent exit when I try to pick locks, each time. Im running a lot of mods, and not complaining. Just dont know if there's a way to get a crash dump to them you know? Or if its expected till the release is officially supported and all.

**Comment by tri-jesseface** [comment]
No match found for mapping 'ls__GlobalAllocator' [CRITICAL]
No match found for mapping 'ls::FixedString::CreateFromString' [CRITICAL]
No match found for mapping 'ls::FixedString::GetString' [CRITICAL]
No match found for mapping 'EoCServer2/EoCClient2' [CRITICAL]
No match found for mapping 'ecl::EoCClient::HandleError' [CRITICAL]

In case this is helpful, this is printing when I'm running DeBug. I'm not able to load the game past 100%; (I've reinstalled, validated, downloaded and installed manually, etc...) Please don't feel any pressure, I just wanted to contribute some print out.

**Comment by PhilippeBolduc13** [comment]
> > > Appears to be fixed (at least for my mods) as of this commit: [ea154c9](https://github.com/Norbyte/bg3se/commit/ea154c9b3b59415928943f6814a8a076dbfd664d)
> > 
> > 
> > So sorry if I sound dumb as heck, but where do I download the updated version, or is it the same one and it updates when you launch type thing?
> 
> Your BG3MM should update it automatically, but if you're concerned, when you're in the mod manager you can click 'Tools' and click 'download and install script extender' (ctrl + shift + alt +T)

I am using vortex mod (from Nexus) and I just dropped the the Dwrite.dll in the bin folder. Will it update automatically? (I am also sorry if I sound stupid, I am new at modding games)

**Comment by tri-jesseface** [comment]
> > > > Appears to be fixed (at least for my mods) as of this commit: [ea154c9](https://github.com/Norbyte/bg3se/commit/ea154c9b3b59415928943f6814a8a076dbfd664d)
> > > 
> > > 
> > > So sorry if I sound dumb as heck, but where do I download the updated version, or is it the same one and it updates when you launch type thing?
> > 
> > 
> > Your BG3MM should update it automatically, but if you're concerned, when you're in the mod manager you can click 'Tools' and click 'download and install script extender' (ctrl + shift + alt +T)
> 
> I am using vortex mod (from Nexus) and I just dropped the Dwrite.dll in the bin folder. Will it update automatically? (I am also sorry if I sound stupid, I am new at modding games)

SFAIK, yes. There's an updater bulit inside of it when it communicates with the server on load.

**Comment by Rogue-Demon-King** [comment]
Will SE update even If I'm running an older game version with Steam in Offline mode? I'm really confused on how BG3SE operates as it obfuscates everything from me and I hate that lol.

**Comment by VeniceTwicen** [comment]
I'm sorry if my question sounds stupid, but my SE can't seem to update to the latest version unless I use the updaterless version:https://bg3se-updates.norbyte.dev/Channels/Release/ManualInstall.zip
I get a message saying "Script Extender update failed; make sure you're connected to the internet and try again. Unable to download manifest (35) SSL connect error." What should I do?

**Comment by jeffstokes72** [comment]
> I'm sorry if my question sounds stupid, but my SE can't seem to update to the latest version unless I use the updaterless version:https://bg3se-updates.norbyte.dev/Channels/Release/ManualInstall.zip I get a message saying "Script Extender update failed; make sure you're connected to the internet and try again. Unable to download manifest (35) SSL connect error." What should I do?

Check your security software (firewall, etc) to see if its being blocked, would be my go-to for this.

**Comment by VeniceTwicen** [comment]
> Check your security software (firewall, etc) to see if its being blocked, would be my go-to for this.

The problem is solved. I didn't expect it to be so simple. Thank you very much for your help.

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
