### ISSUE TITLE
Steam Auto-Updated before SE and Mods

### ISSUE THREAD

**Issue by itziebitzie** [Norbyte/bg3se#266]
So, I am fairly new to modding steam games and did not know I was supposed to turn off auto-updates. Patch 6 downloaded before my mods and SE could get updated. I haven't ran the game at all or tried to remove mods or anything. I've heard that, since it updated, my previous saves could be ruined. Anyone know if it is save for me to play or a way for me to fix it if it is messed up?

**Comment by jeffstokes72** [comment]
SE is updated as of hours ago. Other mods are dependent on their creators. If you're worried about it, wait I guess till all your mods are updated

**Comment by itziebitzie** [comment]
So it doesn't make a difference that patch 6 downloaded before SE? I have auto updates off now just in case.

**Comment by jeffstokes72** [comment]
Nah the mods use symbolic links looks like to shim files into place (I think thats what I'm seeing anyway). the main thing you'll hit is some mods wont have been updated at all yet for patch 6. and patch 6 was pretty robust, might be a few days, etc.

**Comment by itziebitzie** [comment]
Alright so just wait til all my mods are updated and I should be good? Thank you so much!

**Comment by jeffstokes72** [comment]
Yep should be fine :)
