### ISSUE TITLE
Attempted to send extender message to user 65537 that does not understand extender protocol

### ISSUE THREAD

**Issue by adriant1978** [Norbyte/bg3se#269]
Since game patch 6 / extender v14, I am now getting this error when attempting to use **Ext.Net.PostMessageToUser**, e.g.

`Ext.Net.PostMessageToUser(playerID, NETMSG_CHANNEL, Ext.Json.Stringify(msg))`

**Comment by adriant1978** [comment]
Custom variable syncing also appears to be broken, I assume by the same underlying issue:

`S >> Ext.Vars.RegisterUserVariable("Foo", { Server = true, Client = true, SyncToClient = true })`
`S >> _C().Vars.Foo = "Bar"`
`S >> Not sending extender message to peer 1 as it does not understand extender protocol!`

**Comment by Norbyte** [comment]
This should be fixed now

**Comment by adriant1978** [comment]
Confirmed fixed. Thank you!
