### ISSUE TITLE
Game crash on modifying entity component twice in one engine tick

### ISSUE THREAD

**Issue by gavrant** [Norbyte/bg3se#273]
The following sample code results in a "Script Extender Crash" (or occasionally, in a nil Lua error logged in the SE console):
```lua
function MainFunction(caster, target)            
    local proxyMarker = Osi.CreateAtObject("06f96d65-0ee5-4ed5-a30a-92a3bfe3f708", target, 1, 0, "", 1)
    CreateProxy(caster, proxyMarker)
    CreateProxy(target, proxyMarker)
end

function CreateProxy(actor, proxyMarker)
    local proxy = Osi.CreateAtObject(Osi.GetTemplate(actor), proxyMarker, 1, 0, "", 1)

    local actorEntity = Ext.Entity.Get(actor)
    local proxyEntity = Ext.Entity.Get(proxy)

    if actorEntity.Voice and actorEntity.Voice.Voice then
        if not proxyEntity.Voice then
            proxyEntity:CreateComponent("Voice")
        end
        proxyEntity.Voice.Voice = actorEntity.Voice.Voice -- <--- CRASHES HERE on second CreateProxy call
        proxyEntity:Replicate("Voice")        
    end
end
```
The crash happens on the second call of ```CreateProxy```, in the ```proxyEntity.Voice.Voice = ...``` line. If the second call of ```CreateProxy``` is moved to a timer triggered 100 milliseconds later, the crash is gone. So I believe it happens only if ```CreateProxy``` is called twice in a single engine tick.

BG3 SE version: BG3Ext v14 built on Feb 17 2024 14:29:05
The game updated to Patch 6.
The above sampe code did not crash just a week ago, on the previous versions of the game and SE.
![SECrash](https://github.com/Norbyte/bg3se/assets/17292867/e3b05153-4e77-4d8a-ba9a-3fddcf92fcf7)

**Comment by Norbyte** [comment]
Hi,

This should be fixed now in the latest release.

**Comment by gavrant** [comment]
Thank you! Tested on "BG3Ext v14 built on Feb 17 2024 20:34:22", no crashes or errors in the console, the voice component is properly copied for both actors.
