### ISSUE TITLE
MessageBoxYesNoClosed event not working

### ISSUE THREAD

**Issue by adriant1978** [Norbyte/bg3se#274]
Nothing seems to happen regardless of whether Yes or No is clicked.

`S >> Ext.Osiris.RegisterListener("MessageBoxYesNoClosed", 3, "after", function (char, msgbox, option) Ext.Utils.PrintWarning("Selected option: " .. option) end)`
`S >> Osi.OpenMessageBoxYesNo(Osi.GetHostCharacter(), "Is this thing working?")`
`S >>`

Was working prior to patch 6 / SE v14.

**Comment by Norbyte** [comment]
I've checked and the game doesn't seem to throw any Osiris even after you close a message box anymore.
Seems like a vanilla bug sadly

**Comment by adriant1978** [comment]
For what it's worth to anyone else impacted by this, I found a sort of workaround for my use case of OpenMessageBoxYesNo/MessageBoxYesNoClosed by using **ReadyCheckSpecific**/**ReadyCheckPassed** instead:

`Ext.Osiris.RegisterListener("ReadyCheckPassed", 1 ,"after", function(id)`
  `if ( id == "MyID" ) then`
    ` ...`
  `end`
`end)`

`Osi.ReadyCheckSpecific("MyID", "MyString", 1, Osi.GetHostCharacter(), "NULL_00000000-0000-0000-0000-000000000000", "NULL_00000000-0000-0000-0000-000000000000", "NULL_00000000-0000-0000-0000-000000000000")`

_MyString_ is defined in **Public\MyModName\Localization\ReadyChecks_Descriptions.lsx**

**Comment by Norbyte** [comment]
This is still broken in the latest hotfix sadly; ReadyCheckSpecific/ReadyCheckPassed and manipulating translated strings is the current "accepted" workaround.
