### ISSUE TITLE
Problems I'm currently experiencing

### ISSUE THREAD

**Issue by sachan27** [Norbyte/bg3se#275]
①I am using the Auto Loot Seller V3 mod, but when I opened the commercial bag of this mod, I was unable to move my luggage and it seemed that I was unable to select other characters. And then shut down. 
I contacted the creator of this mod yesterday and was told that it was probably a BG3SE issue. I have contacted the mod creator again, but I would like to see if there are any problems on the BG3SE side as well.

②I tried to trade with a merchant in the Emerald Forest, but the items the merchant had were clearly decreasing.
when I try to cancel a transaction, the screen seems to freeze temporarily.

③When attacking an enemy, there are times when it does not move even if you choose to attack even though there is no cover.
This is especially common with the barbarian's throwing attack, but it also occurs with other characters.
I don't know if this is a problem on the BG3 side or a mod-related problem.

There may be other issues as well, but if there is a problem with BG3SE, I would like to see it fixed.

**Comment by sachan27** [comment]
![スクリーンショット 2024-02-18 021839](https://github.com/Norbyte/bg3se/assets/160276130/c3c72b70-2e32-4d62-8460-c482facb6262)

① I took a screenshot of the situation when the problem occurred.

**Comment by FallenStar08** [comment]
> I contacted the creator of this mod yesterday and was told that it was probably a BG3SE issue. I have contacted the mod creator again, but I would like to see if there are any problems on the BG3SE side as well.

The mod author is an idiot, I know him, he's me.

The issue doesn't seem to be related to SE anymore (it's up to date now) it's something else, I'll have a look soon :tm:
