### ISSUE TITLE
Please stop complaining that the game isn't working right now

### ISSUE THREAD

**Issue by HnyxLmn** [Norbyte/bg3se#276]
They are still working on the update to the script extender. The game is still going to have bugs or crashes until it is fully done, it's probably going to take a couple days at the latest to get done. Please have some patience with the creators, they will post the full release when it is done. This is what always happens when a new patch drops, your mods will not work for a bit!

**Comment by Ex0ticMG** [comment]
my games is working again i did nothing

**Comment by dlykely** [comment]
Mine too no crashes anymore. I've seen the new kisses and idle animations already as well. Only nitpick is i get repeat notification on getting the night spear and the inspiration that comes with it. I'm on wyrm's crossing already.

**Comment by Apalll** [comment]
Every new patch there is a couple new threads with the same "hewp game crashing"

**Comment by uraniummore** [comment]
The author works for free and these people not only don't show patience, but act like they are owed something.

**Comment by Norbyte** [comment]
<3
