### ISSUE TITLE
Odd softlock upon character creation

### ISSUE THREAD

**Issue by UnstableMango** [Norbyte/bg3se#278]
After updating to patch 6 and uninstalling all mods plus updating script extender, whenever I try to start a new game, I get put in an odd storage/limbo place with several dummy actors. I've tried uninstalling and reinstalling both the game and script extender. The savefile claims I'm in character creation. Attached image shows where it puts me. 
![bg3 bug](https://github.com/Norbyte/bg3se/assets/79785153/1b7652bd-df4a-4cd3-9e24-f19ebf9462b8)

**Comment by outofserotonin** [comment]
Looks like you just need Mod Fixer.

**Comment by UnstableMango** [comment]
worked perfectly, thx

> Looks like you just need Mod Fixer.
