### ISSUE TITLE
Mods don't see Se

### ISSUE THREAD

**Issue by Klaim51** [Norbyte/bg3se#279]
The situation is as follows, no matter what version of SE, the mods still don’t see it, even those updated for the new patch
<img width="591" alt="Снимок экрана 2024-02-18 112458" src="https://github.com/Norbyte/bg3se/assets/118605733/a21bf992-a41d-483e-93a4-51e87cff54ef">
<img width="597" alt="Снимок экрана 2024-02-18 112515" src="https://github.com/Norbyte/bg3se/assets/118605733/17e5861c-831d-468f-9b9a-a5552cdc55f7">

**Comment by Saturnnd** [comment]
I had the same problem in the patch before but i solved it instalin dthe sript extender manualy. And after that y restart the computer and it works

**Comment by ReFleXzZ** [comment]
That's a problem with the Mod Manager, please open an issue there :D Hopefully LaughingLeader will fix this 😁

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
