### ISSUE TITLE
Thank you very much 😁 

### ISSUE THREAD

**Issue by ReFleXzZ** [Norbyte/bg3se#280]
I just want to thank you for the fast update, that is even working without uploading it to GitHub, because of  the update channel I suppose! 😁 (it says "built on 18th Feburary", that's why I suppose that)

Have a nice Day @Norbyte and all other contributers which work on this ❤️

**Comment by ReFleXzZ** [comment]
Oh and for everyone who have a problem with the character creation: Try to move the contents of "%LocalAppData%/Larian Studios\Baldur's Gate 3" to a different location as a backup. The game will ask you because of the brightness settings and some other settings. Hope this helps

**Comment by kineci** [comment]
> I just want to thank you for the fast update, that is even working without uploading it to GitHub, because of the update channel I suppose! 😁 (it says "built on 18th Feburary", that's why I suppose that)
> 

Where did you get the update? I'm using BG3 Mod Manager and the game still does not launch when I delete and reinstall Script Extender.

**Comment by dlykely** [comment]
Thanks to the team for the update! My game only crashed once due to unknow reasons but so far it's been good! <3 <3

**Comment by Norbyte** [comment]
<3
