### ISSUE TITLE
Freeze When Exiting Trade Session with WIthers

### ISSUE THREAD

**Issue by WDF00** [Norbyte/bg3se#282]
I am using mod "Trade With Withers" having enabled both the base mod plus the optional addon "AIO", which stocks Withers with lots of items.  This worked fine until Patch#6 became active.

Problem Description: After a trading session, independent of whether or not items were exchanged, exiting the session returns to the expected conversation menu.  Clicking "Leave" results in no action with the character held in place (freeze-like).  The game does not respond to "escape" and does not allow quitting normally.

Troubleshooting: With only the base mod installed, conversation exits normally.  The AIO option (which adds the items I am interested in acquiring) results in the problem.

The mod author believes the issue is caused by the Script Extender (see Bug Report on mod page): [https://www.nexusmods.com/baldursgate3/mods/2458?tab=bugs]

**Comment by callistowrites** [comment]
I had the same problem. And it's not just the base Trade with Withers AIO - even the mods that were created by another to work with the Trade with Withers mod (for food and jewelry) don't work.

It's something about giving Withers his own vendor inventory that seems to be the problem. You've always been able to trade with Withers, like you can trade with a lot of NPCs in game, the base Trade with Withers mod just gives him more gold to buy your stuff. But something about giving Withers inventory of his own, not just what you sell him, seems to break the function.

**Comment by BurgersMcFly** [comment]
I did say that this is 100% on script extender but later added that I'd wait for script extender to push some more updates to troubleshoot/debug the mod. Everything worked fine before the update and debugging this with no errors is going to be a guessing game.

**Comment by clielausis** [comment]
I noticed that attempting to trade with Volo in camp results in a freeze.  That implies that the issue is with trading in camp.

**Comment by BurgersMcFly** [comment]
This is why I want to wait a bit before I try to debug the mod. Similar issues reported here as well:

[Problems I'm currently experiencing · Issue #275 · Norbyte/bg3se (github.com)](https://github.com/Norbyte/bg3se/issues/275)
②I tried to trade with a merchant in the Emerald Forest, but the items the merchant had were clearly decreasing.
when I try to cancel a transaction, the screen seems to freeze temporarily.

[Game crashes whenever I do a dice roll in conversation · Issue #272 · Norbyte/bg3se (github.com)](https://github.com/Norbyte/bg3se/issues/272)

**Comment by callistowrites** [comment]
I've got Improved UI, fully updated, and it doesn't make any difference.

**Comment by BurgersMcFly** [comment]
Seems like this is a vanilla bug:

[baldurs gate 3 crashing after trading site:www.reddit.com - Google Search](https://www.google.com/search?q=baldurs+gate+3+crashing+after+trading+site:www.reddit.com&sxsrf=ACQVn0-ZkG1Wtsk3Xn7l0kIerjV1_wDsCg:1708372211117#ip=1)

[Selling/Bartering Crashing Game? : r/BaldursGate3 (reddit.com)](https://www.reddit.com/r/BaldursGate3/comments/1aslrfa/sellingbartering_crashing_game/)

[Patch 6 issues with merchants : r/BaldursGate3 (reddit.com)](https://www.reddit.com/r/BaldursGate3/comments/1asjqcv/patch_6_issues_with_merchants/)

**Comment by Norbyte** [comment]
As others already said, this is/was in fact a vanilla bug, not SE related.
