### ISSUE TITLE
Keeps crashing when I try to do an ability check?

### ISSUE THREAD

**Issue by Mak-Dawg** [Norbyte/bg3se#284]
Ever since the latest game update I can't do an ability check, as the game crashes before the d20 even shows up. I can't figure out why. I've pasted by mod load order below. I use BG3MM. Mods 38-44 use the script extender. I also tried using the diagnostic generator and nothing came up. Any idea whats wrong?

0	Customizer, Alana
1	Honour, GustavDev	
2	DiceSet_06			
3	DeityForAll, Djmr			
4	FaithfulFaithlessD, Margerard			
5	SilvanusDeity, OddCoward		
6	Origin Gods, Kilay		
7	Highlight All, kou Shared, GustavDev	
8	Scratch_And_Shovel, Syrchalis			
9	Draconic Dyes, RadonWolf		
10	AS_ExtraDyes_Bundle, AstralSprout				
11	Aether's Black Dye, Aetherpoint			
12	DyeDyeDye, Liareth			
13	Everybody Dyes Unlimited Dyeing, Loktide			
14	SakuraDice, TsukiSoft			
15	Stackable Items, Balzhur		
16	NoInspCap, FrozenLayer			
17	Gold Weight Zero, Loktide		
18	Permanent Speak With Animals, Joco	
19	Purchasable Camp Clothes and Underwear - All In One, anshela		
20	UnderwearOfAbilityScores, Belinn	
21	Slightly Better Dragonborn, IndecisionIncarnate	
22	Feat Every 1 Level, kou Shared, GustavDev	
23	ASTRL Glowing Eyes, Astralities			
24	EotB Main - EyesOfTheBeholder, labotor	
25	EotB Extra - ExtraEyeColors, labotor			
26	EotB Eye Preset - GlowEyes, labotor			
27	ElleCurios, Elle		
28	Haarashi, 773PPVM		
29	Selune'sSentinel, Adlock221b			
30	TruerResurrection, DonkeyTheBard		
31	LegendaryEquip, DonkeyTheBard			
32	LightBothWeapons, TumblingLemmings			
33	Unvisual Volo's Eye, Takikun			
34	chooseyourequipment, LostSoulMan		
35	Raised Ability Score Caps, IndecisionIncarnate	
36	Pale Oak, Ganred	
37	LathandersNightLight, Keefr		
38	AutolootAura, unamazement			
39	Tutorial Level Exit Full Release, SwissFred			
40	BetterGear_MoonDruid, Syrchalis		
41	RichTraders, yakuzadeso	
42	TutorialChestSummoning, wesslen			
43	Deity Tag Activator, Lightboom		
44	Party Limit Begone, Sildur		
Override	HighlightEverything				
Override	ImprovedUI	AlanaSP,ShinyHobo,Djmr,Zee		
Override	ImprovedUI Assets		
Override	ModFixer

**Comment by lilith6lamber** [comment]
I had the same issue. Updating ImprovedUI to v3.18.1 fixed this.

**Comment by Mak-Dawg** [comment]
> I had the same issue. Updating ImprovedUI to v3.18.1 fixed this.

Thanks! I thought I had updated all my mods, guess I missed one lol
