### ISSUE TITLE
Game crashes on roll

### ISSUE THREAD

**Issue by divineBatman** [Norbyte/bg3se#285]
So I'm playing Dark Urge and at the scene in Act 2 where I would kill the one I love when I try saving throw or any other throw during the scene the game crashes. I tried disabling most of the mods I have, but the problem continues. 

Here are the mods I run: 
Index	Name	Author	FileName	Tags	Dependencies	URL
0	AbbotCrest	fawert	AbbotCrest_34fde8c3-0411-4a11-968d-ed4ae5cb554a.pak			
1	Anduril	Lykon / Kiderion	Anduril_67711d04-9794-4cf1-b3c6-1639b466f8a6.pak			
2	AnnPointBlankShot	Annolyin	AnnPointBlankShot_5cc17320-04a4-4013-99b6-0d7d8cb115a9.pak			
3	ApostleScythe	Chromosome16	ApostleScythe_5a08320f-cb85-4737-a5cd-0a5deb180b9e.pak			
4	ArmourOfVengeance	kahashi69	ArmourOfVengeance_e2f68acb-3c55-4794-844e-da25420b0792.pak			
5	BasketEquipmentNSFW	AnteMaxx	BasketEquipmentNSFW_a9e98a1f-7a59-4b70-be39-1f69924c0b80.pak			
6	BetterDualWielding	TumblingLemmings	BetterDualWielding_c4b61fcc-5450-49da-a2c1-6b24acdd4dd9.pak			
7	BetterGear_MoonDruid	Syrchalis	BetterGear_MoonDruid_d4d885b7-061d-4ca4-ab2b-77eb0af8555c.pak			
8	BG3ShadowSorcerer	Baaleos	BG3ShadowSorcerer_38291fe1-40a3-4af7-bbbd-c9a55f3e39c0.pak			
9	BloodOfLathanderReDivined	NukaCola069	BloodOfLathanderReDivined_c77763a2-5770-4611-8e8e-415ac06ad7d6.pak			
10	Camp Boots	anshela	CampBoots_0038aa8b-0a46-4f78-9de0-95c2335b3488.pak			
Override	Trips_Shaders	Trips	Trips_Shader_166bdea1-ec32-4cdb-bd75-98affd58dd92.pak			
Override	HalsinReaves	StableFluffy	HalsinReaves_ee4679d5-7ded-40e8-8245-f3439ea2b444.pak			
13	Carry Weight Increased 9000	Mharius	Carry Weight Increased 9000_1d6ece6c-b9e1-430e-8263-7d223a78abmh.pak			
Override	Female Gale Voice Conversion Style A v2.1	StableFluffy	Female Gale Voice Conversion Style A v2.pak			
15	CelestialDevaGear	fawert	CelestialDevaGear_15ae8c91-6f83-4f0f-ab8b-831e94d9e9a1.pak			
Override	Fem Gale Voice B Spells-Combat-Interaction Add-on	StableFluffy, Arkien	Fem Gale Voice B Spells-Combat-Interaction Add-on_a97bc820-dad2-4cb9-823a-0dad31bfc3a0.pak			
17	ClemencySword	fawert	ClemencySword_e7999408-c55a-4d90-a0e5-fb6784f8231d.pak			
18	Clerics	Baltavi	Clerics_eef7b885-1423-4096-abd6-7a5db5f871db.pak			
19	ClericUnofficialClassPatch	Avalonica	ClericUnofficialClassPatch_8746e310-62ae-4cf4-9d5c-9dd10674c7c8.pak			
20	CreateEquipment	Sindae	CreateEquipment_12d4fdc5-0b13-460f-91c5-beaac4ab9123.pak			
21	Custom Item Pack	Sumajin	SUM_9a5b4585-0677-45a3-be5c-0cdaa30123fa.pak			
22	Custom Subclass Icons	Dragonify	SubclassIcon_f26ba921-5f61-45ec-9235-4ae836a42f88.pak			
23	Customizer	Alana	Customizer_83b4e98f-28b3-4e75-915d-4cf795ec2b74.pak			
24	DaddyKMommaWyll	snk4211	DaddyKMommaWyll_c35b336b-1545-434c-9b65-b4f517dd5920.pak			
25	DatabaseCleaner	wesslen	DatabaseCleaner_08e267cf-bf28-4e29-8711-8282ed017fcb.pak			
Override	VC_Wyll	Arkien	VC_Wyll_d6596f6b-796e-4d9f-acf5-97b777aa57e0.pak			
27	Daughter of Lolth - Chosen Path	Rukongai	DaughterofLolthChosen_e64e2e53-92c3-444e-a374-0d6638ed4e99.pak			
28	DeityForAll	Djmr	DeityForAll_23b9ad37-9fa6-4d25-9346-deeeeeeeeeee.pak			
29	DiscipleOfTheFirstFlame	Nitreaux	DiscipleOfTheFirstFlame_9fd2fdbf-a71a-4eb2-9750-954669465c0c.pak			
30	DIvineAllegiance	PavloGarmata	DIvineAllegiance_ae01a06b-06e8-4488-b1ea-173ab94e7082.pak			
31	Drakewarden	Lykon	Drakewarden_a951d531-dd86-4ff6-8d96-a5358fa95821.pak			
32	DreadOverlord	aheram	DreadOverlord_2e686664-8fbb-4e08-9ec2-3eea5d0300ab.pak			
33	Druid_Perfection	Syrchalis	Druid_Perfection_55249f39-faa9-4e51-a36c-0ac6560d8a0c.pak			
34	EnemiesEnhanced	Khione, ropya, kvnbass	EnemiesEnhanced_7deea48e-8b9d-45e4-8685-5acfd0ce39ad.pak			
35	Firearms	AnxietyTheOrk	Firearms_6cde95a8-2682-4645-9b38-2964962fe8e0.pak			
36	FireproofKarlach	Belinn	FireproofKarlach_0d77ef52-11ac-4031-8027-1a625834a16c.pak			
37	FizbansTreasuryOfDragons	3XC4L1B3R	FizbansTreasuryOfDragons_1e64a434-4318-42fe-9388-e6aa49505094.pak			
38	Frostmourne	Curotar	Frostmourne_7be8baa9-50e8-4c23-aefd-e1633d619bc6.pak			
39	GalePals	snk4211	GalePals_d4206b6c-9753-4d35-beac-209e04125f33.pak			
40	Gold Weight Zero	Loktide	Gold Weight Zero_GOLDWEIG-HTZE-RO12-4444-deeeeeeeeeef.pak			
41	Harness Divine Power TCE	Lumaterian	Harness Divine Power TCE_ca61feb4-93d2-4390-acac-cae2b462207d.pak			
42	Hexblade	Feriat	Hexblade_e1eb6d1a-5922-4964-bfd7-c971e71e351a.pak			
43	Infernal Dice	SeanConnorX0	MagDice_748889fd-8ef9-4241-912b-b89b2d957589.pak			
44	InfinityRing	PavloGarmata	InfinityRing_9f06ac5a-9828-4294-8294-c14465add4c6.pak			
45	LegendaryEquipTonedTUT	DonkeyTheBard	LegendaryEquipTonedTUT_a5206fb2-bac3-4021-82b7-09824bd37e35.pak			
46	LegendaryItems	Oiff	LegendaryItems_061529e0-ddab-402e-a3ed-53caf7701290.pak			
47	Lightbringer- A Paladin Overhaul	Astralities and EthicalCrusader	Lightbringer- A Paladin Overhaul_a6a06d11-4379-49e1-8edb-61c1aaa26bec.pak			
48	magicitemsplus	LostSoulMan	magicitemsplus_9284977d-a7f2-4bb3-a1f4-73748e8ccf8b.pak			
49	More Mage Gear	pooteeweet	PTW_Sorcerer_94fed047-7d79-41e3-9d1c-1a3b3de781e4.pak			
50	MyPetsAreSafe	isamuchu	MyPetsAreSafe_9cda7308-fc26-4abc-8c2e-0049f96351e7.pak			
51	NoIntroPak	Caites	NoIntroPak_12a1fc9f-e39d-43f2-ab49-25026f073e46.pak			
52	NoRomanceLimit	wilhelmw	NoRomanceLimit_726b130c-6139-11ee-8c99-0242ac120092.pak			
53	NPCs Dont Flee From Summons	Pwybman	NPCsDontFlee_fbfc236d-17b5-47a1-a918-d1ecb17c6709.pak			
54	Olympian Weapons	dmarquez	Olympian Weapons_dcac7271-ee4e-48b4-97fb-f0ebe7bfe10c.pak			
55	Plus Backgrounds - Main	Raizan	Plus Backgrounds - Main_bcc57c57-42e9-4da4-99a3-b4629e450d98.pak			
56	PolearmMasterWithTrident	AnxietyTheOrk	PolearmMasterWithTrident_73bfccac-270d-4c20-abb4-3c5687f1fdba.pak			
57	PowerHunger	Siael	PowerHunger_b2cf9ce7-3836-4b07-b245-9b1e0a299110.pak			
58	Purchasable Camp Clothes and Underwear - All In One	anshela	PurchaseClothesAllInOne_9d77a376-98b4-4b8b-8256-4dfdb110859a.pak			
59	RaritiesOfTheRealms	clintmich	RaritiesOfTheRealms_d23881c2-f6b5-4e64-a2fe-f55c9538ab1e.pak			
60	ReaperArmour	kahashi69	ReaperArmour_3dcd19a5-3632-43c2-8f62-964c9e8c9ab9.pak			
61	Rebalance_Lvl6_Spells	Syrchalis	Rebalance_Lvl6_Spells_8dcc6c86-b80c-4920-824d-f21ea796bb32.pak			
62	Scantily Camp Outfit	Crosscrusade	SCO_73928ffc-07c0-46ac-8cf4-86a693b0cd92.pak			
63	SecretScrolls5eSpells	darkcharl	SecretScrolls5eSpells_b093bc44-ccf9-4eec-b5ec-e96a6f2940f9.pak			
64	Shadar-Kai	NellsRelo	Shadar-Kai_c36d595f-70d1-44f1-8ca6-4ad14186f489.pak			
65	Skeleton Key	Faane	Skeleton_Key_c9327dea-fd58-4803-a201-27a678943ffc.pak			
66	Spells Enhanced - Sleep - A2	MaskedRPGFan	Spells Enhanced - Sleep_80350cda-1216-4dba-b8b6-b09c674f3e01.pak	Spell		
67	Stackable Items	Balzhur	Stackable Items_823cb235-Balz-47e2-8701-99752d59659d.pak	Equipment		
68	TacticianPlusHealth	Feriat	TacticianPlusHealth_6ef804ed-1dd0-4f97-9cf7-5e29a51829ca.pak			
69	Tav's Hairpack	Toarie	DFHairPack_da0b99ca-4406-49c1-bef9-3a08621280a2.pak			
70	Tav's Hairpack - Icon Patch	perseidipity	THSIconPatch_bfad4cdb-0b02-435a-96c7-06c0f6533055.pak		Tav's Hairpack	
71	The Dragonkin	Pebble	Dragonkin_34c98919-d66b-4d29-876b-a7ce7b72292f.pak			
72	TutorialChestSummoning	wesslen	TutorialChestSummoning_505c630c-79fa-49b6-9f21-29a5f2322c2d.pak			
73	UniversalArmourFixer	wesslen	UniversalArmourFixer_cabe6d93-e26a-473a-9b04-8717015bd51f.pak			
74	UnlockLevelCurve	Charis	UnlockLevelCurve_d903677e-f24b-48ec-ab20-98dcc116a371.pak			
75	VFX_Library_SHV	Shivero	VFX_Library_SHV_dd19db12-96c0-4bca-9ef6-e8d733801d23.pak			
76	VladsGrimoire	VladmirFFXI	VladsGrimoire_66666666-4444-4444-4444-666666668000.pak			
77	Volo's Dark Ersatz Eye	Xal aka Crypto_Neo	VolosDarkErsatzEye_885d2411-16f6-4430-a415-0653de12cb4b.pak			
78	WitchElf	CovenElf, labotor	WitchElf_1aa49383-9208-4cc0-96b6-e827819d71d0.pak			
79	5eSpells	DiZ	5eSpells_fb5f528d-4d48-4bf2-a668-2274d3cfba96.pak			
80	CompatibilityFramework	BG3 Community	SubclassCompatibilityFramework_67fbbd53-7c7d-4cfa-9409-6d737b4d92a9.pak	Template		
81	ConfigurableEnemies	Mithras666	ConfigurableEnemies_411a64a2-0be4-467e-8ae4-302740f75bb6.pak			
82	CommunityLibrary	BG3 Community	CommunityLibrary_396c5966-09b0-40a1-af3f-93a5e9ce71c0.pak	API, Core, Library		
Override	ImprovedUI	AlanaSP,ShinyHobo,Djmr,Zee	ImprovedUI_00000000-0000-0000-0000-ImprovedUI12.pak			
Override	ImprovedUI Assets		Game_C:\Users\Eros\AppData\Local\Larian Studios\Baldur's Gate 3\Mods\ImprovedUI Assets.pak			
Override	ModFixer		Gustav_C:\Users\Eros\AppData\Local\Larian Studios\Baldur's Gate 3\Mods\ModFixer.pak

**Comment by phl0at** [comment]
To my understanding this was related to an Improved UI bug that has been fixed in a patch on the 16th or 17th (you will also need the Assets patch). Have you already updated that mod?

**Comment by divineBatman** [comment]
> To my understanding this was related to an Improved UI bug that has been fixed in a patch on the 16th or 17th (you will also need the Assets patch). Have you already updated that mod?
> 
> I also had to completely uninstall and reinstall all of my mods to get the game working after Patch 6. Just disabling them wouldn't work for me so you may need to do this as well.

I'll try, thank you
