### ISSUE TITLE
Script extender crashing mods after hotfix

### ISSUE THREAD

**Issue by TkleinBaltink** [Norbyte/bg3se#289]
The small update/hotfix that hit just now is causing the script extender to no longer find matches for the various mappings just like right after Patch 6 hit. This results in no longer being able to load into the game.

<img width="828" alt="Script extender BG3 errors" src="https://github.com/Norbyte/bg3se/assets/24541813/6e2e3ed5-9989-470e-a47c-42dfba21550d">

**Comment by AreVaskela** [comment]
Same here. Needed to remove NativeCamera and WASD movement to not crash the game.

**Comment by nepharys** [comment]
For me, the game does not crash but it seems that the script extender is not loaded (see error messages below).
I tried with and without mods, with/wo modfixer or LSLib mods from vortex. I tried downloading the script extender from github, bg3 mod manager or vortex, same error messages.

For me, only the No Romance limit does not work anymore, other mods such as Transmog or Tutorial chest seem to work ok.

![Screenshot 2024-02-20 172219](https://github.com/Norbyte/bg3se/assets/160638341/73e7ff72-e863-49de-96f8-ad430b0172e1)

**Comment by dajolieasya** [comment]
Transmog and other SE based mods, from what I see, load, but don't actually work. Everything is there in inventory, but trying to transmog an item does nothing.

**Comment by smtcpn** [comment]
Similar issue here. Only SE-based mod I have is Transmog. When I load the game I get a "Script Extender update failed. Script extender not available for game version v4.47.88.723" error. I can load into the game just fine, but cannot interact with companions or NPCs, nor fast travel or dig up dirt mounds.

**Comment by fantista** [comment]
The above temporary fix worked for me. Thank you for the information

**Comment by AreVaskela** [comment]
> **TEMPORARY SOLUTION for Steam from a kind soul on Nexus, fixed it for me, SE 14 loads now:**

This fixes SE 14, thank you very many! :)
WASD is otherwise broken: https://www.nexusmods.com/baldursgate3/mods/781?tab=posts

**Comment by moore1emu** [comment]
after the hot fix: 
![image](https://github.com/Norbyte/bg3se/assets/11082634/2bccf700-b834-4294-acf0-c39cb38ef0af)

**Comment by smtcpn** [comment]
The temporary solution posted above got rid of the script extender error message for me, but I still can't interact with NPCs, fast travel, go to camp etc. Anyone else having that issue?

**Comment by cdymak** [comment]
> **TEMPORARY SOLUTION for Steam from a kind soul on Nexus, fixed it for me, SE 14 loads now:**
> 
> https://www.nexusmods.com/baldursgate3/mods/945?tab=posts&BH=0 take exact command from the comment, it doesn't save here correctly
> 
> 20 February 2024, 6:54PM
> 
> A WORKING SOLUTION FOR STEAM PLAYERS Download previous bin files using steam console: Open a command window "Run" by pressing «Win + R» and then enter the command: steam://open/console, and then press Enter. Type command: download_depot 1086940 1419652 8231067205656009020 [] [] : download a single depot It will download previous unbroken exe files. Just copy and paste them into BG3 bin folder, and everything will work.

This works for me too, thank you so much!

**Comment by RedCanary1** [comment]
> The temporary solution posted above got rid of the script extender error message for me, but I still can't interact with NPCs, fast travel, go to camp etc. Anyone else having that issue?  

Same here. Stuck in my camp and can't interact with NPCs or use fat travel. I only use "Party limit begone" and after disabling it the game seemed to work but for some reason after 5 minutes performance just TANKED.

**Comment by dajolieasya** [comment]
I see from other comments that no other files were changed in the hotfix, only these 2 exe. Don't see any risk here.

**Comment by cocoonbug** [comment]
> **TEMPORARY SOLUTION for Steam from a kind soul on Nexus, fixed it for me, SE 14 loads now:**
> 
> https://www.nexusmods.com/baldursgate3/mods/945?tab=posts&BH=0 take exact command from the comment, it doesn't save here correctly
> 
> 20 February 2024, 6:54PM
> 
> A WORKING SOLUTION FOR STEAM PLAYERS Download previous bin files using steam console: Open a command window "Run" by pressing «Win + R» and then enter the command: steam://open/console, and then press Enter. Type command: download_depot 1086940 1419652 8231067205656009020 [] [] : download a single depot It will download previous unbroken exe files. Just copy and paste them into BG3 bin folder, and everything will work.

even after doing this, for whatever reason, my mods aren't 'enabled' in the game. 🤔 i restarted and was hopeful that would work, but it didn't

**Comment by Rich-Rulez** [comment]
So after putting files in bin folder, launching on steam this will force a download?

**Comment by GamerJD75** [comment]
> So after putting files in bin folder, launching on steam this will force a download?

I did this, got a "mismatch warning" in the launcher, & then the game played just fine with SE working.  So far it hasn't downloaded the hotfix again.
