### ISSUE TITLE
mods relying on bg3se ,have stopped working in game after the last hotfix

### ISSUE THREAD

**Issue by Taemaly** [Norbyte/bg3se#290]
Mods not working after the last  official hotfix

**Comment by CaptnRen** [comment]
I don't know if this is helpful/ to post the console notes here for Hotfix #18 issue. If not, is there a place I can send info if it would be helpful? 
![BG# Script Extender Error](https://github.com/Norbyte/bg3se/assets/160642283/5bbedd22-54ca-4373-8f68-72e0797694da)

**Comment by CanadaBry** [comment]
Have same issue with BG3SE after hotfix patch.

**Comment by GiGurra** [comment]
same

**Comment by AsUI87** [comment]
Yep.. Larian try to destroy modding, releasing small useless patch.

Am I the only one who smiled at the realization that they fixed it by breaking the game for people?

**Comment by FransBouma** [comment]
I found a lot of old code back from before Patch 4. And code that was added after or with Patch 4 isn't there anymore. It looks like a build with old code (lots of functions aren't inlined either, but size is way smaller!). Id wait a bit, probably gonna be reverted

**Comment by LiangBao1** [comment]
du nouveau ?

**Comment by grumblefoot** [comment]
Please see the other thread [https://github.com/Norbyte/bg3se/issues/293](url) where there is a workaround explanation. Happy gaming!

**Comment by Norbyte** [comment]
The mod meltdown ™️ has ended.
