### ISSUE TITLE
SE not working.. Patch 6

### ISSUE THREAD

**Issue by Haryleybutton** [Norbyte/bg3se#291]
I re-downloaded the script extender for patch 6, I've reinstalled the mods that need it. I've also launched the game through BG3 Mod Manager and through Steam as well and both times I get an Error message that says:  "Script Extender update failed. Script Extender not available for game version v4.47.88.723"  (The game doesn't crash but the mods requiring SE don't work)

Thank you :)

**Comment by TheImageworks89** [comment]
The game was updated this morning to Hotfix 18 and from the looks of it the .exe file was reorganized, which means Script Extender will need to be updated in order to work again. 

I'm sure Norbyte will get to it when they can (and I'm grateful for all the work)

**Comment by Colne73** [comment]
Hotfix 18 broke a lot of things. Revert the update if you can / want.

Read Remrenraven message here : https://www.nexusmods.com/baldursgate3/mods/781?tab=posts

**Comment by Haryleybutton** [comment]
Seems to have worked 😊 thank you!

**Comment by NinioElninio** [comment]
> I re-downloaded the script extender for patch 6, I've reinstalled the mods that need it. I've also launched the game through BG3 Mod Manager and through Steam as well and both times I get an Error message that says: "Script Extender update failed. Script Extender not available for game version v4.47.88.723" (The game doesn't crash but the mods requiring SE don't work)
> 
> Thank you :)

having the same issue here

**Comment by RKive2319** [comment]
> Hotfix 18 broke a lot of things. Revert the update if you can / want.
> 
> Read Remrenraven message here : https://www.nexusmods.com/baldursgate3/mods/781?tab=posts
> 
> Edit : That's for Steam version. Hopefully it won't break more things :D

How do you revert it?

**Comment by Haryleybutton** [comment]
@RKive2319 click on the link and look for Remrenraven's comment with instructions on how to fix it 🙂

**Comment by colt-smith** [comment]
> @RKive2319 click on the link and look for Remrenraven's comment with instructions on how to fix it 🙂

Getting an access denied error :/

**Comment by Norbyte** [comment]
The mod meltdown ™️ has ended.
