### ISSUE TITLE
Anybody facing this issue When you load an archive(game), the game automatically crashes after the progress bar reaches 100%

### ISSUE THREAD

**Issue by kyleAlexandad** [Norbyte/bg3se#292]
I installed BG3 mod manager yesterday and tried some simple mods and it works perfectly, but this morning after hotfix 18 when I open my game from last night it works for the first time but I noticed there is a message saying: script extender update failed bg3.
So what I did is uninstall the entire whole game and download it again, after this the message still exist but now every time when I tried to load my current game, it crashed when the progress bar reaches 100%. I have tried this method but it won't work
https://www.nexusmods.com/baldursgate3/mods/945?tab=posts&BH=0
Any help is appreciated.

**Comment by cypheroftyr** [comment]
yep! Same issue here. Now I'm getting an error that there is no version of script extender for this version of the game:

<img width="301" alt="script extender update failed" src="https://github.com/Norbyte/bg3se/assets/26696778/5678dfaf-d6a8-4ab0-9de3-7f6946a3f965">

**Comment by AikoTM** [comment]
You gotta wait on updates.
Also, uninstalling mods and loading a modded savegame has a high chance of making you crash or even corrupt the save.
Gotta be patient. 
If you scrolled down a bit in the comment section of the mod you posted, you'll see that Hotfix 18 itself is apparently broken, and thus the wait on mod updates or the game is gonna take a bit more than usual. 

For future cases, I recommend turning off auto-update for games you mod. It will almost always be the case that you cannot play until the mods get updated.

**Comment by cypheroftyr** [comment]
> You gotta wait on updates. Also, uninstalling mods and loading a modded savegame has a high chance of making you crash or even corrupt the save. Gotta be patient. If you scrolled down a bit in the comment section of the mod you posted, you'll see that Hotfix 18 itself is apparently broken, and thus the wait on mod updates or the game is gonna take a bit more than usual.
> 
> For future cases, I recommend turning off auto-update for games you mod. It will almost always be the case that you cannot play until the mods get updated.

I know. I was replying to OP. I did scroll down and see that. Thanks tho!

**Comment by Norbyte** [comment]
This was a hotfix 18 specific issue that has since been rectified.
