### ISSUE TITLE
We appreciate you! Stop harassing the mod peeps!

### ISSUE THREAD

**Issue by jamimunchkin** [Norbyte/bg3se#294]
Guys, I get that you simple cannot go another breath without your BG3 mods, but cool it on harassing the person creating them. Show them some love for the work they do!

[you're awesome, buddy].

**Comment by Junkeira** [comment]
> Does the extender support patch 6 (pre-hotfix 18)? **YES** Now a pop-up window says it doesn't support the current version. Solution: Use the offline version of SE

It's broken nevertheless, throwback doesn't work anymore it seems.

**Comment by Zhaggygodx** [comment]
> Does the extender support patch 6 (pre-hotfix 18)? **YES** Now a pop-up window says it doesn't support the current version. Solution: Use the offline version of SE

I am completely new to this stuff!

How does one use an offline version of SE?

Thank you!

**Comment by JoshuaVSherman** [comment]
Just post your venmo and we will contribute!

**Comment by LeoHalivan** [comment]
Hey, I'm just sitting here updating mods and organizing the mess.

**Comment by Norbyte** [comment]
<3
