### ISSUE TITLE
No longer works on Patch 6 (no hotfix 18)

### ISSUE THREAD

**Issue by alterNERDtive** [Norbyte/bg3se#296]
Worked just fine™ yesterday, now it says:

![image](https://github.com/Norbyte/bg3se/assets/53827887/aec2e3c7-4443-4cb5-97fe-5612d5b0e3d9)

**Comment by alterNERDtive** [comment]
The even weirder thing: after disabling SE updates it claims there’s no cached version available for my current game version. Guess this unearthed another bug?

**Comment by Rogue-Demon-King** [comment]
It wasn't just updates being disabled, SE updater has remotely deleted local files, which I never expected to happen.

**Comment by alterNERDtive** [comment]
> It wasn't just updates being disabled, SE updater has remotely deleted local files, which I never expected to happen.

I can confirm that SE has **not** remotely deleted any files on my machine.

**Comment by Rogue-Demon-King** [comment]
did you run the game with the SE dll in the bin folder?

**Comment by alterNERDtive** [comment]
Now that I’ve been fiddling a bit more, it does delete v13 and v14 if you have updates enabled. That’s … sad.
