### ISSUE TITLE
BG3ModManager + SE Issue

### ISSUE THREAD

**Issue by Kittesh** [Norbyte/bg3se#298]
Hey everyone! So this is my problem, BG3ModManager keeps saying that i don't have SE installed (working fine until yesterday)

I tried to delete DWrite.dll and re-install it both from the Mod Manager "Tools" panel and from Github, but it keeps giving me this error.

I tried to launch the game and a popup opens when launching the game that says "Script extender is not compatible with this version" but it keeps going and I can normally play (without the SE mod ofc)

I did the exact same thing to my gf pc, same mods and same SE download and it just work on her pc.... Can't figure it out! 

Anyone having this issue can help? thanks!

**Comment by Honor4saken** [comment]
There's a few hundred comments below your post explaining the situation. Read some of them.

**Comment by Yrkhoon** [comment]
I have the same issue as him and after reading previous explaination it still doesn't make sense to me why the SE is working only for some people

**Comment by j3nesis87** [comment]
> I have the same issue as him and after reading previous explaination it still doesn't make sense to me why the SE is working only for some people

I _think_ that's because SE is not yet working with Hotfix #18, but it is working for people who have not yet downloaded #18. or who have reverted to a previous version of BG3.

**Comment by Norbyte** [comment]
This was a hotfix 18 specific issue that has since been rectified.
