### ISSUE TITLE
ignore

### ISSUE THREAD

**Issue by dragonqueen0124** [Norbyte/bg3se#299]

**Comment by Colne73** [comment]
Hotfix 18 killed BGSE... ffs they are dozen of posts about that under yours.

**Comment by JulieApraksina** [comment]
Agree, have same notification, but game still open and even mods works as i see
![image](https://github.com/Norbyte/bg3se/assets/70812027/870c63d1-0d8e-4e0f-b514-140554f50404)
But i have problem with localization... this problem discuss in steam

**Comment by HekateWitch** [comment]
OMG, please, can people stop posting ANOTHER after ANOTHER complaint about SE not working. Can't you see that there are dozen of posts? And answers are the same, just WAIT.

**Comment by viineapple** [comment]
answers to your questions and much more can be found [here](https://github.com/Norbyte/bg3se/issues/293). check the other threads next time and you'll find you're not the only one posting about it!

**Comment by SheeraDarkphoenix** [comment]
If you want to, with the BG3MM, create a separate mod list that does not use the SE. The warning will still show up, but the mods that don't use the SE will also show up, especially the ones for the Character Creation. The ones that include a Mod Fixer also work. It's a temporary, but it's worth a try if rollbacks don't work. I make separate lists just to see what works and what don't. It helps just in case of problems like this. It's just until the SE gets updated.

**Comment by dragonqueen0124** [comment]
> OMG, please, can people stop posting ANOTHER after ANOTHER complaint about SE not working. Can't you see that there are dozen of posts? And answers are the same, just WAIT.

excuse me, no need to be rude. I did not look because I didn't have the time. so my bad...

**Comment by belowzeros** [comment]
go download hotfix 19, things seem to be working again for me
