### ISSUE TITLE
Error Code When CallingOsiris

### ISSUE THREAD

**Issue by allcoast** [Norbyte/bg3se#30]
Using an addon, we are now receiving this error since your update on 8/31. It appears that this is not fixed with the latest update. Can you shed some light on whether this will be fixed or not? Please note, this was working fine before your 8/31 update.

Error while dispatching event SessionLoaded:    [string "AutoSaver/Server/Autosave.lua"]:2: Attempted to access Osiris t
stack traceback:
        [C++ Code]: in field 'TimerLaunch'
        AutoSaver/Server/Autosave.lua:2: in function <AutoSaver/Server/Autosave.lua:1>
        [C++ Code]: in function 'xpcall'
        builtin://Libs/Event.lua:129: in method 'Throw'
        builtin://Libs/Event.lua:184: in function <builtin://Libs/Event.lua:183>

**Comment by Norbyte** [comment]
See my comment to this issue: https://github.com/Norbyte/bg3se/issues/22

Calling Osiris during `SessionLoaded` is unsafe as a lot of the game systems are not initialized yet, and many calls will outright crash the game.

**Comment by Norbyte** [comment]
This was answered, closing
