### ISSUE TITLE
Update your game to "hotfix 19" and everything will return to normal.

### ISSUE THREAD

**Issue by Saiszon** [Norbyte/bg3se#302]
![Captura de Tela (177)](https://github.com/Norbyte/bg3se/assets/144752139/3fee4fd4-5076-45a2-81f6-a37156e20fd2)
just that.

**Comment by KiyoiAncunin** [comment]
> just that.

oh really ? thxx I was scared xD

**Comment by Larathiel** [comment]
Didn't have time enough to test all my mods, but WASD Movement (which requires Native Mod Loader), Improved World Tooltips, and Auto Send Food to Camp are all working. There was no longer an error about not finding a Script Extender for this game version, nor being unable to initialize WASD when I launched the game either.

**Comment by Saiszon** [comment]
> Didn't have time enough to test all my mods, but WASD Movement (which requires Native Mod Loader), Improved World Tooltips, and Auto Send Food to Camp are all working. There was no longer an error about not finding a Script Extender for this game version, nor being unable to initialize WASD when I launched the game either.

I did a quick test just now... using "Yet Another BG3 Native Mod Loader":

WASD Character Movement: Works
Native Camera Tweaks: Works
Baldur's Priority - CPU Performance FPS Optimizer: Works

Apparently everything really went back to normal as before.

**Comment by Jephry5** [comment]
Thanks for the update.  I nearly got a little misty when all my mods magically returned! haha
