### ISSUE TITLE
Somehow SE is broken AFTER hotfix #19?

### ISSUE THREAD

**Issue by Tiayin** [Norbyte/bg3se#304]
Seems like this is a me-only problem considering everyone is overjoyed that the SE is working again but since I updated to hotfix #19 an hour ago I get an error saying "No extender version found for game version v4.48.11.634". Before I updated, everything was working smoothly (I did "undo" hotfix #18 however)
Does anyone know why that might be the case? Thanks

![Error](https://github.com/Norbyte/bg3se/assets/160962071/e8da3b9d-daa6-414c-b15b-fd5e7d3d8bac)

**Comment by Tiayin** [comment]
What I tried so far:
- restarting my computer
- re-downloading the script extender

**Comment by AliakseiPitsukha** [comment]
> What I tried so far:
> 
> * restarting my computer
> * re-downloading the script extender

try deleting the folder in this path %USERPROFILE%\AppData\Local\BG3ScriptExtender\ScriptExtender
and then download SE via MM

**Comment by Tiayin** [comment]
> > What I tried so far:
> > 
> > * restarting my computer
> > * re-downloading the script extender
> 
> try deleting the folder in this path %USERPROFILE%\AppData\Local\BG3ScriptExtender\ScriptExtender and then download SE via MM

That seemed to do the trick. Thank you!
