### ISSUE TITLE
Achievements not working on steam deck

### ISSUE THREAD

**Issue by astaeria** [Norbyte/bg3se#305]
I read something about needing to enable them if it's installed using BG3MM but I can't get that to work on my Deck and can only install via Vortex. 

Not using any mods with any dependencies (only a custom face and some armour - installed this as the vortex guide I used advised to do it due to the number of mods that need it).

Any ideas how I can fix it? I would normally assume there's a file I can alter somewhere that will perform the same function as clicking enable in BG3MM but I can't find it.

Thanks!

**Comment by Jack7on7** [comment]
In Steam too! And this happened even after the last fix. Support recommended removing mods. Great, but then I won't be able to load the save at all!

**Comment by Jack7on7** [comment]
Although I just checked and after the last fix they fixed it) My achievements are working again)
