### ISSUE TITLE
Hotfix 19 Issue

### ISSUE THREAD

**Issue by Poindexter96** [Norbyte/bg3se#308]
![image_2024-02-22_235330823](https://github.com/Norbyte/bg3se/assets/160978998/9911e760-72a0-44bf-b164-24556aa57b24)

I rolled back bg3 to patch 6 after Hotfix 18 and everything was fine. Hotfix 19 has come out and seems to be working for people but I get this issue whenever I try to load a save after the update. I have tried verifying game files and reinstalling SE but it doesn't seem to work. 
I know there are a thousand threads related to this but I couldn't seem to find one with my particular issue. Is my best bet to just reinstall BG3?

**Comment by ladyesteria** [comment]
I'm getting the same issue.. though It only started popping when I removed the PlusUI mod. 
![image](https://github.com/Norbyte/bg3se/assets/114866327/ca9a09de-1ba4-44dd-a3df-fdbaa814f3a8)

**Comment by koticR** [comment]
Might be worth a try to rename or delete the 'BG3ScriptExtender' folder inside your Local AppData folder (eg. C:\Users\<username>\AppData\Local). This will regenerate the folder when the game is launched and download the latest version.

I don't know why it happens but the download/update seems to fail sometimes. I can confirm that the latest version works with the latest Hotfix (19).

**Comment by Poindexter96** [comment]
> Might be worth a try to rename or delete the 'BG3ScriptExtender' folder inside your Local AppData folder (eg. C:\Users<username>\AppData\Local). This will regenerate the folder when the game is launched and download the latest version.
> 
> I don't know why it happens but the download/update seems to fail sometimes. I can confirm that the latest version works with the latest Hotfix (19).

IT Worked! Thank you so much. I was starting to worry that something had corrupted within the game files.

**Comment by LunarisFawn** [comment]
deleting the folder didn't work for me but I also notice when I launch it isn't regenerating the folder, I've tried reinstalling but no dice. I'm still fiddling with it so if I figure it out I'll update here.

**Comment by Sebas0329** [comment]
Hotfix 19 worked for me but I have a new problem my screen goes black when I get off the Nautiloid the game doesn't crash it stays black any suggestions?

**Comment by SheeraDarkphoenix** [comment]
> Hotfix 19 worked for me but I have a new problem my screen goes black when I get off the Nautiloid the game doesn't crash it stays black when I try to go back to the main menu it stays at 0% when loading it back up any suggestions? Just ran it on another character and the game like froze but my character could still move around but no commands were working for looting, dialogue, or combat then my character froze and as I quit the game the game crashes and says the bg3.exe is not responding any ideas on what is going on?

I am having that same problem.

**Comment by belowzeros** [comment]
> deleting the folder didn't work for me but I also notice when I launch it isn't regenerating the folder, I've tried reinstalling but no dice. I'm still fiddling with it so if I figure it out I'll update here.

i've had this problem before too and nothing i could do would get it to recreate the folder.  i had to resort to updating SE manually because updating broke so it's probably related.  At some point down the road i redid my install completely to start a new game and that fresh install did everything properly.  there's got to be a setting somewhere i couldn't find

**Comment by LunarisFawn** [comment]
> > deleting the folder didn't work for me but I also notice when I launch it isn't regenerating the folder, I've tried reinstalling but no dice. I'm still fiddling with it so if I figure it out I'll update here.
> 
> i've had this problem before too and nothing i could do would get it to recreate the folder. i had to resort to updating SE manually because updating broke so it's probably related. At some point down the road i redid my install completely to start a new game and that fresh install did everything properly. there's got to be a setting somewhere i couldn't find
> 
> do you guys use native mod loader or it's related two mods? a verify for hotfix 19 will overwrite some of it's files.

What ended up working for me was creating the subfolder in local appdata myself and then loading up a new game all the way until you can move then reloading my main save, so if anyone has the same issue give that a shot.

and yeah I have native mod loader and the camera tweaks and wasd mods but the mod suggests after every update to reinstall and i assume that extends to verifying files so I did that :)

**Comment by Sebas0329** [comment]
@SheeraDarkphoenix U are having it too did u solve the issue or still figuring it out?

**Comment by Sebas0329** [comment]
Does anyone know if these mods may be crashing or making my bg3.exe to be unresponsive?
![Baldur's Gate 3 Mod Manager 1 0 10 0 2_19_2024 11_01_31 PM](https://github.com/Norbyte/bg3se/assets/98564580/3ba6ca83-c9a7-41c1-a1ec-ef1964f62ef3)
![Baldur's Gate 3 Mod Manager 1 0 10 0 2_19_2024 11_01_59 PM](https://github.com/Norbyte/bg3se/assets/98564580/6976eab9-9d86-4c3b-a313-83ae8eba78da)
![Baldur's Gate 3 Mod Manager 1 0 10 0 2_19_2024 11_02_08 PM](https://github.com/Norbyte/bg3se/assets/98564580/e588bd76-5775-4034-8d40-631b5955be85)

**Comment by SheeraDarkphoenix** [comment]
![Screenshot 2024-02-23 181959](https://github.com/Norbyte/bg3se/assets/138608790/20da2720-0f39-49f4-8948-a66699a8cdf7)
Here's what shows up on the SE. I saved before the Hotfix, but now the save doesn't show up, and neither do the mods. I tried to see if it was a mod problem, but it wasn't. The save file is still missing. I tried both Vulkan and DX11 versions, verified files, and nothing. I am going to wait till more is done on the SE before trying again.

**Comment by belowzeros** [comment]
> Does anyone know if these mods may be crashing or making my bg3.exe to be unresponsive?

how come all your mods have the same last updated date?  I was looking at them to see if any of them were outdated since that's how I usually start troubleshooting

**Comment by Sebas0329** [comment]
> > Does anyone know if these mods may be crashing or making my bg3.exe to be unresponsive?
> 
> how come all your mods have the same last updated date? I was looking at them to see if any of them were outdated since that's how I usually start troubleshooting

I have been installing and uninstalling I have been testing its showing when I installed them again

**Comment by Sebas0329** [comment]
@SheeraDarkphoenix The issue for me was the SoulBlade Mod everything else works so far

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
