### ISSUE TITLE
Red exclamation mark?

### ISSUE THREAD

**Issue by antarek** [Norbyte/bg3se#31]
Hi,

I haven't been able to find anything that explains what does the red exclamation mark means in your active mods list. So i would appreciate having a clarification on this. Thanks in advance.

![image](https://github.com/Norbyte/bg3se/assets/42368527/d8e2dee1-9a36-49b0-a83d-fdd0e24f0dd7)

**Comment by Norbyte** [comment]
Hi,

This is the Script Extender github, not the Mod Manager github, pls file the bug for the appropriate project, thanks :)
