### ISSUE TITLE
Script Extender Causing Crash

### ISSUE THREAD

**Issue by ImNarted** [Norbyte/bg3se#310]
I am technologically illeterate with this stuff, does anyone know what I need to do. Yesterday all my friends and I were playing together and now i cant join their lobby (we all have hotfix 19, same mods, same order, alll updated graphics drivers.)
![sa](https://github.com/Norbyte/bg3se/assets/160980568/0f2895d3-202c-44bb-b06d-e2400eb44f6f)

**Comment by callistowrites** [comment]
They were working on a fix for hotfix 18, and hotfix 19 has come out, so they'll need to update SE again. It'll be just a matter of waiting.

**Comment by Larathiel** [comment]
So my SE-enabled mods are working again, and my multiplayer players can all launch BG3 without getting an error about missing SE for the HF19 version.

HOWEVER, one of my friends is able to connect to my multiplayer session whereas another player crashes to desktop with the same exact error as ImNarted. I've ensured that their mod list matches mine exactly, but it doesn't seem to matter.

**Comment by LGCaerwyn** [comment]
you'd better roll back to patch 6, just patience for bg3se update.

**Comment by ImNarted** [comment]
The solution was posted on the Nexusmods page 

"Go to C:\Users\USER\AppData\Local\BG3ScriptExtender\ScriptExtender and delete everything that exists in there launch the game again and it should give you the current version"
