### ISSUE TITLE
Hi Norbyte! It's Gabe...

### ISSUE THREAD

**Issue by GabeCamomescro** [Norbyte/bg3se#313]
Sorry for having to add to your list, but I didn't see an existing thread. This is not a complaint, I can be patient, but it MAY help you with something or other. May not. Either way, feel free to slap me with a trout on Discord if need be.

So, this is the error I am getting (Hotfix 19). Some are saying SE works fine, and I figure this is just an issue until you update again. That said, I DID notice a discrepancy between the actual version number and the one in your popup, not sure if that is relevant to anything. Posting it here for you to be aware of.

Keep on keepin on, we <3 you man.

![SEError1](https://github.com/Norbyte/bg3se/assets/142802856/1181833b-9a3e-421e-ba7c-6df12a2818c7)

**Comment by Trygve-Husky** [comment]
meetoo.i can wait.

**Comment by Norbyte** [comment]
Ayo,
Devel branch was not yet updated, which is probably why you're getting the error still.
The game has two versions, the extender uses the .exe version:

![image](https://github.com/Norbyte/bg3se/assets/2243424/1a1e9f6b-21b8-4d7a-8176-775ede7da6e1)
