### ISSUE TITLE
Inventory Unusable

### ISSUE THREAD

**Issue by Multi-Faker** [Norbyte/bg3se#315]
Anyone else having an issue with their inventories? I have ImprovedUI and ImprovedUI Assets installed which I'm suspecting is the problem, but I'd rather not reinstall the entire game until I'm sure.

**Comment by GabeCamomescro** [comment]
Posting here will not help. If a mod uses SE, the SE-specific functions will be broken unless you have a version of SE that works. You can close your own comment 👍

**Comment by thefrogthatgotaway** [comment]
if you have Plus Ui installed, that's the mod that causes this

**Comment by Multi-Faker** [comment]
> if you have Plus Ui installed, that's the mod that causes this

I was thinking it might've been that but wasn't sure what UI it messed with, will give this a try

**Comment by belowzeros** [comment]
Plus UI does it because I believe it has outdated scaling in it.  If you have any of the scaling mods that use loose files they need to be updated or removed too, they definitely blank out your inventories.  You can find the loose files in /Public in the game directory
