### ISSUE TITLE
BUG:  Using AddBoosts to modify MinimumRollResult causes BG3 to crash when interacting with Armor

### ISSUE THREAD

**Issue by GamerJD75** [Norbyte/bg3se#316]
### I have attempted solutions to common problems

Yes

### I have checked that my game version is supported

Yes

### OS

Windows 11

### Platform

Steam

### Description

I was trying to use the AddBoosts function to tweak MinimumRollResult for a fun "Godlike" playthrough.

EX:  Osi.AddBoosts(GetHostCharacter(), "MinimumRollResult(RawAbility,20)", "", GetHostCharacter())

This works just fine & makes me always get Critical successes for those types of roles.  However, doing any AddBoost to the MinimumRollResult value causes the game to crash when mousing over the Scarlet Leather Armor from Dolor in Act 3, when the PC created avatar is the controlled toon.  Doing the same with a modified NPC follower (Jahira, etc) doesn't result in the same crash.  It only happens with my Durge toon.

Other AddBoost functions do not cause this crash.
EX: Osi.AddBoosts(GetHostCharacter(), "ActionResource(Movement,10000,0)", "", GetHostCharacter())

EDIT 1:  I should add that this problem did not happen before Patch 6 & the latest hotfixes.
EDIT 2:  It seems to be multiple types of armor, not just the Scarlet Leather Armor.

### Indications

Game crash only occurs if AddBoosts is used to tweak MinimumRollResult

### Steps to Reproduce

1) Select PC generated toon (such as Durge)
2) Use console to tweak MinimumRollResult
EX:  Osi.AddBoosts(GetHostCharacter(), "MinimumRollResult(RawAbility,20)", "", GetHostCharacter())
3) Mouse over Scarlet Leather Armor somewhere in game
4) Game should crash at this point

### Expected Behavior

Game shouldn't crash

### Actual Behavior

Game crashes

**Comment by GamerJD75** [comment]
> Hi,
> 
> Seems like a bug in the game's tooltip UI rendering code that crashes on this specific boost type. Sadly it is not an SE issue, but rather a base game issue :(
> 
> It is likely that you'd get the same crash if you added the boost to the item "normally", i.e. from stats rather than AddBoosts

I was figuring it was a game issue.  Sucks that it started happening after patch 6, since it was fine before.

Thanks for looking into this Norbyte.

**Comment by Kara-4search** [comment]
I just dealing the same problom with add status KAI, It got data "Boosts" "MinimumRollResult(Damage,20)" .inside . And It crash the game，anyone knows how to solve it？
