### ISSUE TITLE
Magic Mirror and All Appearance editing is blank?

### ISSUE THREAD

**Issue by ShadowSShifter** [Norbyte/bg3se#321]
### I have attempted solutions to common problems

Yes

### I have checked that my game version is supported

Yes

### OS

Windows 10

### Platform

Steam

### Description

As soon as I return to edit my character, whether it be a new save or preexisting load, it does not pop up with any options to change my character, only a view of them, as added in the screenshot and diagnostic files below.

### Indications

All mods were removed and the script extender was solely run with the BG3 mod manager. The issue persisted, in no way could I edit my tav.

### Diagnostic Files

[BG3 Diagnostic Data.txt](https://github.com/Norbyte/bg3se/files/14395872/BG3.Diagnostic.Data.txt)

This is what the appearance editor is stuck on.
![Screenshot (104)](https://github.com/Norbyte/bg3se/assets/64106541/bd0db149-b528-4e58-8efc-cb432dec275c)

### Steps to Reproduce

1. Enter a new save file and get sent to the character editor
2. Press "edit character appearance"

Alternatively:
1. Load save file
2. Go to camp
3. Touch Magic Mirror

### Expected Behavior

Magic Mirror and appearance should be able to be edited

### Actual Behavior

Both magic mirror and first character design lead to no customizable options.

**Comment by Norbyte** [comment]
Hi,

Do you have this issue without SE? It does not sound like something that SE touches.
Also be aware that some mods (eg. Improved UI and Improved UI Assets) are loaded even if they're not in your load order (them being in your Mods folder is enough).

i.e. clearing out the Mods folder might help to ensure no file-override mods are loaded.

**Comment by BurgersMcFly** [comment]
This is most probably a vanilla bug or an issue with Improved UI:

https://www.reddit.com/r/BaldursGate3/comments/16utxoi/edit_appearance_bugged/?sort=new

https://www.reddit.com/r/BaldursGate3/comments/16pcjyh/cant_access_the_magic_mirror/


Copy pasting possible fix from these posts:

Hey guys, found a method that has worked 100% for me.

If you have Improved UI installed amongst a plethora of mods - do this. Works for current save file that has already been using mods. You'll need to do this method for each save file if you have multiple characters - can do step 4 all at once on each character to save time.

For reference i have: Improved UI, Tav's Hairpack, Black Dye & Mod Fixer.

Open Mod Manager and DELETE "Improved UI". Make sure to tick "Permanent" & "Remove from Load Order". DO NOT DO ANYTHING ELSE. don't save the load order etc.

LAUNCH THE GAME

Load your save - you'll get a warning with a list of your mods notifying it will be disabled.

go into the mirror and "confirm" a change to exit. if you can't confirm just hit randomize and you should be able to confirm.

Save the game & then close to desktop

Add "Improved UI" back into your Mod Manager and now you save the load order again.

go back into that save and you should be able to access the mirror and utilise all the mods you have installed.

**Comment by ShadowSShifter** [comment]
I removed all my mods and only ran BG3 with the script extender, and the
issue persisted. Also, I ran a file verification, and the issue persists;
the only thing left it could be is the SE

**Comment by Norbyte** [comment]
DId you try removing SE and trying without it?

**Comment by Varriount** [comment]
Is your game installation in a "non-standard" location? That is, it's not in either "C:\Program Files (x86)\GOG Galaxy\Games\Baldurs Gate 3" or "C:\Program Files (x86)\Steam\steamapps\common\Baldurs Gate 3"?
