### ISSUE TITLE
How to edit SpellProperties?

### ISSUE THREAD

**Issue by aolose** [Norbyte/bg3se#322]
### I have attempted solutions to common problems

Yes

### I have checked that my game version is supported

Yes

### OS

Windows 11

### Platform

GOG

### Description

When I edit `SpellProperties` like this:
```
aaa = Ext.Stats.Get('Target_CreateUndead')
aaa.SpellProperties = aaa.SpellProperties
```

 the se throw an error:
```
bg3se::lua::stats::LuaStatGetAttribute(): Don't know how to fetch values of type 'StatsFunctors'
bg3se::stats::Object::SetFunctors(): Temporarily disabled until functors are mapped
```

It seems is not allowed to read and write SpellProperties

**Comment by Norbyte** [comment]
Hi,

SpellProperties (and other functors) cannot be read right now until the entire internal structure is mapped.
You can write them (and any other properties) as string using `aaa:SetRawAttribute("SpellProperties", "DoSomething(...)")`

**Comment by aolose** [comment]
> Hi,
> 
> SpellProperties (and other functors) cannot be read right now until the entire internal structure is mapped. You can write them (and any other properties) as string using `aaa:SetRawAttribute("SpellProperties", "DoSomething(...)")`

Thank your!
