### ISSUE TITLE
BG3SE Won't load in game although BG3MM says it's installed.

### ISSUE THREAD

**Issue by razzgonchik** [Norbyte/bg3se#323]
Hello, I've been using BG3 mods for some time now but never had this issue before. I reinstalled the game today and downloaded the Script Extender, Native Mod Loader and all the other mods I used to have before.
![Screenshot_2](https://github.com/Norbyte/bg3se/assets/98236713/6ea6075d-88bf-4484-b4c2-6187aff70f0e)
![Screenshot_4](https://github.com/Norbyte/bg3se/assets/98236713/dc31e76e-b45f-4577-8604-26865635d0ea)

 The issue I have noticed is that I installed the DWrite.dll file in my .bin folder but when I launch the game it doesn't say that the Script extender v.14 is loaded at the bottom left of the menu.
![Screenshot_1](https://github.com/Norbyte/bg3se/assets/98236713/db2798e6-6c55-4309-86ee-cc2acad47168)

I've also noticed that some mods that require BG3SE have not loaded or aren't working. Other mods that do not need BG3SE work normally.

**Comment by ximena-13** [comment]
It has been happening to me as well.

**Comment by SilverExil** [comment]
First, thanks for always working so hard on the SE. Now secondly, I also happen to be unable to open the console, it worked before, after fix 19 SE loads in again, but the console wont't come back.

**Comment by fantista** [comment]
Same unfortunately

**Comment by Varriount** [comment]
Could someone affected by this run the [diagnostic script](https://github.com/Norbyte/bg3se/blob/main/Generate%20BG3%20Diagnostic.bat) and attach the results?

**Comment by BoldolfLeif** [comment]
[BG3 Diagnostic Data.txt](https://github.com/Norbyte/bg3se/files/14436240/BG3.Diagnostic.Data.txt)

**Comment by razzgonchik** [comment]
I reinstalled the game again on a new patch and it has been fixed since.
