### ISSUE TITLE
warning in compilation

### ISSUE THREAD

**Issue by JDWOL** [Norbyte/bg3se#325]
### I have attempted solutions to common problems

Yes

### I have checked that my game version is supported

Yes

### OS

Windows 10

### Platform

Steam

### Description

![ОШИБКА](https://github.com/Norbyte/bg3se/assets/161544877/1263b1f4-4fd5-4ae6-a181-424d2ef0acd7)

### Indications

Every time after the start of the game, this error occurs. And if I disable the first two mods, then the character editor does not work and there is also an error, what should I do with it at all?

**Comment by Varriount** [comment]
Osiris errors mean that one or more mods have bugs in their Osiris code. Osiris is separate from Script Extender, and these errors would occur even if Script Extender wasn't installed (you just wouldn't see any error message). You should find out which mods cause the errors, and report the bug to the appropriate mod author.

**Comment by Norbyte** [comment]
This message is normal and is a side effect of mod fixer being loaded.
I dont see any actually errors in that log.
