### ISSUE TITLE
Ext.getCharacter Problem

### ISSUE THREAD

**Issue by Toxin4ick** [Norbyte/bg3se#33]
When calling `GetCharacter` method with correct GUID passing, `FIXME` message is called and nil type is returned.

Do I understand correctly that this is a temporary problem and it will go away in the next releases?
Is there any other way to get Object of type `esv::Character`?

**Comment by Norbyte** [comment]
Hi,

You're probably mixing up the D:OS 2 extender docs and the BG3 extender docs.
`Ext.GetCharacter()` currently does not exist in BG3, and I'm not sure if it will in the future because the engine is built very differently.

**Comment by cmooref17** [comment]
I have a related question, but are the docs for the BG3SE correct? It references "Ext.GetCharacter..." multiple times in there. Also, how would we know what methods are available for us to call?

**Comment by Norbyte** [comment]
The docs were since updated to reflect the changes to the character APIs, closing.
