### ISSUE TITLE
Startup errors

### ISSUE THREAD

**Issue by mysteryminds697** [Norbyte/bg3se#333]
### I have attempted solutions to common problems

Yes

### I have checked that my game version is supported

Yes

### OS

Windows 11

### Platform

GOG

### Description

I turned on the console and saw that I was getting errors when starting up and besides, all my mods weren’t working.
![Скриншот 02 03 24_19 44 12](https://github.com/Norbyte/bg3se/assets/161809676/2567922c-a9a7-42b2-8595-27681d50a658)

**Comment by Norbyte** [comment]
Update your game to the latest hotfix, SE doesn't work on HF 18.

**Comment by mysteryminds697** [comment]
Yes thank you. This solved my problem!
