### ISSUE TITLE
This isn't so much a bug as it is my inability and I would like to ask for help if possible 

### ISSUE THREAD

**Issue by NotASpicyGerman** [Norbyte/bg3se#334]
Just to prefis, this is my first time modded a game, so I am very out of my element. When I start up bg3 a error message pops up saying "no extender version found for game version v.4.36.48.72" I am very confused because I downloaded the latest version of the script extender(2023/10/28) to my knowledge help would be very much appreciated.

**Comment by SwissFred57** [comment]
Installation:

Download the extender [from here](https://github.com/Norbyte/bg3se/releases/download/updater-20231028/BG3SE-Updater-20231028.zip)
Extract DWrite.dll to the Baldurs Gate 3\bin directory (eg. C:\Program Files (x86)\Steam\steamapps\common\Baldurs Gate 3\bin)

**Comment by NotASpicyGerman** [comment]
I did as instructed but the error message still came up

**Comment by GamerJD75** [comment]
How is your game version so old?  The current version is 4.48.54.838.

**Comment by Norbyte** [comment]
The earliest supported game version is `v4.40.61.0` currently, anything before that will fail.
