### ISSUE TITLE
When i load the game it arrives to 100% and send me back to the menu. (I don't know if it is a bg3se problem or a mod problem.) Pleas could someone help me.

### ISSUE THREAD

**Issue by Saturnnd** [Norbyte/bg3se#335]
### I have attempted solutions to common problems

Yes

### I have checked that my game version is supported

Yes

### OS

Windows 10

### Platform

Steam

### Description

When i load the game it arrives to 100% and send me back to the menu. (I don't know if it is a bg3se problem or a mod problem.) Pleas could someone help me.

![image](https://github.com/Norbyte/bg3se/assets/132562329/e425efa4-a65e-4641-8a71-290bbdac308c)

Cause i don´t know what is the problem :(

**Comment by Varriount** [comment]
This means that your save game depends on a mod that *was* present, but is *currently* disabled. This is usually because your characters have a spell, action, status, or item that was defined by the disabled mod.

**Comment by Saturnnd** [comment]
> This means that your save game depends on a mod that _was_ present, but is _currently_ disabled. This is usually because your characters have a spell, action, status, or item that was defined by the disabled mod.

But i already check every mod and all of them are working.... this sucks... I want to play!!! Is posible to discover what is the problem?

**Comment by Varriount** [comment]
Hm, you might have luck enabling Script Extender's console and the other logging options. That *might* display an error from the game's internals that give more information.

(Note that this doesn't mean the problem is with Script Extender, it just means that SE is displaying an error generated by the game itself)
