### ISSUE TITLE
Requesting confirmation that this may be a bug in BG3 itself, not SE

### ISSUE THREAD

**Issue by FineRedMist** [Norbyte/bg3se#336]
Hi Norbyte,

I have enjoyed experimenting with SE and learning to create my mod. I encountered something odd that might be a bug with BG3, not SE, but you may have insight into other possibilities I ought to rule out before hitting up Larian with a more technical issue.

Essentially, right after levelling up right after a respec, attempting to add a boost for an action resource point 'kind of' fails. I can test the value for the action resource with GetActionResourceValuePersonal which returns 0 before applying the boost, and 0 after applying the boost. However, if I add the boost _again_, it will now read 2 for the action resource.

Currently, I'm testing the respec logic for my mod (working on a D&D Epic 6 implementation where the level is capped to 6, and you only get feats after) and encountered this anomaly. However, I am using StartRespec(GetHostCharacter()) in the console, so to be sure I have eliminated that as a possibility, I'll work my way to Withers and do an official respec to confirm it is entirely within the game.

I'd appreciate it if you have any other insights on what I should double-check against. I have attached my mod so far (first time in lua, much more comfortable in C++ or C#) for reference.

[DnD-Epic6.zip](https://github.com/Norbyte/bg3se/files/14475475/DnD-Epic6.zip)

**Comment by FineRedMist** [comment]
Confirmed it occurs on a Withers respec as well.

**Comment by Norbyte** [comment]
Are you adding the boost directly after respec or after a delay?
Some engine events are only resolved some ticks later, so the kludgy method of waiting a bit then adding the boost may work.

**Comment by FineRedMist** [comment]
I did add a 5-tick delay. I'll increase the count. The post-level-up animation covers enough time I could increase it pretty far.

**Comment by FineRedMist** [comment]
I have a workaround that monitors ensuring numbers end up being what they ought to be. It does seem to be more of a bg3 engine issue.
