### ISSUE TITLE
Can't go to camp or interact with NPCs, weird teleport behaviour

### ISSUE THREAD

**Issue by LeafWDM** [Norbyte/bg3se#337]
I'm not certain that this is a Script Extender bug, but it seems to be a common variable in other recent cases of this bug that I can find.
I'm doing a modded multiplayer playthrough and since we got to the underdark (I think sometime around when hotfix #20 came out) it seems like randomly upon opening the game npcs and events like sleeping aren't interactable, I can't go to or from camp, and when I warp it only warps my selected characters, with all other grouped characters walking back to where they started when I loaded the save. I did a complete reinstall of the game, my appdata, and every mod, and I loaded from a backup. I thought it was fixed until I logged on again later and it was screwed again. 

Mods used(not listed in same order as load order): 
ImprovedUI & ImprovedUI Assets
Community Library
Compatability Framework
Extra Attack Compatability
5E Spells
5E Spells  adjustments
5E Spells Larian Durations
Secret Scrolls for 5E Spells
Artificer
Artificer 5E Spells addon
Extra Dyes for the Fashionable Folk of Faerun
Additional Autosort Containers
Better Character Party Panel
Better Cursor Text Panel
Better Inventory UI Default for ImprovedUI
Better Containers
Better Context Menu
Better Dyeing
Better Hotbar 2
Better Loot + level restricted addon
Better Target Info
Combat Extender
Combat Extender AI
Faces Of Faerun
Mark As Read
Featsextra + orderfeats addon
Fizban's Treasury of Dragons + short rest addon
Immersive Equipment & Encounters
JWL Drop All The Loot
Camp Event Notifier
Mod Fixer
No Annoying VFX
No Intro
No Press Any Key Menu
Paladin - Oath of the gunslinger
Permanent Longstrider
Strong Female Heads
Tav's Hairpack + Tav's Hair Pack Icon Patch
The Gunslingers
Transmog Enhanced
Vemperen's Other Heads repaired
VFX Library By Shivero
Warcaster 5E
quite a few different dice mods
WASD movement and native camera tweaks native mods

If anyone has any advice for how to troubleshoot this or what might be the cause it would be appreciated. My apologies if I'm barking up the wrong tree. It doesn't seem to happen on every reload and I'm not sure what triggers it, but so far it has only happened to me after clearing out dread hollow, the duergar at the docks, and Dhourn + the spectator.

**Comment by Tarragon-L** [comment]
I had a problem like this (not being able to interact with sleeping, not being able to access camp, some other stuff), also near Dhourn, but only with hotfix 18. We have no mods in common from what I can tell (besides bg3se), but I also have a dye mod installed, and that's strangely enough the one that has caused the most problems with updates and hotfixes.

**Comment by Varriount** [comment]
See https://github.com/Norbyte/bg3se/blob/main/TROUBLESHOOTING.md

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
