### ISSUE TITLE
Not a bug, asking for advice on modifying a character HP after spawning

### ISSUE THREAD

**Issue by Eumeta** [Norbyte/bg3se#340]
Apologies if this is not the place to post this, I just can't find any site with script advice that's not Cheat Engine related.
So my issue is the visual inability of a character spawn by command to update its health bar to match its data:
+ I used` CreateAt(TemplateId, X, Y, Z, Temporary, PlaySpawn, SpawnFinishEvent)` to spawn a character
+ Then used my own defined functions to essentially copy every aspect of a vanilla character onto the spawn ( `Ext.Entity.Get(*spawn id*) = deepcopy( Ext.Entity.Get(*vanilla character id*)`, basically copies every field with its subfield recursively (e.g. Health, then Health.Hp, etc)
+ I noticed the Hp bar of the spawn always stay at Medium difficulty HP version upon creation. Changing Max Hp is possible (via AddBoosts, ApplyStatus with custom status, changing difficulty in Menu, etc.)  but their HP bar would not update to the new value, unless I add temporary HP.
+ THe Hp bar would update if the character takes damage, then it would be something like 155/130 (130, 169 are Max HP in Balanced and Tatician).
I tried to resolve this by adding lines after the deepcopy function to no effect:
```
Ext.Entity.Get(spawn id).Health.MaxHp = Ext.Entity.Get(target id).Health.MaxHp
Ext.Entity.Get(guid).Health.Hp = Ext.Entity.Get(guid).Health.MaxHp
```
Am I missing a function somewhere to update stats to display ?
Also, the deep_copy function is provided by Phind
<details>
`function deepcopy(orig)
	local type = type(orig)
	local copy
	if type == 'table' then
		copy = {}
		for k, v in next, orig, nil do
			copy[deepcopy(k)] = deepcopy(v)
		end
		setmetatable(copy,deepcopy(getmetatable(orig)))
	else
		copy = orig
	end
	return copy
end`
</details>
THank you for making BG3SE, and for supporting its creators

**Comment by Varriount** [comment]
One possibility is that there are fields that Script Extender does not yet provide access to that would need to be filed in for things to work correctly.

**Comment by Eumeta** [comment]
I noticed the same thing with passives added this way, or at least the passives within Ext.Entity.Get(character id).PassiveContainer.Passives, wrote a whole piece to detect and add passives the vanilla character has that the spawned character doesn't. While the script works, judging by the spawned character can do extra attacks, it doesn't display the passive Extra Attack on inspection

**Comment by Norbyte** [comment]
> `Ext.Entity.Get(*spawn id*) = deepcopy( Ext.Entity.Get(*vanilla character id*)`

This will absolutely not work.
Firstly, `Ext.Entity.Get` returns an entity handle, which is an lvalue; assigning to it will not change the properties of the, but rather just assign a different handle to the local.

Secondly, entity handles are not iterable, so you cannot deep copy them.

Thirdly, the deepcopy function you mentioned only performs a copy for `type == 'table'`; all values returned from Entity.Get (and its subobjects) are `lightcppobject`, not `table`.

Either the code you pasted is incomplete, or your the code doesn't really copy anything.

**Comment by Eumeta** [comment]
So that explains why i had to add smaller functions below, i really didn;t have a clue doing stuff in Lua
Thank you.
There's still the issue of the clones maxHP not updating visually in-game, do I close this issue as complete or not planned ?
