### ISSUE TITLE
Mods say I need SE v4 or v14 but even with BG3MM it won’t work

### ISSUE THREAD

**Issue by Greygameing** [Norbyte/bg3se#342]
### I have attempted solutions to common problems

Yes

### I have checked that my game version is supported

Yes

### OS

Linux

### Platform

Steam

### Description

I’ve downloaded 3 mods and everytime I move them to active mods list on BG3MM they say “Mod depends on SE v4 or v14” and then it tells me to use the “Tools”menu to get the latest update. So I open the game, close it, then do the SE update and the mods still say I’m missing the updated SE. Other mods also use the SE and they are completely fine! It’s just these 3 mods. I don’t know if I’m doing something wrong or what.
![image](https://github.com/Norbyte/bg3se/assets/162500437/d88de3be-072d-410b-a88a-fc6e6898af52)

**Comment by Norbyte** [comment]
What SE version do you see ingame?
If it's v14, then it's fine and BG3MM displays the wrong version for some reason.

**Comment by Greygameing** [comment]
It’s V14 yes! It might just be the mod itself than that’s not working! Because everything else that uses SE is fine, it’s just these 3 mods that are saying I need v14 even though I have V14. I downloaded the most recent .zip (the one released in October) and I used the BG3MM tools “download updated SE” tool as well. These 3 mods just refuse to recognize it!
