### ISSUE TITLE
Is this going to be updated soon? My game keeps crashing and everyone says this is the cause.

### ISSUE THREAD

**Issue by Miss-Foxy** [Norbyte/bg3se#343]
### I have attempted solutions to common problems

Yes

### I have checked that my game version is supported

Yes

### OS

Windows 10

### Platform

Steam

**Comment by Varriount** [comment]
What version of the game are you running? Have you looked to see if any of your mods have updates available?

**Comment by Miss-Foxy** [comment]
> What version of the game are you running? Have you looked to see if any of your mods have updates available?

I have the latest version of the game and all my mods have been updated too

**Comment by Varriount** [comment]
What errors are you getting?

**Comment by Jephry5** [comment]
If it's anything like mine, there are no apparent errors; the game just disappears...

**Comment by Miss-Foxy** [comment]
Yeah no errors the game just goes poof, it happens mostly when I do a dice roll of some kind.

**Comment by Varriount** [comment]
Could you please run the diagnostic tool at https://github.com/Norbyte/bg3se/blob/main/Generate%20BG3%20Diagnostic.bat and upload the results?

**Comment by Jephry5** [comment]
Pardon my complete and total ignorance, but...do I just hit the "create" link at the top and then paste all 182 lines? I am SO not a coder, clearly.

**Comment by Miss-Foxy** [comment]
Sorry its alot, Also unsure if this is what you asked for.

Start Section: Basic System Information
=======================================
    
    Name                           Value                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
    ----                           -----                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
    PSVersion                      5.1.19041.4046                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
    PSEdition                      Desktop                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
    PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
    BuildVersion                   10.0.19041.4046                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
    CLRVersion                     4.0.30319.42000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
    WSManStackVersion              3.0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
    PSRemotingProtocolVersion      2.3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
    SerializationVersion           1.1.0.1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
    
    
=====================================
End Section: Basic System Information


Start Section: File Hashes
==========================
    
    Algorithm Hash                             Path                                                                                                                             
    --------- ----                             ----                                                                                                                             
    MD5       AEEA74992B56E8470040134FA3A3740F C:\Users\annal\AppData\Local\Larian Studios\Baldur's Gate 3\analytics.lsx                                                        
    MD5       CCE4B453AEB513FC5E469F9C300F36F6 C:\Users\annal\AppData\Local\Larian Studios\Baldur's Gate 3\global\modsettings.lsx                                               
    MD5       56EEA506B0E28BD1E9FCD17E8515C363 C:\Users\annal\AppData\Local\Larian Studios\Baldur's Gate 3\graphicSettings.lsx                                                  
    MD5       CA18018E427BD538BDA3BD2F6E746D2D C:\Users\annal\AppData\Local\Larian Studios\Baldur's Gate 3\PlayerProfiles\playerprofiles8.lsf                                   
    MD5       70C2A7C79B289BC22091C5A36C7995C8 C:\Users\annal\AppData\Local\Larian Studios\Baldur's Gate 3\PlayerProfiles\Public\config.lsf                                     
    MD5       CF63B2BBF1EC0FDAA567D78549DF93A7 C:\Users\annal\AppData\Local\Larian Studios\Baldur's Gate 3\PlayerProfiles\Public\modsettings.lsx                                
    MD5       88E4D2037502CEA4885A513AE1363E89 C:\Users\annal\AppData\Local\Larian Studios\Baldur's Gate 3\PlayerProfiles\Public\modsettings.lsx.backup                         
    MD5       7602E5A87EBA100EBEBE15105B492E38 C:\Users\annal\AppData\Local\Larian Studios\Baldur's Gate 3\PlayerProfiles\Public\profile8.lsf                                   
    MD5       5658D1622D8A0B6286C04F323C292CAD C:\Users\annal\AppData\Local\Larian Studios\Baldur's Gate 3\PlayerProfiles\Public\UILayout.lsx                                   
    MD5       FF26B59EC9BA2E20D1A6A5D75527F48C C:\Users\annal\AppData\Local\Larian Studios\Baldur's Gate 3\Script Extender\AutoSendFoodToCamp\auto_send_food_to_camp_config.json
    MD5       81CFDED3DB46D1F95D9667F30ACCE114 C:\Users\annal\AppData\Local\Larian Studios\Baldur's Gate 3\Temp\Story\story_merge_f.dat                                         
    MD5       615282E9743D95D9DFAB232713530829 C:\Users\annal\AppData\Local\Larian Studios\Baldur's Gate 3\Temp\Story\story_merge_g.dat                                         
    
    
========================
End Section: File Hashes


Start Section: Mod Settings Files
=================================
    Start Section: C:\Users\annal\AppData\Local\Larian Studios\Baldur's Gate 3\global\modsettings.lsx
    =================================================================================================
        <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
        <save>
          <version major="4" minor="0" revision="10" build="100"/>
          <region id="ModuleSettings">
            <node id="root">
              <children>
                <node id="ModOrder">
                  <children/>
                </node>
                <node id="Mods">
                  <children>
                    <node id="ModuleShortDesc">
                      <attribute id="Folder" type="LSString" value="GustavDev"/>
                      <attribute id="MD5" type="LSString" value=""/>
                      <attribute id="Name" type="LSString" value="GustavDev"/>
                      <attribute id="UUID" type="FixedString" value="28ac9ce2-2aba-8cda-b3b5-6e922f71b6b8"/>
                      <attribute id="Version64" type="int64" value="36028797018963968"/>
                    </node>
                  </children>
                </node>
              </children>
            </node>
          </region>
        </save>
    ===============================================================================================
    End Section: C:\Users\annal\AppData\Local\Larian Studios\Baldur's Gate 3\global\modsettings.lsx
    
    
    Start Section: C:\Users\annal\AppData\Local\Larian Studios\Baldur's Gate 3\PlayerProfiles\Public\modsettings.lsx
    ================================================================================================================
        <?xml version="1.0" encoding="UTF-8"?>
        <save>
          <version major="4" minor="0" revision="9" build="331" />
          <region id="ModuleSettings">
            <node id="root">
              <children>
                <node id="ModOrder">
                  <children>
                    <node id="Module">
                      <attribute id="UUID" value="28ac9ce2-2aba-8cda-b3b5-6e922f71b6b8" type="FixedString" />
                    </node>
                    <node id="Module">
                      <attribute id="UUID" value="16ba58e4-3ee5-4cfd-81e8-5a9f6d3f6b46" type="FixedString" />
                    </node>
                    <node id="Module">
                      <attribute id="UUID" value="b77b6210-ac50-4cb1-a3d5-5702fb9c744c" type="FixedString" />
                    </node>
                    <node id="Module">
                      <attribute id="UUID" value="da0b99ca-4406-49c1-bef9-3a08621280a2" type="FixedString" />
                    </node>
                    <node id="Module">
                      <attribute id="UUID" value="243f3a0f-38fa-4c5f-8faa-0f0b867c7622" type="FixedString" />
                    </node>
                    <node id="Module">
                      <attribute id="UUID" value="0b051a3d-3f8e-4f12-a6df-a2feca729327" type="FixedString" />
                    </node>
                    <node id="Module">
                      <attribute id="UUID" value="4885204f-7e46-4a42-b38c-ad24719609ba" type="FixedString" />
                    </node>
                    <node id="Module">
                      <attribute id="UUID" value="8c611d4b-75d9-40eb-ad61-15f898396e12" type="FixedString" />
                    </node>
                    <node id="Module">
                      <attribute id="UUID" value="e64e2e53-92c3-444e-a374-0d6638ed4e99" type="FixedString" />
                    </node>
                    <node id="Module">
                      <attribute id="UUID" value="0d77ef52-11ac-4031-8027-1a625834a16c" type="FixedString" />
                    </node>
                    <node id="Module">
                      <attribute id="UUID" value="6e4cd23c-74a9-46f2-82a2-8b8fc5928a75" type="FixedString" />
                    </node>
                    <node id="Module">
                      <attribute id="UUID" value="dcac7271-ee4e-48b4-97fb-f0ebe7bfe10c" type="FixedString" />
                    </node>
                    <node id="Module">
                      <attribute id="UUID" value="e2f68acb-3c55-4794-844e-da25420b0792" type="FixedString" />
                    </node>
                    <node id="Module">
                      <attribute id="UUID" value="46b38455-1799-45fb-9d5c-dfb2667874e7" type="FixedString" />
                    </node>
                    <node id="Module">
                      <attribute id="UUID" value="e241dad4-8d72-4f4b-9b88-f2a077c6f60e" type="FixedString" />
                    </node>
                    <node id="Module">
                      <attribute id="UUID" value="c53a183b-10c0-4bcf-ab4d-296f60ca972d" type="FixedString" />
                    </node>
                    <node id="Module">
                      <attribute id="UUID" value="8f0d9a35-6d42-4ffd-a277-574f5744480a" type="FixedString" />
                    </node>
                    <node id="Module">
                      <attribute id="UUID" value="a4e10524-5e8c-4b28-a34f-574f5744480a" type="FixedString" />
                    </node>
                    <node id="Module">
                      <attribute id="UUID" value="96ac86cd-f099-4b56-ab8b-1cea055284dc" type="FixedString" />
                    </node>
                    <node id="Module">
                      <attribute id="UUID" value="202f39a3-5d2e-4a8c-aecf-064994deeeec" type="FixedString" />
                    </node>
                    <node id="Module">
                      <attribute id="UUID" value="62333410-e6f3-4c38-aa6a-cb03e126421e" type="FixedString" />
                    </node>
                    <node id="Module">
                      <attribute id="UUID" value="73928ffc-07c0-46ac-8cf4-86a693b0cd92" type="FixedString" />
                    </node>
                    <node id="Module">
                      <attribute id="UUID" value="73696165-6c32-4e31-914f-fc839aaef51d" type="FixedString" />
                    </node>
                    <node id="Module">
                      <attribute id="UUID" value="d5b26f57-5a47-41bb-b752-ce5a4b652510" type="FixedString" />
                    </node>
                    <node id="Module">
                      <attribute id="UUID" value="9833ce61-c66d-427c-b267-54e726dc9c87" type="FixedString" />
                    </node>
                    <node id="Module">
                      <attribute id="UUID" value="9b26c0d1-6248-4732-b75d-bd44f1252c08" type="FixedString" />
                    </node>
                    <node id="Module">
                      <attribute id="UUID" value="e769d750-ac96-48da-8b13-dbda20042df0" type="FixedString" />
                    </node>
                    <node id="Module">
                      <attribute id="UUID" value="505c630c-79fa-49b6-9f21-29a5f2322c2d" type="FixedString" />
                    </node>
                    <node id="Module">
                      <attribute id="UUID" value="e7e2d510-8b0b-435a-b68c-ed5b823df7e9" type="FixedString" />
                    </node>
                    <node id="Module">
                      <attribute id="UUID" value="1c132ec4-4cd2-4c40-aeb9-ff6ee0467da8" type="FixedString" />
                    </node>
                    <node id="Module">
                      <attribute id="UUID" value="28636e14-f396-45a3-81f8-a06e196319bc" type="FixedString" />
                    </node>
                    <node id="Module">
                      <attribute id="UUID" value="4806bd2a-929b-406e-b1d4-2e0e9cc23bb2" type="FixedString" />
                    </node>
                    <node id="Module">
                      <attribute id="UUID" value="2831844d-e3bf-4d46-9920-71a2af947aac" type="FixedString" />
                    </node>
                    <node id="Module">
                      <attribute id="UUID" value="35e8df86-5c3d-4d5d-81bf-7ff3a1717a9a" type="FixedString" />
                    </node>
                    <node id="Module">
                      <attribute id="UUID" value="86cd6b91-0358-4b93-97c4-ffa54f4a8cc2" type="FixedString" />
                    </node>
                    <node id="Module">
                      <attribute id="UUID" value="fb5f528d-4d48-4bf2-a668-2274d3cfba96" type="FixedString" />
                    </node>
                    <node id="Module">
                      <attribute id="UUID" value="ee4989eb-aab8-968f-8674-812ea2f4bfd7" type="FixedString" />
                    </node>
                    <node id="Module">
                      <attribute id="UUID" value="65f3ff35-a64b-47c6-8a79-5271bdfa35f5" type="FixedString" />
                    </node>
                  </children>
                </node>
                <node id="Mods">
                  <children>
                    <node id="ModuleShortDesc">
                      <attribute id="Folder" value="GustavDev" type="LSString" />
                      <attribute id="MD5" value="a1287bc433a174b162a98cf0667efc30" type="LSString" />
                      <attribute id="Name" value="GustavDev" type="LSString" />
                      <attribute id="UUID" value="28ac9ce2-2aba-8cda-b3b5-6e922f71b6b8" type="FixedString" />
                      <attribute id="Version64" value="144960472004315828" type="int64" />
                    </node>
                    <node id="ModuleShortDesc">
                      <attribute id="Folder" value="HalfDragon" type="LSString" />
                      <attribute id="MD5" value="" type="LSString" />
                      <attribute id="Name" value="HalfDragon" type="LSString" />
                      <attribute id="UUID" value="16ba58e4-3ee5-4cfd-81e8-5a9f6d3f6b46" type="FixedString" />
                      <attribute id="Version64" value="36732484460740608" type="int64" />
                    </node>
                    <node id="ModuleShortDesc">
                      <attribute id="Folder" value="Honour" type="LSString" />
                      <attribute id="MD5" value="58cd99c19c1cc1338fc578ab42769194" type="LSString" />
                      <attribute id="Name" value="Honour" type="LSString" />
                      <attribute id="UUID" value="b77b6210-ac50-4cb1-a3d5-5702fb9c744c" type="FixedString" />
                      <attribute id="Version64" value="36028797023832756" type="int64" />
                    </node>
                    <node id="ModuleShortDesc">
                      <attribute id="Folder" value="DFHairPack" type="LSString" />
                      <attribute id="MD5" value="" type="LSString" />
                      <attribute id="Name" value="Tav's Hairpack" type="LSString" />
                      <attribute id="UUID" value="da0b99ca-4406-49c1-bef9-3a08621280a2" type="FixedString" />
                      <attribute id="Version64" value="37295434414161920" type="int64" />
                    </node>
                    <node id="ModuleShortDesc">
                      <attribute id="Folder" value="HarpyHairs" type="LSString" />
                      <attribute id="MD5" value="" type="LSString" />
                      <attribute id="Name" value="HarpyHairs" type="LSString" />
                      <attribute id="UUID" value="243f3a0f-38fa-4c5f-8faa-0f0b867c7622" type="FixedString" />
                      <attribute id="Version64" value="36028797018963968" type="int64" />
                    </node>
                    <node id="ModuleShortDesc">
                      <attribute id="Folder" value="HW_HeadEdits" type="LSString" />
                      <attribute id="MD5" value="" type="LSString" />
                      <attribute id="Name" value="HW_HeadEdits" type="LSString" />
                      <attribute id="UUID" value="0b051a3d-3f8e-4f12-a6df-a2feca729327" type="FixedString" />
                      <attribute id="Version64" value="36028797018963968" type="int64" />
                    </node>
                    <node id="ModuleShortDesc">
                      <attribute id="Folder" value="New Race Heads" type="LSString" />
                      <attribute id="MD5" value="" type="LSString" />
                      <attribute id="Name" value="New Race Heads" type="LSString" />
                      <attribute id="UUID" value="4885204f-7e46-4a42-b38c-ad24719609ba" type="FixedString" />
                      <attribute id="Version64" value="36028797018963968" type="int64" />
                    </node>
                    <node id="ModuleShortDesc">
                      <attribute id="Folder" value="Aloija_New_Heads" type="LSString" />
                      <attribute id="MD5" value="" type="LSString" />
                      <attribute id="Name" value="Faces of FaerÃ»n" type="LSString" />
                      <attribute id="UUID" value="8c611d4b-75d9-40eb-ad61-15f898396e12" type="FixedString" />
                      <attribute id="Version64" value="36591746972385280" type="int64" />
                    </node>
                    <node id="ModuleShortDesc">
                      <attribute id="Folder" value="DaughterofLolthChosen" type="LSString" />
                      <attribute id="MD5" value="" type="LSString" />
                      <attribute id="Name" value="Daughter of Lolth - Chosen Path" type="LSString" />
                      <attribute id="UUID" value="e64e2e53-92c3-444e-a374-0d6638ed4e99" type="FixedString" />
                      <attribute id="Version64" value="72198340116217856" type="int64" />
                    </node>
                    <node id="ModuleShortDesc">
                      <attribute id="Folder" value="FireproofKarlach" type="LSString" />
                      <attribute id="MD5" value="" type="LSString" />
                      <attribute id="Name" value="FireproofKarlach" type="LSString" />
                      <attribute id="UUID" value="0d77ef52-11ac-4031-8027-1a625834a16c" type="FixedString" />
                      <attribute id="Version64" value="36028797018963968" type="int64" />
                    </node>
                    <node id="ModuleShortDesc">
                      <attribute id="Folder" value="Squire" type="LSString" />
                      <attribute id="MD5" value="" type="LSString" />
                      <attribute id="Name" value="Squire" type="LSString" />
                      <attribute id="UUID" value="6e4cd23c-74a9-46f2-82a2-8b8fc5928a75" type="FixedString" />
                      <attribute id="Version64" value="36169534507319296" type="int64" />
                    </node>
                    <node id="ModuleShortDesc">
                      <attribute id="Folder" value="Olympian Weapons" type="LSString" />
                      <attribute id="MD5" value="" type="LSString" />
                      <attribute id="Name" value="Olympian Weapons" type="LSString" />
                      <attribute id="UUID" value="dcac7271-ee4e-48b4-97fb-f0ebe7bfe10c" type="FixedString" />
                      <attribute id="Version64" value="144115196665790673" type="int64" />
                    </node>
                    <node id="ModuleShortDesc">
                      <attribute id="Folder" value="ArmourOfVengeance" type="LSString" />
                      <attribute id="MD5" value="" type="LSString" />
                      <attribute id="Name" value="ArmourOfVengeance" type="LSString" />
                      <attribute id="UUID" value="e2f68acb-3c55-4794-844e-da25420b0792" type="FixedString" />
                      <attribute id="Version64" value="700682432" type="int64" />
                    </node>
                    <node id="ModuleShortDesc">
                      <attribute id="Folder" value="SwordOfGods" type="LSString" />
                      <attribute id="MD5" value="" type="LSString" />
                      <attribute id="Name" value="Sword Of Gods" type="LSString" />
                      <attribute id="UUID" value="46b38455-1799-45fb-9d5c-dfb2667874e7" type="FixedString" />
                      <attribute id="Version64" value="36028797018963968" type="int64" />
                    </node>
                    <node id="ModuleShortDesc">
                      <attribute id="Folder" value="SwordOfGods_onehanded" type="LSString" />
                      <attribute id="MD5" value="" type="LSString" />
                      <attribute id="Name" value="Sword Of Gods - One Handed" type="LSString" />
                      <attribute id="UUID" value="e241dad4-8d72-4f4b-9b88-f2a077c6f60e" type="FixedString" />
                      <attribute id="Version64" value="36028797018963968" type="int64" />
                    </node>
                    <node id="ModuleShortDesc">
                      <attribute id="Folder" value="RingOfGods" type="LSString" />
                      <attribute id="MD5" value="" type="LSString" />
                      <attribute id="Name" value="Ring Of Gods" type="LSString" />
                      <attribute id="UUID" value="c53a183b-10c0-4bcf-ab4d-296f60ca972d" type="FixedString" />
                      <attribute id="Version64" value="36028797018963968" type="int64" />
                    </node>
                    <node id="ModuleShortDesc">
                      <attribute id="Folder" value="WoWDemonHunterClass" type="LSString" />
                      <attribute id="MD5" value="" type="LSString" />
                      <attribute id="Name" value="WoWDemonHunterClass" type="LSString" />
                      <attribute id="UUID" value="8f0d9a35-6d42-4ffd-a277-574f5744480a" type="FixedString" />
                      <attribute id="Version64" value="36028797018963968" type="int64" />
                    </node>
                    <node id="ModuleShortDesc">
                      <attribute id="Folder" value="WoWDemonHunterClassExtraFeat" type="LSString" />
                      <attribute id="MD5" value="" type="LSString" />
                      <attribute id="Name" value="WoWDemonHunterClassExtraFeat" type="LSString" />
                      <attribute id="UUID" value="a4e10524-5e8c-4b28-a34f-574f5744480a" type="FixedString" />
                      <attribute id="Version64" value="36028797018963968" type="int64" />
                    </node>
                    <node id="ModuleShortDesc">
                      <attribute id="Folder" value="Bloodvine" type="LSString" />
                      <attribute id="MD5" value="" type="LSString" />
                      <attribute id="Name" value="Bloodvine" type="LSString" />
                      <attribute id="UUID" value="96ac86cd-f099-4b56-ab8b-1cea055284dc" type="FixedString" />
                      <attribute id="Version64" value="72057594037927936" type="int64" />
                    </node>
                    <node id="ModuleShortDesc">
                      <attribute id="Folder" value="RenArmor3" type="LSString" />
                      <attribute id="MD5" value="" type="LSString" />
                      <attribute id="Name" value="RenArmor3" type="LSString" />
                      <attribute id="UUID" value="202f39a3-5d2e-4a8c-aecf-064994deeeec" type="FixedString" />
                      <attribute id="Version64" value="36028797018963968" type="int64" />
                    </node>
                    <node id="ModuleShortDesc">
                      <attribute id="Folder" value="DrowClericArmor" type="LSString" />
                      <attribute id="MD5" value="" type="LSString" />
                      <attribute id="Name" value="DrowClericArmor" type="LSString" />
                      <attribute id="UUID" value="62333410-e6f3-4c38-aa6a-cb03e126421e" type="FixedString" />
                      <attribute id="Version64" value="144115188075855912" type="int64" />
                    </node>
                    <node id="ModuleShortDesc">
                      <attribute id="Folder" value="SCO" type="LSString" />
                      <attribute id="MD5" value="" type="LSString" />
                      <attribute id="Name" value="Scantily Camp Outfit" type="LSString" />
                      <attribute id="UUID" value="73928ffc-07c0-46ac-8cf4-86a693b0cd92" type="FixedString" />
                      <attribute id="Version64" value="72057654167470080" type="int64" />
                    </node>
                    <node id="ModuleShortDesc">
                      <attribute id="Folder" value="DeathsongSet" type="LSString" />
                      <attribute id="MD5" value="" type="LSString" />
                      <attribute id="Name" value="DeathsongSet" type="LSString" />
                      <attribute id="UUID" value="73696165-6c32-4e31-914f-fc839aaef51d" type="FixedString" />
                      <attribute id="Version64" value="36169540949770240" type="int64" />
                    </node>
                    <node id="ModuleShortDesc">
                      <attribute id="Folder" value="DivineCurse" type="LSString" />
                      <attribute id="MD5" value="" type="LSString" />
                      <attribute id="Name" value="DivineCurse" type="LSString" />
                      <attribute id="UUID" value="d5b26f57-5a47-41bb-b752-ce5a4b652510" type="FixedString" />
                      <attribute id="Version64" value="36873224096579584" type="int64" />
                    </node>
                    <node id="ModuleShortDesc">
                      <attribute id="Folder" value="MutilatedCarapace" type="LSString" />
                      <attribute id="MD5" value="" type="LSString" />
                      <attribute id="Name" value="Basket of Bhaalist Loot" type="LSString" />
                      <attribute id="UUID" value="9833ce61-c66d-427c-b267-54e726dc9c87" type="FixedString" />
                      <attribute id="Version64" value="36028797018963968" type="int64" />
                    </node>
                    <node id="ModuleShortDesc">
                      <attribute id="Folder" value="MyshkaComesToCamp" type="LSString" />
                      <attribute id="MD5" value="" type="LSString" />
                      <attribute id="Name" value="MyshkaComesToCamp" type="LSString" />
                      <attribute id="UUID" value="9b26c0d1-6248-4732-b75d-bd44f1252c08" type="FixedString" />
                      <attribute id="Version64" value="36028797018963968" type="int64" />
                    </node>
                    <node id="ModuleShortDesc">
                      <attribute id="Folder" value="RaiseInspirationRewards" type="LSString" />
                      <attribute id="MD5" value="" type="LSString" />
                      <attribute id="Name" value="Raise Inspiration Rewards - 4" type="LSString" />
                      <attribute id="UUID" value="e769d750-ac96-48da-8b13-dbda20042df0" type="FixedString" />
                      <attribute id="Version64" value="36028797018963968" type="int64" />
                    </node>
                    <node id="ModuleShortDesc">
                      <attribute id="Folder" value="TutorialChestSummoning" type="LSString" />
                      <attribute id="MD5" value="" type="LSString" />
                      <attribute id="Name" value="TutorialChestSummoning" type="LSString" />
                      <attribute id="UUID" value="505c630c-79fa-49b6-9f21-29a5f2322c2d" type="FixedString" />
                      <attribute id="Version64" value="73183493944770560" type="int64" />
                    </node>
                    <node id="ModuleShortDesc">
                      <attribute id="Folder" value="AethersAutoSaver" type="LSString" />
                      <attribute id="MD5" value="" type="LSString" />
                      <attribute id="Name" value="Aether's Auto Saver - 5 Minutes" type="LSString" />
                      <attribute id="UUID" value="e7e2d510-8b0b-435a-b68c-ed5b823df7e9" type="FixedString" />
                      <attribute id="Version64" value="36028797018963968" type="int64" />
                    </node>
                    <node id="ModuleShortDesc">
                      <attribute id="Folder" value="AutoSendFoodToCamp" type="LSString" />
                      <attribute id="MD5" value="" type="LSString" />
                      <attribute id="Name" value="Auto Send Food To Camp" type="LSString" />
                      <attribute id="UUID" value="1c132ec4-4cd2-4c40-aeb9-ff6ee0467da8" type="FixedString" />
                      <attribute id="Version64" value="36451015926480896" type="int64" />
                    </node>
                    <node id="ModuleShortDesc">
                      <attribute id="Folder" value="Feat Every 1 Level" type="LSString" />
                      <attribute id="MD5" value="" type="LSString" />
                      <attribute id="Name" value="Feat Every 1 Level" type="LSString" />
                      <attribute id="UUID" value="28636e14-f396-45a3-81f8-a06e196319bc" type="FixedString" />
                      <attribute id="Version64" value="2" type="int64" />
                    </node>
                    <node id="ModuleShortDesc">
                      <attribute id="Folder" value="Trips_Aasimar" type="LSString" />
                      <attribute id="MD5" value="" type="LSString" />
                      <attribute id="Name" value="Whispers of the Divine: Aasimar (Race)" type="LSString" />
                      <attribute id="UUID" value="4806bd2a-929b-406e-b1d4-2e0e9cc23bb2" type="FixedString" />
                      <attribute id="Version64" value="180143985094819840" type="int64" />
                    </node>
                    <node id="ModuleShortDesc">
                      <attribute id="Folder" value="Swarmkeeper" type="LSString" />
                      <attribute id="MD5" value="" type="LSString" />
                      <attribute id="Name" value="Swarmkeeper" type="LSString" />
                      <attribute id="UUID" value="2831844d-e3bf-4d46-9920-71a2af947aac" type="FixedString" />
                      <attribute id="Version64" value="36028839968636928" type="int64" />
                    </node>
                    <node id="ModuleShortDesc">
                      <attribute id="Folder" value="UndeadSoul" type="LSString" />
                      <attribute id="MD5" value="" type="LSString" />
                      <attribute id="Name" value="UndeadSoul" type="LSString" />
                      <attribute id="UUID" value="35e8df86-5c3d-4d5d-81bf-7ff3a1717a9a" type="FixedString" />
                      <attribute id="Version64" value="36169536654802944" type="int64" />
                    </node>
                    <node id="ModuleShortDesc">
                      <attribute id="Folder" value="LearnKnock" type="LSString" />
                      <attribute id="MD5" value="" type="LSString" />
                      <attribute id="Name" value="Learn Knock" type="LSString" />
                      <attribute id="UUID" value="86cd6b91-0358-4b93-97c4-ffa54f4a8cc2" type="FixedString" />
                      <attribute id="Version64" value="36028797018963968" type="int64" />
                    </node>
                    <node id="ModuleShortDesc">
                      <attribute id="Folder" value="5eSpells" type="LSString" />
                      <attribute id="MD5" value="" type="LSString" />
                      <attribute id="Name" value="5eSpells" type="LSString" />
                      <attribute id="UUID" value="fb5f528d-4d48-4bf2-a668-2274d3cfba96" type="FixedString" />
                      <attribute id="Version64" value="36169547392221188" type="int64" />
                    </node>
                    <node id="ModuleShortDesc">
                      <attribute id="Folder" value="DiceSet_06" type="LSString" />
                      <attribute id="MD5" value="" type="LSString" />
                      <attribute id="Name" value="DiceSet_06" type="LSString" />
                      <attribute id="UUID" value="ee4989eb-aab8-968f-8674-812ea2f4bfd7" type="FixedString" />
                      <attribute id="Version64" value="36028797018963968" type="int64" />
                    </node>
                    <node id="ModuleShortDesc">
                      <attribute id="Folder" value="RemodelledFrameBody" type="LSString" />
                      <attribute id="MD5" value="" type="LSString" />
                      <attribute id="Name" value="RemodelledFrameBody" type="LSString" />
                      <attribute id="UUID" value="65f3ff35-a64b-47c6-8a79-5271bdfa35f5" type="FixedString" />
                      <attribute id="Version64" value="37013959437451264" type="int64" />
                    </node>
                  </children>
                </node>
              </children>
            </node>
          </region>
        </save>
    ==============================================================================================================
    End Section: C:\Users\annal\AppData\Local\Larian Studios\Baldur's Gate 3\PlayerProfiles\Public\modsettings.lsx
    
    
===============================
End Section: Mod Settings Files

**Comment by rascalito777** [comment]
i am having the same problem is there a solution?

**Comment by Miss-Foxy** [comment]
> i am having the same problem is there a solution?

for me it was UIAssets but that has been recently updated so my game works now
