### ISSUE TITLE
When lauching through BG3MM, Script Extender closes after very quick search (78ms vice 800ish ms) with no errors. Bg3 does not launch at all.

### ISSUE THREAD

**Issue by BigChed** [Norbyte/bg3se#344]
![SE](https://github.com/Norbyte/bg3se/assets/162640401/125470e5-c144-4478-bd79-52d554a1c330)
### I have attempted solutions to common problems

Yes

### I have checked that my game version is supported

Yes

### OS

Windows 11

### Platform

Steam

### Description

When launching game through BG3MM, SE opens and does a VERY quick search (78ms vice 800ms) and then just closes with no errors stated and BG3 doesn't even launch.  Just curious if this is common with hotfixes (21 seems to be the issue) or if its not even SE related. Screenshot is where SE stops at before closing with no more info being loaded.

Thank you for all your work and time you put into this!

**Comment by Varriount** [comment]
Could you download and run [the diagnostic tool](https://github.com/Norbyte/bg3se/blob/main/Generate%20BG3%20Diagnostic.bat) and attach the report here?

**Comment by BigChed** [comment]
> Could you download and run [the diagnostic tool](https://github.com/Norbyte/bg3se/blob/main/Generate%20BG3%20Diagnostic.bat) and attach the report here?

Github n00b here... Do I just paste the script into powershell or is there a way to download it as an exe? sorry! lol

**Comment by BigChed** [comment]
So.. i am an idiot and launching the game frrm the launcher booted up SE and all is good. Guess i was loading it from the "go" and launch game option. So that doesn't work for some reason but its working regardless.

**Comment by Varriount** [comment]
@BigChed If your issue is resolved, you can close it.
