### ISSUE TITLE
Starting the game with SE spikes CPU and causes severe stutter

### ISSUE THREAD

**Issue by puyebu** [Norbyte/bg3se#345]
### I have attempted solutions to common problems

Yes

### I have checked that my game version is supported

Yes

### OS

Linux

### Platform

Steam

### Description

Starting the game with SE enabled using wine-ge-26 causes severe stutter even in main menu, spikes CPU activity as well.
SE console window does not show anything in red or weird.
I am launching the game .exe directly using Lutris, the issue persists whether I have esync enabled or not.
The lags/stutter seem to start when loading progress of main menu reaches 100% but before displaying it.
Seems to only happen on DX11 but DX11 is the most performant option for me.

### Indications

Stutter in main menu, CPU activity spikes.

### Diagnostic Files

For some reason I cannot access diagnostics bat, so I am posting SE logs:

The one with mods:
```
Extender runtime log written to 'C:/users/admin/AppData/Local/Larian Studios/Baldur's Gate 3//Script Extender Logs\Extender Runtime 2024-03-08 00-09-37.log'
Configuration for 'Combat Extender':
	MinVersion 13; Feature flags: Lua 
Configuration for 'Combat Extender AI':
	MinVersion 13; Feature flags: Lua 
Configuration for 'AbsoluteWrath':
	MinVersion 5; Feature flags: Lua 
Configuration for 'SpeakWithAnimalsForAll':
	MinVersion 2; Feature flags: Lua 
4 mod configuration(s) loaded.
Merged configuration:
	MinVersion 13; Feature flags: Lua 
Initializing client with target context Load
Modded achievements enabled.
bg3se::ExtensionStateBase::LuaResetInternal(): LUA VM reset.
Configuration for 'Combat Extender':
	MinVersion 13; Feature flags: Lua 
Configuration for 'Combat Extender AI':
	MinVersion 13; Feature flags: Lua 
Configuration for 'AbsoluteWrath':
	MinVersion 5; Feature flags: Lua 
Configuration for 'SpeakWithAnimalsForAll':
	MinVersion 2; Feature flags: Lua 
4 mod configuration(s) loaded.
Merged configuration:
	MinVersion 13; Feature flags: Lua 
Initializing client with target context Game
bg3se::ExtensionStateBase::LuaResetInternal(): LUA VM reset.
Loading bootstrap script: Mods/CombatExtender/ScriptExtender/Lua/BootstrapClient.lua
ecl::ScriptExtender::OnGameStateChanged(): Loaded module
```

The one without:
```
Extender runtime log written to 'C:/users/namusan/AppData/Local/Larian Studios/Baldur's Gate 3//Script Extender Logs\Extender Runtime 2024-03-08 00-14-42.log'
Initializing client with target context Load
Modded achievements enabled.
bg3se::ExtensionStateBase::LuaResetInternal(): LUA VM reset.
Initializing client with target context Game
bg3se::ExtensionStateBase::LuaResetInternal(): LUA VM reset.
ecl::ScriptExtender::OnGameStateChanged(): Loaded module
```

### Steps to Reproduce

1. Add WINEDLLOVERRIDES="DWrite.dll=n,b" to launch command prefix
2. Add PROTON_NO_ESYNC=1 to arguments or disable esync in settings
3. Run game

### Expected Behavior

No stutter

### Actual Behavior

Stutter

**Comment by Norbyte** [comment]
For reference, the `PROTON_NO_ESYNC=1` setting has since been removed from the recommended flags list, since it causes stutter and is no longer required to run SE properly, it was a holdover from the DOS2 days when esync was bugged.
