### ISSUE TITLE
Console errors and BG3SE not loading

### ISSUE THREAD

**Issue by martinkah0** [Norbyte/bg3se#349]
### I have attempted solutions to common problems

Yes

### I have checked that my game version is supported

Yes

### OS

Windows 10

### Platform

Steam

### Description

When I launch the game this appears in the console:

BG3Ext v14 built on Feb 23 2024 11:34:06
Game version v4.47.88.723 OK
ScriptExtender::Initialize: Starting
No match found for mapping 'ls__GlobalAllocator' [CRITICAL]
No match found for mapping 'ls__GlobalAllocator__Alloc' [CRITICAL]
No match found for mapping 'ls::FixedString::IncRef' [CRITICAL]
No match found for mapping 'ls::FixedString::CreateFromString' [CRITICAL]
No match found for mapping 'ls::FileReader::ctor' [CRITICAL]
No match found for mapping 'ls::FileReader::dtor' [CRITICAL]
No match found for mapping 'ls__PathRoots' [CRITICAL]
No match found for mapping 'EoCServer2/EoCClient2' [CRITICAL]
No match found for mapping 'ecl::EoCClient::HandleError' [CRITICAL]
No match found for mapping 'ecl__gGameStateEventManager' [CRITICAL]
No match found for mapping 'esv__gGameStateEventManager' [CRITICAL]
No match found for mapping 'esv::GameStateMachine::Update' [CRITICAL]
No match found for mapping 'App::LoadGraphicSettings' [CRITICAL]
No match found for mapping 'esv::GameStateThreaded::GameStateWorker::DoWork' [CRITICAL]
No match found for mapping 'ecl::GameStateThreaded::GameStateWorker::DoWork' [CRITICAL]
Target mapping action did not succeed for mapping 'ecl::GameStateThreaded::GameStateWorker::DoWork - Outer' [CRITICAL]
No match found for mapping 'esv::SavegamePostVisit_DisableStoryMerge'
No match found for mapping 'esv::StatsSystem::ThrowDamageEvent'
No match found for mapping 'eoc::DealDamageFunctor::ApplyDamage'
No match found for mapping 'App::Instance'
No match found for mapping 'ecs::StaticContextRegistrant'
No match found for mapping 'ecs::StaticIDRegistrant'
No match found for mapping 'ecs::StaticStringConstructor'
No match found for mapping 'ecs::ComponentReplicationIDRef'
No match found for mapping 'KillLauncher'
No match found for mapping 'ls::VirtualTextureResource::Load'
No match found for mapping 'esv::LevelManager'
No match found for mapping 'eoc::InterruptPrototype::Init'
ScriptExtender::Initialize: Could not load libraries; skipping scripting extension initialization.
Library startup took 6064 ms

I've tried to open game only with bg3se without any other mod, but it does not change a thing. So far other mods work, but bg3se just doesn't. I tried to even update latest vc redist, still the same issue. Otherwise the game works fine.

**Comment by Norbyte** [comment]
Update to a later hotfix. 
SE does not support hotfix18, i.e. the v4.47.88.723 version.
