### ISSUE TITLE
Failures and Updates

### ISSUE THREAD

**Issue by horsefog** [Norbyte/bg3se#35]
I've been unable to go back into one of my campaigns for a few days, and have tried a whole bunch of stuff to no avail.

I did see the following in the crashdump for the script extender and don't know how to fix them

  Key  : Failure.Bucket
    Value: NULL_POINTER_READ_c0000005_bg3_dx11.exe!Unknown

    Key  : Failure.Hash
    Value: {0915c37a-44ac-c947-c10d-ae131d365117}

Also, in the Mod Manager it keeps telling me that I'm using v1 instead of v3, despite having downloaded/installed v3 repeatedly. I don't know if that's part of the problem either. Any insight would be great.

Other things I've tried include:

- Deleting the modsetting.lsx file and reloading all mods again
- Validating files on Steam
- Redownloading/installing all mods
- Reinstalling the Script Extender
- Enabling/Disabling Export Default Values in the script extender
- Change the game path from bg3.exe to bg3_dx11.exe
- Moving ImprovedUI from Overrides to the load order it was in before the update
- Updating all mods that have updates available
- Removing mods that I added before encountering this problem
- Enabling/Disabling DirectX 11 Mode, launching through Steam, and Auto Add Missing Dependencies When Exporting

**Comment by horsefog** [comment]
[I think I found which mod is causing the problem](https://www.nexusmods.com/baldursgate3/mods/327?tab=posts&BH=0), as multiple people are reporting this issue in its comments. I don't know if the script extender is equipped to fix this issue or if it'll have to come from the author of the mod itself but here's hoping it gets solved soon. I miss my main campaign lol.

**Comment by Jessicanity** [comment]
I'm having the same issue. I tried rolling back to an earlier version of the specific mod (the one I was using before I had this issue) but still having the problem. It's only for a few specific campaigns (three, with no other links between them as far as I can tell) but it's the exact same errors you're getting, and trying to load any saves from those three campaigns causes a crash to desktop. No other campaigns have the issue.

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
