### ISSUE TITLE
Hotfix 21 - is it working?

### ISSUE THREAD

**Issue by trelik** [Norbyte/bg3se#352]
### I have attempted solutions to common problems

Yes

### I have checked that my game version is supported

Yes

### OS

Windows 11

### Platform

Steam

### Description

Hey,

It is not report bug, but there is nowhere place saying if actual version of SE works with latest updates or not, so not only me but probably a lot of people still keeping old version of the game (mine is still on hf 19).

Could you please keep us updated on the FAQ page or any other place? I see daily updates in the script from your side, but it does not tell me if its ready or not and if I can DL it without corrupting my current mod setup.

Would appriciate your effort and help here.

**Comment by 1llus1veman** [comment]
Hotfix 25 - is it working?

**Comment by Norbyte** [comment]
It is.
