### ISSUE TITLE
Got a Issue, Script Extender Update Error

### ISSUE THREAD

**Issue by Leghtin** [Norbyte/bg3se#355]
### I have attempted solutions to common problems

Yes

### I have checked that my game version is supported

Yes

### OS

Windows 10

### Platform

Steam

### Description

My friend got this issue, Script Extender update failure; make sure your connected to the internet and try again. Unable to download manifest (28) SSL connect error. 
And he also got same issue on Divinity Original Sin 2. We use same Step to update this Extender, but we have different Windows OS. His Windows OS is Windows 10 22H2, my OS is Windows 11 23H2. Could this problem be caused by his incorrect Windows system? Is there any other troubleshooting information that we need to provide that might help?
![QQ图片20240316155820](https://github.com/Norbyte/bg3se/assets/17336721/2bbe374d-8312-4cd2-a38e-c7e1d88f039e)

### Indications

Game Cannot Launch, and the Mod manager Works well. When we use Mod Manager Tools to update  Script Extender, it can be success. And these mods show normal installation in the mod manager.
![QQ图片20240316155825](https://github.com/Norbyte/bg3se/assets/17336721/6dcc2349-6368-4ada-99e0-168e299f6e91)

**Comment by Leghtin** [comment]
![QQ图片20240316161233](https://github.com/Norbyte/bg3se/assets/17336721/8f00acda-e8e2-49ba-ba70-65163fffc9c6)
![QQ图片20240316161238](https://github.com/Norbyte/bg3se/assets/17336721/d24245e6-f583-440d-9dec-7b7d3eaae2f3)
The Picture Of Console

**Comment by Norbyte** [comment]
Cloudflare was IP blocked in China for whatever reason, I think it's unblocked now.
