### ISSUE TITLE
Help building on W11 VS2022 + VCPKG

### ISSUE THREAD

**Issue by calebtt** [Norbyte/bg3se#357]
### I have attempted solutions to common problems

Yes

### I have checked that my game version is supported

Yes

### OS

Windows 11

### Platform

Steam

### Description

Attempting to build this project with Visual Studio 2022 and use Vcpkg for the "externals", having a rough time.

1. What json library (aside from the Lua included one) is used in Manifest.h? The include is "json/json.h" which makes it appear to be a project file instead of a 3rd party lib include.
2. What do I install to have the Debug Interface Access include files? i.e., "dia2.h" in SymbolTableGenerator.cpp
3. LuaLib and TinyCrypt for example actually have none of the source files in them that the VS solution file expects them to have, where to obtain those?

### Expected Behavior

build -or- build after installing packages with lib package manager

### Actual Behavior

not build

**Comment by calebtt** [comment]
Also, do you have C++20 features available like std::format ?
What about C++23 features like std::print?

**Comment by mycroftjr** [comment]
Re OP's question #1, I think it's jsoncpp?

Either way, at least half of the "local dependencies" the project expects probably could have worked via NuGet, so that'd be a nice change.
The NoesisGUI library in particular is quite hard to obtain, and in fact I wasn't able to get the exact version the project wants at all.

**Comment by Norbyte** [comment]
> Re OP's question #1, I think it's jsoncpp?
> 
> Either way, at least half of the "local dependencies" the project expects probably could have worked via NuGet, so that'd be a nice change. The NoesisGUI library in particular is quite hard to obtain, and in fact I wasn't able to get the exact version the project wants at all.

There is a readme now in the Externals/ folder that links to the latest version of all external files required.
(Including jsoncpp, etc.)

**Comment by Norbyte** [comment]
As for the original questions:

>> What json library (aside from the Lua included one) is used in Manifest.h? The include is "json/json.h" which makes it appear to be a project file instead of a 3rd party lib include.
It's jsoncpp, built through cmake3.

>> What do I install to have the Debug Interface Access include files? i.e., "dia2.h" in SymbolTableGenerator.cpp
I have these files available without installing any other dependency apart from the standard Windows SDK that Visual Studio installs.

>> LuaLib and TinyCrypt for example actually have none of the source files in them that the VS solution file expects them to have, where to obtain those?
See https://github.com/Norbyte/bg3se/blob/main/External/README.md
