### ISSUE TITLE
BaseUtilities.h Any reason for empty ctor definition?

### ISSUE THREAD

**Issue by calebtt** [Norbyte/bg3se#358]
https://github.com/Norbyte/bg3se/blob/957d58b74e1c0d287677e0b36f7d0595b726446f/CoreLib/Base/BaseUtilities.h#L28

to my knowledge the empty ctor definition makes a class not trivially constructible when otherwise it would be if you had used = default, is there any purpose for the empty braces after this constructor?

Also the HashMix function has some non-const temporaries that could be constexpr.

**Comment by Norbyte** [comment]
I've updated the constructor, good catch.

The temporaries cannot actually be made constexpr, since that would require the inputs to be constexpr, which cannot be guaranteed.
