### ISSUE TITLE
Ext.Stats. There is no support for modifiers which contains space character

### ISSUE THREAD

**Issue by dr-corvax** [Norbyte/bg3se#362]
### I have attempted solutions to common problems

Yes

### I have checked that my game version is supported

Yes

### OS

Windows 10

### Platform

Steam

### Description

Works as expected
S >> _D(Ext.Stats.Get("WPN_Dagger")."Weapon Properties")
"569b0f3d-abcd-4b01-aaf0-979091288163"

And for modifier with space "_modifier "Weapon Properties","WeaponFlags"_"
S >> _D(Ext.Stats.Get("WPN_Dagger").'Weapon Properties')
[string "_D(Ext.Stats.Get("WPN_Dagger").'Weapon Proper..."]:1: <name> expected near ''Weapon Properties''

S >> _D(Ext.Stats.Get("WPN_Dagger").WeaponProperties)
bg3se::lua::stats::LuaStatGetAttribute(): Stat object 'WPN_Dagger' has no attribute named 'WeaponProperties'
null

**Comment by Norbyte** [comment]
It's `Ext.Stats.Get("WPN_Dagger")["Weapon Properties"]`

**Comment by dr-corvax** [comment]
Thanks
