### ISSUE TITLE
StatsLoaded event wasn't triggered

### ISSUE THREAD

**Issue by dr-corvax** [Norbyte/bg3se#364]
It seems something wrong with StatsLoaded event trigger
SessionLoaded - works fine: "SessionLoaded" appears in console
StatsLoaded - nothing happens

local function OnStatsLoaded()
    print("Stats loaded...")
end

local function OnSessionLoaded()
    print("Session loaded...")
end

Ext.Events.StatsLoaded:Subscribe(OnStatsLoaded) 
Ext.Events.SessionLoaded:Subscribe(OnSessionLoaded)

**Comment by Norbyte** [comment]
In BG3 stats are always loaded by the client (however strange this may seems), so it will only fire on the client.
