### ISSUE TITLE
DWrite.dll does not exist in most recent release.

### ISSUE THREAD

**Issue by alexnjfoust** [Norbyte/bg3se#367]
I am not knowledgeable regarding coding. However, the most recent update, 4 hours prior to this submission, asset contains BG3Updater.dll and not DWrite.dll.
Again, I am not knowledgeable, the description lists extracting the DWrite.dll, so I'd figure I would report the possible issue!

**Comment by Norbyte** [comment]
The release zip was uploaded incorrectly, should be fixed now
