### ISSUE TITLE
latest release does not contain DWrite.dll

### ISSUE THREAD

**Issue by rockiesmagicnumber** [Norbyte/bg3se#368]
### I have attempted solutions to common problems

Yes

### I have checked that my game version is supported

Yes

### OS

Linux

### Platform

GOG

### Description

BG3ModManager is choking on upgrading ScriptExtender, citing problems with DWrite.dll and "check the log" - the Log just says exactly the same thing.

Manual installation reveals that the currently released Zip only has a file called `BG3Updater.dll` and no sign of `DWrite.dll`.

This is causing LariLauncher to complain about corrupted files, and verifying the files via GOG Galaxy does not resolve the issue.

**Comment by Norbyte** [comment]
The release zip was uploaded incorrectly, should be fixed now

**Comment by rockiesmagicnumber** [comment]
Confirmed via BG3MM, thank you for the quick turnaround
