### ISSUE TITLE
MessageBox Listener not working

### ISSUE THREAD

**Issue by SwissFred57** [Norbyte/bg3se#369]
### I have attempted solutions to common problems

Yes

### I have checked that my game version is supported

Yes

### OS

Windows 11

### Platform

Steam

### Description

i use messageboxes
Osi.OpenMessageBoxYesNo(character, message) but the Listener is not working
Osi.MessageBoxYesNoClosed(character, message, result)

since Patch 6 but i am not sure when it was not working

is there a fix ?

**Comment by TripsLetash** [comment]
Known issue caused by Larian. No fix.

**Comment by Hippo0o** [comment]
using Osi.ReadyCheckSpecific is the solution.

**Comment by Norbyte** [comment]
see https://github.com/Norbyte/bg3se/issues/274

Not an SE issue.
