### ISSUE TITLE
Script Extender update failed; Unable to download manifest: (6) Couldn't resolve host name

### ISSUE THREAD

**Issue by ytokisd** [Norbyte/bg3se#373]
### I have attempted solutions to common problems

Yes

### I have checked that my game version is supported

Yes

### OS

Windows 10

### Platform

Steam

### Description

![image](https://github.com/Norbyte/bg3se/assets/27485274/91c726a9-b000-46c6-81ca-a2fcc3b2c226)

I have downloaded DWrite.dll, launched the game, then got an error described in bug name and displaying on a screenshot

### Indications

It's script extender download issue

### Steps to Reproduce

1. Download DWrite.dll and place it into Bg3 bin folder
2. Launch game with launcher, or mod manager
3. Get an error

### Expected Behavior

Update SE and all is good

### Actual Behavior

error occurs and I'm so sad

**Comment by Murlocoff** [comment]
almost the same trouble here. I decided to download the newest version and it started to give me this issue:
![image](https://github.com/Norbyte/bg3se/assets/128255089/403117eb-7e0e-4ceb-8c2e-35154ece1e5c) I've yet managed to figure 1 thing out: if you replace the Dwrite.dill from 2023/10/28, it starts working, showing the same error you have tho. Hope someone will aid us soon :D

**Comment by ytokisd** [comment]
Just want to point out that trying to start game with VPN enabled or switched to mobile network does not help with this issue

**Comment by ytokisd** [comment]
Looks like I managed to resolve this issue.
1) Deleted script extender folder from username/appData/Local
2) Deleted DWrite.dll and two more config files related to Script Extender from BG 3 bin folder
![image](https://github.com/Norbyte/bg3se/assets/27485274/861d286c-5e70-40f2-8ba6-cc196e49fb0b)

**Comment by ytokisd** [comment]
Works for me now

**Comment by WazBurrows** [comment]
@ytokisd what were the two additional config files that you deleted in step 2?

**Comment by ytokisd** [comment]
@WazBurrows I had ScriptExtenderUpdaterConfig.json and ScripExtender something else in my bin folder. Deleted both
