### ISSUE TITLE
Script Extender Updater Error

### ISSUE THREAD

**Issue by SwankJohnson** [Norbyte/bg3se#378]
### I have attempted solutions to common problems

Yes

### I have checked that my game version is supported

Yes

### OS

Windows 11

### Platform

Steam

### Description

"Script Extender update failed. 
Script extender digest not found in manifest:
18b315b48303a7b4356e064270cde7669a25e0422d98ba2348d2a12f0ee"

### Indications

![Script Extender Crash](https://github.com/Norbyte/bg3se/assets/166261055/e7494788-f1a5-4bb5-b4b7-69c7225d2d9f)
"

**Comment by wldng90** [comment]
Just tagging onto this one in case someone responds, as I'm also having a similar issue, except its error code 126 regarding the "SE library" 

I've deleted all mods and redownloaded SE. I've also uninstalled/reinstalled the game and continued running it without mods but the error still occurs. Currently doing a "clean" uninstall/install and hoping that fixes things.

**Comment by deathtome1998** [comment]
norbyte answered this for me and someone else in #370 if it's what I think it is.

**Comment by SwankJohnson** [comment]
That answered my question. All I had to do was delete ScriptExtenderUpdaterConfig.json
