### ISSUE TITLE
Remove `PROTON_NO_ESYNC` from Wine/Proton instructions?

### ISSUE THREAD

**Issue by alterNERDtive** [Norbyte/bg3se#382]
Any system with software post 2018 should support esync; at least if it’s running `systemd`, which basically all mainstream distributions do. I haven’t extensively tested with BG3, but generally speaking disabling esync might impact performance and should only be done if there are specific issues with it. I have always run BG3 with esync.

Is there a specific reason the Proton instructions include `PROTON_NO_ESYNC=1`? Otherwise I would drop it.

**Comment by Norbyte** [comment]
as far as I remember esync broke some of the DLL overrides and needed to be disabled for them to work.
It may work correctly now, I havent tested without it for a long time.

**Comment by Norbyte** [comment]
Removed.
