### ISSUE TITLE
Game Doesnt Start on Steam Deck

### ISSUE THREAD

**Issue by AkumaNoYami** [Norbyte/bg3se#39]
i use the GOG Version of the Game 
![Screenshot 2023-05-04 181040](https://github.com/Norbyte/bg3se/assets/87585966/64eb0086-2804-4608-bb03-b5c6d8ae26ac)
put the Command line in the Launch option 
but now the game doesnt start

**Comment by AkumaNoYami** [comment]
never mind 
i think i found it 
i put the commandline in Heroic > Baldurs Gate 3 (Settings)

**Comment by Norbyte** [comment]
oops :)
