### ISSUE TITLE
ImGui windows do not render using DX11 (on AMD cards)

### ISSUE THREAD

**Issue by klementineQt** [Norbyte/bg3se#390]
### I have attempted solutions to common problems

Yes

### I have checked that my game version is supported

Yes

### OS

Windows 11

### Platform

Steam

### Description

To go ahead and specify since I've seen a few others mention the same issue while having AMD cards in Nexus replies as well as on Discord, I have an AMD Radeon RX 5700 XT running the latest drivers. I'm unable to simply switch to using Vulkan as it's always had issues and as of recent patches, is now at the point where it can't load the game without crashing.

I've removed Reshade, as well as disabled AMD and Steam's overlays, and it's all been to no avail.

### Indications

I'm specifically trying to test my mod, https://www.nexusmods.com/baldursgate3/mods/7258
It works fine for most people, but a few others have let me know that they have the same issue and have all reported using AMD cards as well.

### Diagnostic Files

[BG3 Diagnostic Data.txt](https://github.com/Norbyte/bg3se/files/15277111/BG3.Diagnostic.Data.txt)

### Steps to Reproduce

1. Use AMD card
2. Use mod creating an imgui window
3. Launch BG3 using DirectX 11
4. See that there's no window

### Expected Behavior

I would like at least one lil imgui window to render 🥺

### Actual Behavior

No window :(

**Comment by Norbyte** [comment]
The latest release build has a fix that should hopefully fix this issue.

**Comment by klementineQt** [comment]
Can confirm it did fix the issue for me! This is a huge win
