### ISSUE TITLE
Application Window Information constantly in the console

### ISSUE THREAD

**Issue by AndrewM521** [Norbyte/bg3se#398]
### I have attempted solutions to common problems

Yes

### I have checked that my game version is supported

Yes

### OS

Windows 11

### Platform

Steam

### Description

No matter what I do, this information is being spammed in the console. It looks to be the console application information but I am not entirely sure

"HookApp::deferHook,
HookApp::hookWindow,
UiApp::trySetupGraphicsWindow, gwindow == window 0000000000120AFC
HookApp::hookD3d9, 0"

It does not stop until the console is closed, even when trying the commands; server, client, and exit

### Indications

No mods are being loaded so its not a mod issue, and this same thing happens on a fresh install of the script extender

### Diagnostic Files

![SEConsole](https://github.com/Norbyte/bg3se/assets/55631446/68a6dad2-ef11-4a2f-ae44-32303da4b442)

[BG3 Diagnostic Data.txt](https://github.com/Norbyte/bg3se/files/15478335/BG3.Diagnostic.Data.txt)

### Steps to Reproduce

1. Open game with "DWrite.dll" and "ScripExtenderSettings.json" files in the games bin folder
2. When the console is open it starts to show this information automatically

### Expected Behavior

I don't know, but the information probably should not be always in the console

### Actual Behavior

This information being constantly outputted in the console no matter what I do.

"HookApp::deferHook,
HookApp::hookWindow,
UiApp::trySetupGraphicsWindow, gwindow == window 0000000000120AFC
HookApp::hookD3d9, 0"

**Comment by AndrewM521** [comment]
Turns out this issue was due to my clipping software. Once I closed the software, the constant spammed messages stopped.

**Comment by dorlevy1** [comment]
dude, you are my hero.
