### ISSUE TITLE
Confused about forever sleep bug

### ISSUE THREAD

**Issue by MilkyWhiteLove** [Norbyte/bg3se#399]
### I have attempted solutions to common problems

Yes

### I have checked that my game version is supported

Yes

### OS

Windows 10

### Platform

Steam

### Description

I have a save file (Honor Mode) where I'm at the first romance scene with Lae'zel, but after it finishes, I'm stuck sleeping and all my companions ungroup and disappear from camp except for Lae'zel, she just ungroups. My actions are all greyed out as well. Another thing: It remains nighttime. This means the game doesn't autosave since it's not morning and allows me consistently recreate this issue. What I'm also confused about is that there is already another post with this issue, which doesn't seem to have a resolution, but is marked as closed. I'm not sure what causes the bug so I legit can't give steps to reproduce, but I can consistently reproduce this on my own game, not just that save file, but it has happened in other saves as well where I just restarted, since in those ones I would be stuck in morning asleep. I guarantee I have tried every fix available on the internet, including the ones you do before going to sleep such as ungrouping down to four and even just myself, but they don't work.

**Comment by MilkyWhiteLove** [comment]
*EXCEPT for console version script extender. I've also had numerous problems getting that to work

**Comment by Hippo0o** [comment]
The sleep bug is not related to SE.
