### ISSUE TITLE
Problems with my version?

### ISSUE THREAD

**Issue by Kern14** [Norbyte/bg3se#40]
I tried installing with the last two versions of the extension, but the error message appears in both: Scrip extension not available for game version v4.36.24.901

**Comment by mnogg** [comment]
hey, me too. hope someone knows what how to fix this. o/

**Comment by Rukongai** [comment]
Newer versions of script extender requires you to update to at least Patch2. 4.36.24.901 is Hotfix 1

Update your game. If you have any mods that act as overrides or that you install directly to your game data folder, make sure they're updated as well.

**Comment by Kern14** [comment]
> Newer versions of script extender requires you to update to at least Patch2. 4.36.24.901 is Hotfix 1
> 
> Update your game. If you have any mods that act as overrides or that you install directly to your game data folder, make sure they're updated as well.

THANKS VERY MUCH, I downloaded the first version and worked

**Comment by tdimino** [comment]
## StaticData Research Progress (Dec 13, 2025)

### FeatManager Structure (Confirmed via Ghidra)

From `eoc::FeatManager::GetFeats()` decompilation at `0x101b752b4`:
- **+0x7c**: Feat count (int)
- **+0x80**: Feats array pointer (each feat is 0x128 bytes)

```c
struct FeatManager {
    // ...
    int32_t feat_count;     // +0x7c
    void* feats_array;      // +0x80, each entry 0x128 bytes
};
```

### Singleton Discovery Challenge

**Key Finding**: Unlike prototype managers (`SpellPrototypeManager`, etc.) which have exported `m_ptr` symbols, **FeatManager singleton is NOT exported** via dlsym.

**Access Pattern in Game Code**:
1. `GetAllFeats()` at `0x10120b3e8` calls `FeatManager::GetFeats()`
2. `GetAvailableFeatsForProgression()` calls `GetAllFeats()`
3. The FeatManager pointer appears to be passed implicitly or through a global accessor

**Approach Options**:
1. **Hook-based capture**: Hook `GetFeats()` to capture FeatManager pointer at runtime
2. **Ghidra Python script**: Write script to trace ADRP+LDR patterns near TypeId xrefs
3. **Runtime probing**: Use `Ext.Debug.*` to explore ImmutableDataHeadmaster linked list

### GuidResourceManager Pattern (Windows Reference)

Windows BG3SE uses:
```cpp
resource::GuidResourceBankBase* GetRawResourceManager(ExtResourceManagerType type) {
    auto index = staticDataIndices_[(unsigned)type];
    auto defns = GetStaticSymbols().eoc__gGuidResourceManager;
    return (*defns)->Definitions.try_get(index);
}
```

**macOS Gap**: `eoc__gGuidResourceManager` symbol is **NOT exported** on macOS, requiring alternative discovery approach.

### TypeId Address (for Ghidra reference)
- `FeatManager TypeId`: `0x1088efd00`

### Next Steps
1. Write targeted Ghidra Python script for ADRP+LDR pattern discovery near TypeId xrefs
2. OR: Implement hook-based capture similar to prototype managers
3. Document findings in `ghidra/offsets/STATIC_DATA.md`

### Related Functions Discovered
| Function | Address | Purpose |
|----------|---------|---------|
| `FeatManager::GetFeats` | `0x101b752b4` | Returns feat array |
| `GetAllFeats` | `0x10120b3e8` | Wrapper that calls GetFeats |
| `GetFeatTitleAndDescription` | `0x101b7902c` | UI description lookup |
| `RegisterType<FeatManager>` | `0x100c64b14` | TypeContext registration |
