### ISSUE TITLE
Achievements still don't work

### ISSUE THREAD

**Issue by Ryvethe** [Norbyte/bg3se#41]
I've installed the Script Extender correctly, and made sure to download and extract it using the BG3 Mod Manager, AND have the Enable Achievements preference ticked in the Script Extender settings, and my achievements still aren't working. I've tested it with playing fetch with Scratch, and the Bottoms Up achievement, and nothing happening. 
I can't use the Achievements mod on Nexus as the creator has set that mod to disable when it detects the Script Extender, and I can't get rid of the Script Extender as I need it for some of my mods, so ideally I want to get the Script Extender working properly.

**Comment by Norbyte** [comment]
Hi,

Achievements seem to work for me, but it might be a flag that is baked into saves. Do you have a savegame I can test this with?

**Comment by Ryvethe** [comment]
What does it being baked into saves mean? (Sorry, I'm new to modding) 
What would I need to do re a save game you can test it with?

**Comment by Necropants** [comment]
I think I am having this same issue but I have done it with a
ScriptExtenderSettings.json config.

```
{
"CreateConsole": true,
"EnableAchievements": true
}
```
Getting a warning in the log that says
"couldn't enable modded achievements (symbol not mapped)"

Unsure what this means, have I set something wrong?

**Comment by lcard00** [comment]
Hi @Necropants.
I started receiving these messages in the log today as well.

![image](https://github.com/Norbyte/bg3se/assets/58016088/2be1dcc8-d08b-4391-bdaa-5ae98158ca97)

**Comment by Norbyte** [comment]
@lcard00 In your case it's probably because another mod already touches the achievement code of the game, so the extender can't find them.

**Comment by lcard00** [comment]
@Norbyte you're right, there was a conflicting mod. Thank you very much. =)

**Comment by Ryvethe** [comment]
@Norbyte any ideas on my issue?

**Comment by Megalovaniac2000** [comment]
> I think I am having this same issue but I have done it with a ScriptExtenderSettings.json config.
> 
> ```
> {
> "CreateConsole": true,
> "EnableAchievements": true
> }
> ```
> 
> Getting a warning in the log that says "couldn't enable modded achievements (symbol not mapped)"
> 
> Unsure what this means, have I set something wrong? _Edit_ No this seems to work fine for me I just got an achievement



Did you just add this to the .json to make it work?

**Comment by Megalovaniac2000** [comment]
Followup question: do you have to make a new game with the extender already installed to get achieves or will it work if you put it into an existing campaign?

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.

**Comment by froggz19** [comment]
> Hi,
> 
> Achievements seem to work for me, but it might be a flag that is baked into saves. Do you have a savegame I can test this with?

It might be, because I can only unlock achievements with a new save but not with my existing (previously modded) save. I was using 'Adjustable Party Limit' before installing SE then I disabled the mod hoping it would be enough to re-enable the achievements but no luck.

![image](https://github.com/user-attachments/assets/78e4adf7-1964-41e7-9dbe-6b7b6284e387)

Saves

https://drive.google.com/file/d/1mJbkH1s9hi6QN_HKMH5eml9SuEN0ymAi/view?usp=sharing
