### ISSUE TITLE
Combined Logging Levels leading to unexpected performance issues due to "crazy" console updates.

### ISSUE THREAD

**Issue by Kinesia23** [Norbyte/bg3se#42]
> Couldn't enable modded achievements (symbol not mapped)
> bg3se::ExtensionStateBase::LuaResetInternal(): LUA VM reset.
> Configuration for '5eSpells':
>         MinVersion 1; Feature flags: Osiris Lua
> Configuration for 'Warcaster':
>         MinVersion 1; Feature flags: Lua
> Configuration for 'AutoSaver':
>         MinVersion 2; Feature flags: Lua
> Configuration for 'KvCampEvents - v0.4.4':
>         MinVersion 2; Feature flags: Lua
> Configuration for 'RespecIllithidPowers':
>         MinVersion 1; Feature flags: Lua
> Configuration for 'DeityTagActivator':
>         MinVersion 1; Feature flags: Lua
> 6 mod configuration(s) loaded.
> Merged configuration:
>         MinVersion 2; Feature flags: Osiris Lua
> Initializing client with target context Game
> Couldn't enable modded achievements (symbol not mapped)
> bg3se::ExtensionStateBase::LuaResetInternal(): LUA VM reset.
> Loading bootstrap script: Mods/5eSpells/ScriptExtender/Lua/BootstrapClient.lua
> ecl::ScriptExtender::OnGameStateChanged(): Loaded module

It seems that logging level 2 of lua works fine for mod output but was too much for Osiris Lua output, so that developer was using logging level 1, but once you mix the "right" mods together it combines to use the Maximum for each feature, so you get Logging level 2 of Osiris Lua and the console goes _crazy_ especially when loading or starting conversations.

I expect this is behind some of the "random" performance drops or behaviour people can't understand that they just can't quite nail down to repeat...
And unless you moved the console to the front you might not ever find out it was scrolling like crazy with every trigger and tag.
Reminds me of doing things in the old days and having to minimise the console, because it was faster if it didn't have to update the screen while it was printing!

Is it possible to keep the debug levels of normal lua and story lua separate?

thanks for your work.

An example of the end of output.
![image](https://github.com/Norbyte/bg3se/assets/35090754/89238c82-10b4-445f-9e76-a80813b13c98)

It changes as I move of course. 
i'd hate/love to see it in a big fight!

**Comment by Norbyte** [comment]
The console output seems to be generated directly from Lua code of one of the mods. There is no "global" verbosity setting in the extender, prints from Lua are always output to the console, it is up to the mod author to take care of logging.

**Comment by Kinesia23** [comment]
Thanks Norbyte, I made an incorrect conclusion.
The "Merged configuration" messages looked like exactly the weird kind of coincidence that could cause what I was seeing, but it seems it was at least partly coincidental.

What was doing the massive output of data was BG3ScriptTracer.dll in NativeMods that I had foolishly installed at the same time as trying to work out my other mod problems.
The confusing part was that it was using the same Console Window which completely muddled the picture.
If I hadn't looked in the right place I'd probably still be confused by the whole thing.

I'm still working through the combination of mods I'm trying to use, but BG3ScriptTracer was at least one part of the picture.

**Comment by Kinesia23** [comment]
(BG3ScriptTracer makes sense as something some people might install when trying to debug a load failure, so this _might_ explain some people's problems. 
And just the idea of a particular combination of mods firing off messages that trigger each other makes sense for some of the weirder problems that noone can make sense of.
For me, one of my bigger problems ended up being the change to load order of some things that didn't used to have it. In my case Improved UI and Customizer. My saves had them in a default order that no longer worked with newer versions of SE that needed Improved UI first.)
