### ISSUE TITLE
Requires the script extender (currently installed version is v1)

### ISSUE THREAD

**Issue by Entrotom** [Norbyte/bg3se#43]
Even if I download a new version, I keep getting this message in the mod manager. So I cannot use the mods that require a script extender. Even if I download it directly from GitHub or through the mod manager's tool, the same message appears.

**Comment by tlgarrion97** [comment]
im having the same issue. hopefully there will be a fix for it soon or somone can help explain whats going on

**Comment by Norbyte** [comment]
What's your game version?

**Comment by MadamAvaCouture** [comment]
Im also running into this issue.  My game version is 4.11.3700362

**Comment by Kvalyr** [comment]
This sounds like people are being confused by the version shown in BG3 Mod Manager - Which always shows as v1.
I don't think this is a Script Extender issue, just people being confused by the disconnect between version shown in BG3MM versus the version of Script Extender actually installed.

For those of you confused: Enable the script extender console and launch the game. You'll see the actual version in the console.

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
