### ISSUE TITLE
Game crashes when activating 'Fake Fullscreen' with Photomode Tools on Vulkan (SE v18 + MCM 1.10.0)

### ISSUE THREAD

**Issue by AtilioA** [Norbyte/bg3se#436]
### I have attempted solutions to common problems

Yes

### I have checked that my game version is supported

Yes

### OS

Windows 11

### Platform

Steam

### Description

I'm relaying a report from a user. 
The game crashes when activating "Fake Fullscreen" in the Baldur's Gate III photomode tools (v1.0.19 by Otis_Inf) while using the Vulkan rendering API. This issue started occurring after updating MCM to 1.10.0. The issue does not occur when using DirectX 11 or when using MCM 1.9.0. The crash only happens with this specific mod active; if all other mods are active except this one, the issue does not occur.

Quoted from the user:
> So far, this is only happening when running the game using Vulkan and not DirectX 11. The issue seems to be occurring with version 1.10.0 of this mod, specifically, as 1.9.0 continues to work just fine for me.
> The crash seems to occur only while this mod is active, and I have tried loading the game while no mods except this one were active with the same result. If all mods I use are active except for this one, then the issue seems to vanish altogether.
> I have tried restarting my computer, ensuring Windows and drivers were up-to-date, scanning Windows for corruption, verifying the integrity of the BG3 game files, and fully reinstalling Script Extender (not just deleting and redownloading the DWrite.dll, but also everything under "...\AppData\Local\BG3ScriptExtender") with no change in the end result.
> Regardless of whether or not this is something you can assist with, thank you very much for your time! I'll try to provide all requested information below, but please let me know if you require anything else.

### Indications

The game crashes with a SE dump: `e546`

### Diagnostic Files

N/A, I'm relaying a report from a user.

System specs:
GPU: NVIDIA GeForce RTX 3060
CPU: 11th Gen Intel(R) Core(TM) i7-11700F @ 2.50GHz
OS: Windows 11 Home (Version: 23H2) 

SE Console logs:
```
Configuration for 'Mod Configuration Menu':
MinVersion 18; Feature flags: Lua 
1 mod configuration(s) loaded.
Merged configuration:
MinVersion 18; Feature flags: Lua 
Initializing client with target context Load
Modded achievements enabled.
bg3se::ExtensionStateBase::LuaResetInternal(): LUA VM reset.
Configuration for 'Mod Configuration Menu':
MinVersion 18; Feature flags: Lua 
1 mod configuration(s) loaded.
Merged configuration:
MinVersion 18; Feature flags: Lua 
Initializing client with target context Game
bg3se::ExtensionStateBase::LuaResetInternal(): LUA VM reset.
Loading bootstrap script: Mods/BG3MCM/ScriptExtender/Lua/BootstrapClient.lua
[38;2;0;255;255;48;2;12;12;12m[Mod Configuration Menu][C]: Volitio's Baldur's Gate 3 Mod Configuration Menu version 1.10.0 loaded (SE version 18)
[38;2;100;200;150;48;2;12;12;12m[Mod Configuration Menu][TEST-0][C]: Done loading MCM configs
ecl::ScriptExtender::OnGameStateChanged(): Loaded module
[38;2;100;200;150;48;2;12;12;12m[Mod Configuration Menu][TEST-0][C]: Done loading MCM configs
ScriptExtender::Shutdown: Exiting
ecl::ScriptExtender::Shutdown: Exiting
```

### Steps to Reproduce

1. Launch Baldur's Gate III with Script Extender v18 and MCM 1.10.0.
2. Load the game using the Vulkan rendering API.
3. Activate "Fake Fullscreen" in the Baldur's Gate III photomode tools (v1.0.19).
4. Observe the game crashing.

### Expected Behavior

The game should not crash when activating "Fake Fullscreen" in the photomode tools, regardless of rendering API or active mods.

### Actual Behavior

The game crashes when "Fake Fullscreen" is activated in the photomode tools.

**Comment by Norbyte** [comment]
This is fixed in v19.
