### ISSUE TITLE
game crashed after patch 7

### ISSUE THREAD

**Issue by planetbear** [Norbyte/bg3se#438]
### I have attempted solutions to common problems

Yes

### I have checked that my game version is supported

Yes

### OS

Windows 10

### Platform

Steam

### Description

I turn on the console, when the game starts, it shows:

> No match found for mapping 'Is__GlobalAllocator' [CRITICAL]
> No match found for mapping 'ls::FileReader::ctor' [CRITICAL]
> No match found for mapping 'EoCServer2/EoCClient2' [CRITICAL]
> No match found for mapping 'ecl::EocCClient::HandlError' [CRITICAL]
> No match found for mapping 'esv::GameStateThreaded::GameStateWorker::DoWork' [CRITICAL]
> No match found for mapping 'esv::SavegamePostVisit_DisableStoryMerge' 
....

> ScriptExtender::Initialize: Could not load libraries; skipping scripting extension initialization

than game crashes.

**Comment by planetbear** [comment]
after i manually install the dll files (Nexus Version, two files: DWrite.dll,libprotobuf-lite.dll), it works. please close this issue, sorry for inconvenience

**Comment by Obiefius** [comment]
Di yiu gave MSI afterburner running if so please close it

**Comment by planetbear** [comment]
> Do you gave MSI afterburner running? if so please close it, the RTSSHOOK64.dll tries to hook into the game and it crashes with the SE.

I don't have MSI afterburner, I'm using Alienware X17 r1
