### ISSUE TITLE
Moonrise Tower Minthara looping dialogue [possible game spoilers]

### ISSUE THREAD

**Issue by ShaguarWKL** [Norbyte/bg3se#45]
Encountered this issue where once Minthara joins the party whether pre-formal join (as follower) or as full party member (and you bring her back to MR Tower) she would keep on initiating dialog with main character or if NPC initiates dialog with Minthara causing a nonstop loop.

I only found out this is an issue with BG3SE from a reddit post and confirmed that by disabling BG3SE, the issue stops and currently the workaround is to avoid MR Tower with Minthara in party or disable BG3SE. BG3SE has to be disabled to get her out of the tower. 

I did this by renaming DWrite.dll to get her out of the tower as a follower. I found out about the NPC looping dialogue with Minthara only because I brought her back to MR Tower with BG3SE reenabled to finish up the area and the NPC guards initiated dialogue with Party and Minthara was the closest party member and so got stuck in the dialog loop again.

**Comment by EArmour** [comment]
Are you also using any mods that make use of BG3SE, which would be disabled along with it? I've seen this same looping issue reported as an issue specifically with [Camp Event Notifications](https://www.nexusmods.com/baldursgate3/mods/1879), one of the reasons I haven't installed it myself yet. But if it's happening without the mod at all, that would probably be interesting for the author to know that something inherent to the Script Extender could be causing it.

**Comment by ShaguarWKL** [comment]
Yeah I have mods that require BG3SE that's why its installed. I also have CEN installed. I'm already passed the Tower on my current playthrough and I don't have saves to see if CEN is the culprit easily.

I've posted a comment asking the OP of the thread I saw on Reddit to see if he also has CEN installed.
https://www.reddit.com/r/BaldursGate3/comments/16cm6az/stuck_in_a_dialogue_loop_with_minthara/

**Comment by ShaguarWKL** [comment]
I scrolled through the CEN posts and seems like conflicting reports of 0.4.3 fixing this for some and not for others. 0.4.4 is latest and mod creator is aware of this and is hoping to clean up all the code to avoid this issue by 0.5.0 release.
