### ISSUE TITLE
Repeating "hookapp" error

### ISSUE THREAD

**Issue by CALLMEBR1CK** [Norbyte/bg3se#450]
### I have attempted solutions to common problems

Yes

### I have checked that my game version is supported

Yes

### OS

Windows 11

### Platform

Steam

### Description

the script extender console won't allow me to input commands because it just repeatedly types.
HookApp::deferHook,
HookApp::findGameWindow, injectWindow: 0000000000000000
HookApp::findGameWindow, graphicsWindow: 0000000000000000
I've looked everywhere for a fix and tried reinstalls too but it only seems that me and 3 other people from a reddit thread are running into this issue.

**Comment by landaire** [comment]
For anyone else coming to this from a search engine, the software which is injecting code into the game and causing the `HookApp::` logs is `Medal`.

You can search the application memory for that string:

<img width="1814" height="1208" alt="Image" src="https://github.com/user-attachments/assets/34b81722-216b-4783-aca5-ae6e99f7ba09" />

And then use `!address <string_address>` to show it lives in Medal's module:

<img width="1826" height="906" alt="Image" src="https://github.com/user-attachments/assets/ddbd0ca2-8074-4251-994f-c73fbb2c2d92" />

Closing or uninstalling Medal -- or perhaps if Medal has a way to prevent itself from being injected into an application doing that -- should resolve this.
