### ISSUE TITLE
Missing definition for ImGui_ImplDX11_RenderObjectsInitialized

### ISSUE THREAD

**Issue by FineRedMist** [Norbyte/bg3se#457]
### I have attempted solutions to common problems

Yes

### I have checked that my game version is supported

Yes

### OS

Windows 10

### Platform

Steam

### Description

Hi Norbyte,

I've been working on a mod; however, I keep seeming to need features that haven't been released yet. I've been compiling bg3se and running it fine up until Patch 7. 

The first issue is a failure to compile because ImGui_ImplDX11_RenderObjectsInitialized isn't defined. I have searched the internet, discord, and grepped the source code but I have yet to find it. Where would I find this? To get by, I have commented out that test in DX11.inl.

This could be why creating imGui windows seems to crash the game in nVidia dlls. Both my mod (which creates imGui windows) and the mod configuration manager (download, no changes) encounter this with my local build of the script extender.

Where would I find this method? I'm hoping it will remedy my issue.

Thank you,
FineRedMist

### Indications

The game crashes in nVidia dlls when creating imGui windows.

### Steps to Reproduce

1. Fork bg3se from main
2. Download external libraries
3. Generate proto and maps
4. Attempt to build

### Expected Behavior

bg3se compiles

### Actual Behavior

Compiling generates the error:
1>F:\GitHub\games\bg3se\BG3Extender\Extender\Client\IMGUI\DX11.inl(139,40): error C3861: 'ImGui_ImplDX11_RenderObjectsInitialized': identifier not found
1>(compiling source file '/Extender/Client/IMGUI/IMGUI.cpp')

**Comment by Norbyte** [comment]
Indeed Externals.7z folder has been out of sync for a while, I've updated it to the latest changes

**Comment by FineRedMist** [comment]
I'm getting new compile failures with the updated Externals:

`
1>{RootFolder}\bg3se\External\NoesisGUI-NativeSDK-win-3.1.7-Indie\Include\NsCore\Delegate.inl(65,17): error C3861: 'Placement': identifier not found
1>(compiling source file '/Extender/Shared/dllmain.cpp')
1>    {RootFolder}\bg3se\External\NoesisGUI-NativeSDK-win-3.1.7-Indie\Include\NsCore\Delegate.inl(65,26):
1>    'Placement': function declaration must be available as none of the arguments depend on a template parameter
1>    {RootFolder}\bg3se\External\NoesisGUI-NativeSDK-win-3.1.7-Indie\Include\NsCore\Delegate.inl(65,26):
1>    the template instantiation context (the oldest one first) is
1>        {RootFolder}\bg3se\External\NoesisGUI-NativeSDK-win-3.1.7-Indie\Include\NsCore\Delegate.inl(11,7):
1>        while compiling class template partial specialization 'Noesis::DelegateImpl<Ret(Args...)>'
`

**Comment by FineRedMist** [comment]
I did a clean build of just BG3Extender; I don't need the other projects to build (yet). I'm unblocked now. Thank you!

![image](https://github.com/user-attachments/assets/8a3ebdfc-2d6e-4220-b55f-35b635d0b935)

**Comment by FineRedMist** [comment]
Unblocked now, thank you!

**Comment by chrisoutwright** [comment]
I still get the issue with
6>GameDefinitionHelpers.cpp
6>C:\Users\chris\Downloads\bg3se-main\bg3se-main\BG3Extender\Extender\Client\IMGUI\DX11.inl(153,40): error C3861: "ImGui_ImplDX11_RenderObjectsInitialized": Bezeichner wurde nicht gefunden.
6>(Quelldatei „/Extender/Client/IMGUI/IMGUI.cpp“ wird kompiliert)

which imgui version do I need to use?
