### ISSUE TITLE
I have Script Extender Installed but not detecting it

### ISSUE THREAD

**Issue by Bluace** [Norbyte/bg3se#466]
### I have attempted solutions to common problems

Yes

### I have checked that my game version is supported

Yes

### OS

Windows 11

### Platform

Steam

### Description

I installed the Script Extender but BGMM isn't detecting it. I did what the instructions said, install script extender and extract it all to my "Baldurs Gate 3/bin" folder, but BG3MM isn't saying that it's installed. 
![Screenshot 2024-10-17 075542](https://github.com/user-attachments/assets/0c0362f9-97a1-4a0c-9dc8-987f7343c03f)

**Comment by Erixperience** [comment]
"Go to Tools -> Download and install Script Extender
Close BG3MM
Open the Game so it actually installs it (the dll isn't SE, but a command to install once the game is launched - this actually may only be what you need to do)
Quit the game
Open BG3MM"

Per some digging on reddit. I had the same issue, and the SE did install. Having other issues with my mods, but it did get the warnings to go away in the mod manager. Hope this helps.

**Comment by Bluace** [comment]
> "Go to Tools -> Download and install Script Extender Close BG3MM Open the Game so it actually installs it (the dll isn't SE, but a command to install once the game is launched - this actually may only be what you need to do) Quit the game Open BG3MM"
> 
> Per some digging on reddit. I had the same issue, and the SE did install. Having other issues with my mods, but it did get the warnings to go away in the mod manager. Hope this helps.

Thank you so much, it finally worked! Have a great day/night wherever you are!
