### ISSUE TITLE
How do I get Orpheus, Prince of the Comet, Part Two: Sacrifice

### ISSUE THREAD

**Issue by FrozenMode** [Norbyte/bg3se#484]
### I have attempted solutions to common problems

Yes

### I have checked that my game version is supported

Yes

### OS

Windows 10

### Platform

Steam

### Description

How do I get Orpheus, Prince of the Comet, Part Two: Sacrifice? I missed being able to get it at the creche and i'm trying to spawn it. I was able to get part 1 with TemplateAddTo("0f5d749b-b620-43e0-bf06-ea4e9f63b642", GetHostCharacter(), 1) But the only UUID for part 2 I could find was 4dbaf850-49ff-4e41-adc2-7054e416c960 I tried with TemplateAddTo("4dbaf850-49ff-4e41-adc2-7054e416c960", GetHostCharacter(), 1) but nothing went into my inventory. What am I missing here? I looked for Orpheus, Prince of the Comet, Part Two: Sacrifice in https://blueneuron.net/hexdatabrowser/ and that is the only thing that came up.

### Indications

It's a console command not a mod

### Steps to Reproduce

1.  Type TemplateAddTo("4dbaf850-49ff-4e41-adc2-7054e416c960", GetHostCharacter(), 1) In the console window and hit enter
2. Nothing happens!

### Expected Behavior

It should give me the book

### Actual Behavior

No book even though I am putting the correct uuid

**Comment by hawchangJA** [comment]
I searched for the RootTemplates files in gustav.pak and shared.pak, but could not find "4dbaf850-49ff-4e41-adc2-7054e416c960". I believe the Script Extender is working correctly.

**Comment by FrozenMode** [comment]
> I searched for the RootTemplates files in gustav.pak and shared.pak, but could not find "4dbaf850-49ff-4e41-adc2-7054e416c960". I believe the Script Extender is working correctly.

Well than what is it? That's the only uuid I could find for it.

**Comment by hawchangJA** [comment]
At least the other items are available with that command, so it's not a Script Extender issue. You're asking in the wrong place.

**Comment by FrozenMode** [comment]
Well then where do I ask, this is the only place andybody is helping me
