### ISSUE TITLE
no console

### ISSUE THREAD

**Issue by nderamo0360** [Norbyte/bg3se#49]
im pretty sure I installed it correctly, but I cant get the console to show up

**Comment by lcard00** [comment]
Hi there, do you have the file "ScriptExtenderSettings.json" in the bin folder of BG3?

`{
  "CreateConsole": true,
  "DeveloperMode": true,
  "EnableLuaDebugger": true,
  "EnableLogging": true,
  "LogCompile": true,
  "LogFailedCompile": true,
  "LogRuntime": true
}`


![image](https://github.com/Norbyte/bg3se/assets/58016088/53c74339-68eb-42fe-b543-d93fe51b7414)

**Comment by nderamo0360** [comment]
Yes. I looked at it. It's correct

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
