### ISSUE TITLE
Confirmation "Working Yes/No" keeps prompting

### ISSUE THREAD

**Issue by arthurh3535** [Norbyte/bg3se#5]
I keep getting this weird prompt asking if this (whatever this is) is working. Answering Yes or No does not change anything. I'll just pop up a minute or two later.

**Comment by Norbyte** [comment]
Did you install the sample mod that comes with the extender? That one is meant for modders, sounds like this prompt is from that.

**Comment by arthurh3535** [comment]
Not that I'm aware of, but Hot Fix #4 did land today too.

**Comment by BloodTwin** [comment]
Same problem here!, any solution ?

**Comment by Norbyte** [comment]
That's curious, what steps did you take to install the extender? Just download the DLL and place it in bin\?

**Comment by PyrionCelendil** [comment]
Ran into this as well, determined the cause on my end to be an old version (1.0.20) of the 5eSpells mod.

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
