### ISSUE TITLE
not launching

### ISSUE THREAD

**Issue by XetoKiyaba** [Norbyte/bg3se#52]
im on hotfix#6 and ive done it right not my first time using script extenders its in the bin with the bg3.exe but on launch it just does nothing

**Comment by XetoKiyaba** [comment]
it sees as though it also downloads a folder to
C:\Users\AppData\Local\BG3ScriptExtender
however the folder remains empty and nothing happends not criticizing but it sucks that its put to a internet download.
 can you post the required files se i can manually insert or force it to work right now im stuck limp noodle with just the files to hook and download the required filed that isnt working

**Comment by Norbyte** [comment]
Can you try with this version and post the console output?
If it still fails, set `"IPv4Only": true` in `ScriptExtenderUpdaterConfig.json` and see if it has any effect.
[BG3SE-Updater-v4-Debug.zip](https://github.com/Norbyte/bg3se/files/12651389/BG3SE-Updater-v4-Debug.zip)

Alternatively an updaterless version is available here:
https://bg3se-updates.norbyte.dev/Channels/Release/ManualInstall.zip
(Note: You have to update this one manually each time a new build comes out.)

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
