### ISSUE TITLE
Script Extender update failure

### ISSUE THREAD

**Issue by tafeilgh** [Norbyte/bg3se#53]
Script Extender update failure; make sure your connected to the internet and try again. Unable to download manifest (28) SSL connect error.

**Comment by LeoSkylynx** [comment]
Script Extender update failed; make sure you're connected to the internet and try again. Unable to download manifest: (7) Couldn't connect to server

**Comment by Norbyte** [comment]
Can you try with this version and post the console output?
If it still fails, set `"IPv4Only": true` in `ScriptExtenderUpdaterConfig.json` and see if it has any effect.
[BG3SE-Updater-v4-Debug.zip](https://github.com/Norbyte/bg3se/files/12651389/BG3SE-Updater-v4-Debug.zip)

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
