### ISSUE TITLE
Achievements Not Working but says enabled

### ISSUE THREAD

**Issue by miztme21** [Norbyte/bg3se#55]
Any help would be great
No achievements are popping here is the script

BG3Ext v3 built on Sep  8 2023 17:58:52
Game version v4.37.0.362 OK
ScriptExtender::Initialize: Starting
Library startup took 624 ms
LibraryManager::PostStartupFindLibraries() took 58 ms
Configuration for '5eSpells':
        MinVersion 1; Feature flags: Lua
Configuration for 'Expansion':
        MinVersion 1; Feature flags: Lua
Configuration for 'SubclassCompatibilityFramework':
        MinVersion 3; Feature flags: Lua
Configuration for 'TutorialChestSummoning':
        MinVersion 2; Feature flags: Lua
Configuration for 'AppearanceEdit':
        MinVersion 1; Feature flags: Lua
Configuration for 'Daughter of Lolth - Chosen Path':
        MinVersion 2; Feature flags: Lua
Configuration for 'BG3ShadowSorcerer':
        MinVersion 1; Feature flags: Osiris Lua
7 mod configuration(s) loaded.
Merged configuration:
        MinVersion 3; Feature flags: Lua Osiris
Initializing client with target context Load
Modded achievements enabled.
bg3se::ExtensionStateBase::LuaResetInternal(): LUA VM reset.

**Comment by The-Antagonist-Weeb** [comment]
I have the same issue here as well. Not sure what's going on, and I've tried quite a bit. Including just getting the achievement enabler mod (w/ NativeMods mod) to enable them, but I still get no achievements from steam.

**Comment by miztme21** [comment]
I was able to fix it by deleting the achievement enable mod which isn't needed.  Also I downloaded a save game achievement and soon i loaded it the achievement popped and has since worked! Also had the game load up through steam, not sure if that's needed or not though.

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
