### ISSUE TITLE
Data mismatch

### ISSUE THREAD

**Issue by Dissim** [Norbyte/bg3se#56]
My game worked perfectly with the archive, when a friend of mine tried to install it too but it kept saying ther was a data mismatch, as if the archive was corrupted or had some conflict with another game archive, is there any plausible cause to that? We couldnt manage to understand what was happening, the only difference we noticed is that the game didnt even seem to understand the archive as a executable script. Anyone know what could be happening?

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
