### ISSUE TITLE
Script Extender Updater Error

### ISSUE THREAD

**Issue by ForgottenQueen** [Norbyte/bg3se#57]
Every time I launch the game, it gives me a pop up error message that says "this game version is too old and only supports Script Extender V1; make sure you're on patch 2+ for newer versions"
My game will then CTD if I don't close it first. I have tried uninstalling and reinstalling the SE, I picked up the two versions that you sent to a different error last night (the updater version gave me the same error, the manual version didn't work at all). I have never had the second window with the command box come up. My game *is* up to date and is set to be high priority. The issue persists even when using BG3's mod manager tool function to download and extract the script extender. 

I'm sorry if this is completely not your problem, I'm just unsure what to do at this point. I do know that I successfully used your SE before I went back to vanilla BG, but this time it's just not working out for me. If anyone has suggestions on how else I can troubleshoot please let me know. Sorry again and thank you for your time. I've been running the game without SE with no problems.
![Untitled](https://github.com/Norbyte/bg3se/assets/145465468/4a4364ab-4ff1-430f-a63b-281ff846e544)

**Comment by ForgottenQueen** [comment]
I tried installing the SE again, and this time I got it to bring up the command console. Unfortunately, it then CTD before it could even reach the main menu.

**Comment by Kvalyr** [comment]
Did you get the game on Steam or from a different store?

**Comment by ForgottenQueen** [comment]
Yes, I have it on Steam. Sorry for the late response!

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
