### ISSUE TITLE
Can't find WINEDLLOVERRIDES="DWrite.dll=n,b"

### ISSUE THREAD

**Issue by Malfolin** [Norbyte/bg3se#59]
When I launch the game it just writes  "Can't find WINEDLLOVERRIDES="DWrite.dll=n,b", check if the name is right and try again".

**Comment by Malfolin** [comment]
Ok, I fixed it buy just reinstalling Mod Fixer with BG3 MO (first I installed it by hand and it didn't work).

**Comment by solgrove** [comment]
If anyone out there, like me, tries reinstalling the Mod Fixer and it still doesn't work then I have the secret right here:

Read the directions more clearly. You only need to do the WINEDLL thing if you're running Linux. Don't do it in Windows.

That's what I get for skimming...

**Comment by Norbyte** [comment]
I've since clarified the instructions to make _extra_ sure people don't do this :P
