### ISSUE TITLE
GPTK / Whisky? 

### ISSUE THREAD

**Issue by DeanMaxwell** [Norbyte/bg3se#60]
I've seen some people getting this working on Steam Deck and Proton. Anyone have any luck with macos running GPTK wine or the macos version of Heroic launcher? 

Have also tried setting WINEDLLOVERRIDES="DWrite.dll=n,b" PROTON_NO_ESYNC=1 %command% and just
WINEDLLOVERRIDES="DWrite.dll=n,b" in the user.reg, but no luck so far.

**Comment by DeanMaxwell** [comment]
Got it working with Whisky. Just open up the wine configuration tab under configuration settings for your wine bottle and add dwrite in the Libraries tab. 

<img width="424" alt="Screenshot 2023-09-20 at 3 51 35 PM" src="https://github.com/Norbyte/bg3se/assets/52510954/696e156f-dabc-452b-af03-aaf0b780a00a">

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
