### ISSUE TITLE
Errors in ScriptExtender Console but no Problem playing/creating new game

### ISSUE THREAD

**Issue by Pyr0blad3** [Norbyte/bg3se#61]
Hello dear ScriptExtender Dev/s,

Currently i am using a lot of mods and today I noticed that in the ScriptExtender Console 4-6 errors accure when trying to start a new game (save file).

Weirdly enough, because I cant spot any "bugs", "missing features" or anything like that related to my mods so far.
Also loading an existing save file works without problems. (No errors in ScriptExtender Console)
I tested this till i found the "mods" which create the error messages, BUT as I said I didnt notice any problems with those mods installed.

So my question would be, could you look over the following Logs and Console Screenshots, maybe you notice something thats a red flag. I dont know if these could cause problems during a playthrough and I dont want to start from new just because of this.

This might not be a problem but i wanted to be sure before beginning my next modded playthrough. I hope you understand.
SO here are the Logs/Console Screenshots:

//Try to create a new game (save file)
![2023-09-21 14_26_07-BG3 Script Extender Debug Console](https://github.com/Norbyte/bg3se/assets/28388430/16b91917-e6fa-48b8-8ad9-187247ad7452)

//Error Log from creating a new game (save file), AGAIN its only the log, I can play and create new saves without problem.
[Compile 2023-09-21 12-25-59.log](https://github.com/Norbyte/bg3se/files/12684518/Compile.2023-09-21.12-25-59.log)

//Loading an existing game (save file)
![2023-09-21 14_26_52-BG3 Script Extender Debug Console](https://github.com/Norbyte/bg3se/assets/28388430/a7debb41-6fce-4bf0-9a1b-0d60ccc60ca3)

Your view, any help or comment on this would be really appriciated.
edit: if you need anything from me please feel free to ask.
Cheers and thanks for your work!

**Comment by Norbyte** [comment]
The compile error is the result of the mod fixer at work, it is 'normal' to see that.

**Comment by Pyr0blad3** [comment]
Thank you!
Now and for the furture i know : )
