### ISSUE TITLE
CreateConsole : True = Crash

### ISSUE THREAD

**Issue by MediumAlco** [Norbyte/bg3se#62]
As the title says if I download and use one of the premade ScriptExtenderSettings.json files or create my own; No matter if it's v1, v2, 3, 4-Debug linked in a different issue thread here, any settings.json with the line " "CreateConsole": true, " will crash my game at the launcher with the "invalid files" crash dump. 
If I launch the game through BG3 Mod Manager the game will will work but the console doesn't appear and loading (into the main menu, and from the menu into the game) takes roughly twice as long as normal.

I'm on Linux mint 21.1 running the game with Vulkan through Steam on Proton 8.0-3 using the launcher, I have the DLL Override in the Launch Options. If I take the line "CreateConsole" out of the settings (or delete the settings JSON entirely) the game works perfectly fine with my mods installed using the Script Extender. 

I'm happy to try to provide any other information you might need to solve this. Hopefully it's just me being dumb somehow. Thanks in advance!

**Comment by MediumAlco** [comment]
In digging into this I've come to learn this is apparently just one of those lovely 'linux' issues more so than something that can be fixed with the program itself.
Sorry for wasting the time of anyone who read this. Hah!

**Comment by StuffOfSonny** [comment]
I second this issue, as I have two separate Linux machines (Main Rig, EndeavourOS | SteamDeck, SteamOS) and I think it should be addressed that a rather important feature simply does not work. If I may offer a suggestion, look into Skyrim Script Extender, as that creates a console/terminal just fine.

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
