### ISSUE TITLE
No match found for mapping - possibly causing save issues?

### ISSUE THREAD

**Issue by MikeRea95** [Norbyte/bg3se#65]
Launching the extender, I get these warnings:
`No match found for mapping 'esv::SavegameManager::WarnIfModded'
No match found for mapping 'ecs::ComponentIDRef'
No match found for mapping 'ecs::EventComponentIDRef'
No match found for mapping 'ecs::ReplicationComponentIDRef3'`
The first one references the SavegameManager, and since getting these new errors, I've started having issues saving. I often get Error 516 when trying to save. I've tried quite a few suggestions for fixing Error 516, such as making more disk space (I already had 150gb open), validating game files, and updating drivers, and nothing has stuck. Anyone else had this issue? Could this be because of SExtender?

**Comment by Norbyte** [comment]
Hi,

516 is a story serialization error, it means the game was unable to write story save data. 
The errors mentioned above are 'normal' and will always appear.
