### ISSUE TITLE
v5: Inconsistent behaviour from entities after reloading save

### ISSUE THREAD

**Issue by Kvalyr** [Norbyte/bg3se#67]
Version:
```
BG3Ext v5 built on Sep 22 2023 19:37:36
Game version v4.37.32.833 OK
```
To Reproduce issue:
```
-- Freshly-started BG3, load a save or start a new game:
-- Do: 
_D(_C():GetAllComponentNames()) --> gives results as expected
```
```
-- Reload save
-- Do again: 
_D(_C():GetAllComponentNames()) --> gives `[]`
```

Returning to main menu and loading back into the game doesn't fix.
Returning to main menu and starting a **new** game seems to fix.

Loading from the new game (new tav) to the older save (older tav): Entity works fine.
Reloading from the old game (old tav) to the same save (old tav): Entity breaks again.

Harder to reproduce on a new game, but consistently happens on the older save(s).

No other calls or replications in between.

**Comment by Norbyte** [comment]
Hotfixed!

**Comment by Kvalyr** [comment]
Amazing, thank you!
Fix confirmed in-game - Closing!
