### ISSUE TITLE
Script Extender Update Error | Syntax Error

### ISSUE THREAD

**Issue by Myzraev** [Norbyte/bg3se#68]
![ScriptExtenderFailure](https://github.com/Norbyte/bg3se/assets/111588008/de35adcd-7577-49e6-9ea9-41a5fa38d831)

I get the attached error message upon loading into the menu, AppData shows v5 installed. When I hit accept and load a savegame however if any mods that use Extender are active it immediately deactivates all mods irrespective of their Extender usage (I've confirmed deactivation via both BG3MM and checking ingame).

I have also tried it with no mods and still get the pop-up.

**Comment by Azzmodeus** [comment]
Same here

**Comment by Matteo8633** [comment]
Is It possible to have a new release?

**Comment by AegrosDescending** [comment]
Received this same error this morning.

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
