### ISSUE TITLE
Disconnecting from Multiplayer? Unsure why

### ISSUE THREAD

**Issue by Ghostlyjet** [Norbyte/bg3se#71]
Not sure if this is due to the script extender or not but my gf and I have been trying to figure out why we are disconnecting from each other when we try to join one another. We both have all of our mods up to date and the Script Extender is on v5. Did the new patch for BG3 mess up multiplayer with mods or something?

**Comment by Bnidoya** [comment]
> Not sure if this is due to the script extender or not but my gf and I have been trying to figure out why we are disconnecting from each other when we try to join one another. We both have all of our mods up to date and the Script Extender is on v5. Did the new patch for BG3 mess up multiplayer with mods or something?

I'm sure it's not. I used 150+mods and it's normal to play online with friends

**Comment by Ghostlyjet** [comment]
Did a nuke option of fresh starting with mods and it worked. No idea what the culprit was but oh well.
