### ISSUE TITLE
mod manger doesn't recognize v3 

### ISSUE THREAD

**Issue by phaontom** [Norbyte/bg3se#72]
so i installed the correct version on the script but the mod manger still say its v1

**Comment by belowzeros** [comment]
it's normal, it has never shown more than v1.0 on the BGMM UI.

however an iteration of v5 is the latest ver of BGSE you need to match the current patch of the game

**Comment by phaontom** [comment]
can you link it to me because i only see v3  even when i look at the latest ver

**Comment by belowzeros** [comment]
> can you link it to me because i only see v3 even when i look at the latest ver

the most current version is at the bottom of this page 
https://bg3se-updates.norbyte.dev/Channels/Release/Manifest.json

referenced here 
https://github.com/Norbyte/bg3se/issues/24#issuecomment-1722539413

**Comment by senthhh** [comment]
> so i installed the correct version on the script but the mod manger still say its v1
if you see v1 it means that you are using an old version of the game

https://github.com/Norbyte/bg3se/issues/26

**Comment by BelegCufea** [comment]
@phaontom 

Just to be clear.

- On github there is v3 of the UPDATER. It IS the latest version of Updater.
- In BGMM it will say v1. Don't pay any attention to it!
- The Udater you donwloaded from here will install Script Extender into %Appdata%/Local/BG3ScriptExtender (Win10) or %LocalAppdata%/BG3ScriptExtender (Win11) on game launch.

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
