### ISSUE TITLE
i have never used github before and have no idea what i'm doing

### ISSUE THREAD

**Issue by PNut8421** [Norbyte/bg3se#73]
please explain how to download and install this script extender for BG3 like i'm a 5 year old. i have never used this site before and have absolutely no idea what i'm doing.

**Comment by PNut8421** [comment]
i went to "downloads available here", saw "Download the extender [from here]" downloaded the file, and all that was in the file i extracted was a .DLL which did absolutely nothing. what am i doing wrong and please explain it like i'm 5.

**Comment by BelegCufea** [comment]
@PNut8421
If you extracted DWrite.dll to the Baldurs Gate 3\bin directory, you should be fine. This will dowload/update the Script Extender on game launch.

Just to be claer. This "mod" does NOT do anything itself. It is just pre-requirement for other mods. So if you don't have any, that specifically instructs you to install Script Extender, you will not profit from it in any meaningful way.

Hope it helps.

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
