### ISSUE TITLE
Console appears on launch but disappears on game launch

### ISSUE THREAD

**Issue by kyokitami** [Norbyte/bg3se#75]
Hey, so I'm pretty sure I got the Script Extender installed in the right locations but here's the problem:

When I launch thru the Mod Manager the console window does appear, but once the game launches is just straight up disappears. And yes the script extender JSON file is there with the necessary code.

Any ideas on how to fix this? I've reinstalled my game and reinstalled all the mod files twice but it still happens. Tried deleting the script extender folder in AppData before relaunching but no luck as well.

Photo below just to show that console appears when launching thru mod manager.
After the last line, game would launch but console window disappears.

![ql9dgcjql7qb1](https://github.com/Norbyte/bg3se/assets/146052842/8cf34532-fd38-423d-a84c-1de96d9b607a)

**Comment by Norbyte** [comment]
This was an issue with the "double launching" behavior the game has when running from the .exe directly and has been fixed since.
