### ISSUE TITLE
Scriptextender resets my modsettings.lsx

### ISSUE THREAD

**Issue by sirkingjamz** [Norbyte/bg3se#76]
So I don't know how long this has been going on, maybe a day or two now but no matter what I do as soon as the console opens it overwrites a blank mod list to the modsettings.lsx file, I know its BG3SE because if i make the file read only after exporting from BG3MM (also with vortex but I have other issues with that loader not related to this issue), it then told me something about not beign able to replace it with the tmp file it made (which was 1kb large and my modsettings file is over 243kbs) Nothing I do seems to work :(

**Comment by BelegCufea** [comment]
@sirkingjamz  Happened to me when installing some version of [Better Containers](https://www.nexusmods.com/baldursgate3/mods/1416) mod. The mod Author found out that it was due to some not "supported" characters in mod folder name when creating PAK file (post [here](https://forum.nexusmods.com/index.php?showtopic=13167849/#entry128202675)). In hindsight Script Extender may be the culprit, but repacking the mod with "corrected" folder name helped.
For quick "hotfix" check if you have recently updated/installed a mod, that may cause that issue.

Don't know what is the real problem though. It may be LSLib, BG3 itself or even Script Extender ... :-(

**Comment by sirkingjamz** [comment]
@BelegCufea Yeah that's what i was thinking as well and I removed all the new downloads i had put in last night, purged my mods folder (manually deleting the files) then tried again and it still was wiping the list clean shortly after loading. I removed the Containers mod as you suggested as well, but it never gave an issue before and the forum you posted was from the 22th and it was "mostly" resolved for the .8 file and i use the 6x7 file (but it is only patch #2 so i removed it until its updated, ill re-enable it when its updated). Also I've also tried the bug infested Vortex manager as well and it did the same thing. I can only assume its either the game (but it worked fine even with the container mod on the 24th) or this mod. 
i don't even know what log to upload for help either: crashdump, extenderruntime, gold, network, Osiris Runtime, osirislog
Though my issue continues :( my only other idea is a full reinstall and see if it persists, sure ill possibly lose HUNDREDS of hours :(

**Comment by BelegCufea** [comment]
@sirkingjamz 
Sorry to hear that :-(

I have no clue how anything of this work, but it seems that it will happen when game detects mod that is mentioned in `modsettings.lsx` but not pressent in `...\Larian Studios\Baldur's Gate 3\Mods` folder (wrong encoding, wrong packing, missing file etc.)
We can try some steps to see what causes the issue. In any case, you don't need to load any save, just run the game till menu is displayed and then check if `modsettings.lsx` is intact.

- Delete/rename DWrite.dll from bin folder of the game (this is Script Extender loader/updater) and see if the `modsettings.lsx` gets wiped out. If it does, then we can safly eliminate Script extender as cause of this issue. If `modsettings.lsx` is intact, then Script Extender needs a update.
- I know it is a hussle, but disable all mods in mod manager (if you don't use one then copy `...\Larian Studios\Baldur's Gate 3\global\modsettings.lsx` to `...\Larian Studios\Baldur's Gate 3\PlayerProfiles\Public\modsettings.lsx`) and then manualy delete all files from `%LocalAppData%\Larian Studios\Baldur's Gate 3\Mods` or `%AppData%\Local\Larian Studios\Baldur's Gate 3\Mods` (one of these will work depending of your windows version). Then enable one mod at a time (start with some old mod that worked) run game and check if `modsettings.lsx` is wiped out.
  - If it is, try another mod disabling the first one first. If none if them works, I really don't know, Sorry ...
  - If the mod is sill in `modsettings.lsx`, try adding mods one by one until you found one, that deletes the content of `modsettings.lsx`. Try to contact mod author or check if there is new version.

Hope you will resolve the issue 👍

**Comment by sirkingjamz** [comment]
@BelegCufea My friend thank you! I know this is basic troubleshooting but its laborious and time consuming but I did find the one breaking my game :) for me the mod that was ruining my day was [Master Class and no spell prep scrolls patch](https://www.nexusmods.com/baldursgate3/mods/2640) once I removed that it all started working! So thank you very much i appreciate the continued help :) have a great day or night, or whatever it is outside when you (if you) read this :)

**Comment by BelegCufea** [comment]
@sirkingjamz Very nice to read that! I am so glad you worked it out.

Have a nice day and enjoy BG3.

**Comment by Gyrofalcon** [comment]
FYI: The game-engine is the one that defaults the modsettings-file, if the engine detects anomalies in any un-official pak file(s) in AppData//Mods or loose file(s) in Data.

**Comment by BelegCufea** [comment]
@Gyrofalcon Good to know. Thank you for the info.

**Comment by Norbyte** [comment]
Yes, this is vanilla game behavior and the extender has no control over that. If modsettings.lsx has references to mod names/paths/UUIDs that the game considers to be invalid or missing, it'll nuke the entire modsettings.lsx file.
