### ISSUE TITLE
how to remove script extender

### ISSUE THREAD

**Issue by santoix** [Norbyte/bg3se#78]
I don't know if where is the best place to ask this if not I apologize in advance, I just wanna know what is a correct way to remove the script without uninstalling the game, is removing the dll and the folder that is created in appdata/local enough?

**Comment by BelegCufea** [comment]
@santoix 
Removing DWrite.dll from bin folder will stop Script Extender to be loaded. You can leave the stuff in AppData intact. Or you can delete it. It will not be loaded if DWrite.dll is missing in bin folder.
