### ISSUE TITLE
 Many internal events are not recognized by RegisterListener()

### ISSUE THREAD

**Issue by AzuraZJ** [Norbyte/bg3se#8]
Hey, Nice Day~
There are some problem when I creating some script in BootstrapServer.lua to functional a custom spell.
It seems RegisterListener() cant register some Osiris internal event anymore.

I received:

> `bg3se::esv::lua::OsirisCallbackManager::RegisterNodeHandler(): Couldn't register Osiris subscriber for StatusRemoved/3: Symbol not found in story.`

The same problem happens on `StatusApplied` also. But BG3SE can correctly working on `TurnEnded`, `CastedSpell `etc. Is my usage wrong? Or are these events no longer supported in Osiris? Is there a new API list that I can refer to?

**Comment by Norbyte** [comment]
Hi,

`StatusRemoved` has 4 parameters, which is why you can't subscribe to `StatusRemoved/3`, since it technically does not exist:
`StatusRemoved(GUIDSTRING, STRING, GUIDSTRING, INTEGER)`.

`StatusApplied` has 4 too: `StatusApplied(GUIDSTRING, STRING, GUIDSTRING, INTEGER)`

**Comment by AzuraZJ** [comment]
> Hi,
> 
> `StatusRemoved` has 4 parameters, which is why you can't subscribe to `StatusRemoved/3`, since it technically does not exist: `StatusRemoved(GUIDSTRING, STRING, GUIDSTRING, INTEGER)`.
> 
> `StatusApplied` has 4 too: `StatusApplied(GUIDSTRING, STRING, GUIDSTRING, INTEGER)`.
> 
> You can check LL's complete list of Osiris symbols here: https://discord.com/channels/98922182746329088/771869529528991744/1137777834664939563

：）
Thanks for the reply, this solved my problem. 
Is there an invitation link for this discord channel that you can send me? I got into this discord channel through your link, but can't see anything.

**Comment by Norbyte** [comment]
Its the public Larian discord, no special invite needed

https://discord.gg/Qh2JM7wn

**Comment by AzuraZJ** [comment]
> Its the public Larian discord, no special invite needed
> 
> https://discord.gg/Qh2JM7wn



Thanks so much, my mod can working again!!!!!
Love U Norbyte!
