### ISSUE TITLE
Could not locate RuleAction; ; Call in osirisdll

### ISSUE THREAD

**Issue by Bnidoya** [Norbyte/bg3se#81]
Enter the main menu of the game, loading stopped at 33%, pop up this prompt, and then CTD
![微信图片_20230929170434](https://github.com/Norbyte/bg3se/assets/145805304/6da4e0e0-c302-4971-9406-bd39a431f92d)

**Comment by Bnidoya** [comment]
The version is the latest v5, how can we solve it

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
