### ISSUE TITLE
Script Extender Update Failed

### ISSUE THREAD

**Issue by Sluss12** [Norbyte/bg3se#83]
I got this post update, I think it's a problem with my PC/network config. Pretty sure I need the appdata files but don't know what I need to do to fix
![bg3 error](https://github.com/Norbyte/bg3se/assets/26719998/406176f2-7875-4631-a258-b45dc06260cf)

**Comment by Norbyte** [comment]
Check if you can open this URL:
https://bg3se-updates.norbyte.dev/Channels/Release/Manifest.json

**Comment by Sluss12** [comment]
I have no issue opening the URL, replaced my `Manifest-Release.json` but still got the error

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
