### ISSUE TITLE
Cannot queue server commands when the server state machine is not initialized

### ISSUE THREAD

**Issue by gaofighgar** [Norbyte/bg3se#84]
Hi Mate,

May i know how to fix the issue ?

![bode3_error](https://github.com/Norbyte/bg3se/assets/79038615/71cec981-7fbc-43a4-b9db-bb9f6486ebf5)

**Comment by Norbyte** [comment]
Use the latest game version, extender requires an up to date game to function (currently Patch 3 or later)

**Comment by MultiKoopa** [comment]
> Use the latest game version, the extender requires an up to date game to function (currently Patch 3 or later)

Hi. I'm running the latest version of the game and of Script Extender, getting this error. What else can cause it?

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
