### ISSUE TITLE
Script Extender in multiplayer?

### ISSUE THREAD

**Issue by HydroShark** [Norbyte/bg3se#85]
This is not so much as a issue and is instead a query, do you know whether or not the Script Extender can be used in multiplayer alongside people who do not have it installed. I am looking to install this mod and would rather not have to install and uninstall it every time I want to play multiplayer.

**Comment by Norbyte** [comment]
By itself the extender does nothing, i.e. you can have a mix of extender and non-extender players.
However if a specific mod you use requires extender, then it is recommended to have it installed for every player.
