### ISSUE TITLE
Persistent variables dont get cleared to nil after Mod remove

### ISSUE THREAD

**Issue by SwissFred57** [Norbyte/bg3se#86]
i have some Persistent Variables in my Mod after i remove the Mod they gets reloaded from cache
also after a Save game without the Mod.

![image](https://github.com/Norbyte/bg3se/assets/123299068/cb298c61-d6bc-4062-b63a-bc0ad7d059d1)

**Comment by Norbyte** [comment]
This is by design to ensure that there is no data loss when a mod is removed and later re-added.
If the mod is not loaded then its variables being kept should have no effect on other mods.

**Comment by SwissFred57** [comment]
yes i understand , the problem is if i set a variable that you get an Item only once
then remove the Mod and add it again the Item is Gone and the Variable set to not add the Item
