### ISSUE TITLE
Script Extender failure with today's SE build

### ISSUE THREAD

**Issue by Cezero** [Norbyte/bg3se#87]
******************************************************************************

BG3Ext v6 built on Oct  1 2023 08:58:23
Game version v4.37.35.951 OK
ScriptExtender::Initialize: Starting
No match found for mapping 'esv::SavegameManager::WarnIfModded'
No match found for mapping 'esv::SavegamePostVisit_DisableStoryMerge'
No match found for mapping 'esv::StatsSystem::ThrowDamageEvent'
No match found for mapping 'ecs::ComponentIDRef'
No match found for mapping 'ecs::EventComponentIDRef'
No match found for mapping 'ecs::ReplicationComponentIDRef2'
No match found for mapping 'KillLauncher'
Library startup took 996 ms
No match found for mapping 'eoc::SpellPrototype::Init Outer'
LibraryManager::PostStartupFindLibraries() took 177 ms
bg3se::ecs::EntitySystemHelpersBase::MapComponentIndices(): Could not find index for component: eoc::spell::CastComponent
bg3se::ecs::EntitySystemHelpersBase::MapComponentIndices(): Could not find index for component: eoc::spell::CastComponent
STARTUP ERROR: An error has occurred during Script Extender initialization. Some extension features might be unavailable.

**Comment by Canadaraid** [comment]
Getting the same issue. was it an update that went through today? was working fine last night

**Comment by BelegCufea** [comment]
Same here. But only with Vulkan (bg3.exe) runtime. It seems  OK with DX11 (bg3_dx11.exe).

**Comment by Norbyte** [comment]
Will investigate

**Comment by BelegCufea** [comment]
@Norbyte 
OK. Now I am totally lost. The latest patch (no. 8 - 4.37.48.643) just fixed it for me.

**Comment by BelegCufea** [comment]
@Norbyte 
And here we go again. Patch 9 and same error in bg3.exe. 
![image](https://github.com/Norbyte/bg3se/assets/3337079/a78c2f9d-dfa1-42e4-93c9-b4f719a4e81d)

And again bg3_dx11.exe is fine.

GOG version
bg3.exe - size 88,821,256, version 4.37.67.641, MD5 77555ca396e2f6e1d74206a466dcce91
bg3_dx11.exe - size 86,243,336, version 4.37.67.64, MD5 1ba18aa9a4f6891b890fb9f151c05b34

I am just fine playing DX11 version (thought Vulkan is smoother for whatever reason).

**Comment by TheoGeek** [comment]
Same here. Works for DX11 but not for Vulkan.  GOG version. Latest update (same versions and errors as the screenshot above)

**Comment by TheoGeek** [comment]
Weird.  I uninstalled and reinstalled and still got the same issue.  DX11 works fine though so I'll just use that for now.

**Comment by BelegCufea** [comment]
OK, Just tried to completely uninstall (wiped ALL files after proper uninstall), then download latest (patch3_hotfix3) files from GOG website (not using Galaxy client), then did clean install and copied over DWrite.DLL.

Unfortunately, no joy :-( Same executables MD5 checksums and filesizes, same error.

@rcx1 Can you please specify, how did you reinstall latest GOG package? Thanks.

**Comment by rcx1** [comment]
> OK, Just tried to completely uninstall (wiped ALL files after proper uninstall), then download latest (patch3_hotfix3) files from GOG website (not using Galaxy client), then did clean install and copied over DWrite.DLL.
> 
> Unfortunately, no joy :-( Same executables MD5 checksums and filesizes, same error.
> 
> @rcx1 Can you please specify, how did you reinstall latest GOG package? Thanks.

I have not used galaxy client either but did not wipe the folder, just let installer overwrite it. But I have not tested it with the latest version, but with v4.1.1.3748643.

**Comment by BelegCufea** [comment]
@rcx1 I see. In that particular version (hotfix 8, or patch 3 hotfix 2) SE works for me as well.
But thanks for info.

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
