### ISSUE TITLE
Crashes on Linux with CreateConsole set to true

### ISSUE THREAD

**Issue by DomiStyle** [Norbyte/bg3se#9]
I tried to follow the guide for deleting characters from a campaign but I can't seem to launch the game with `CreateConsole` set to `true`.

The game just immediately exits on start. Setting it to `false` and the game launches with no issues.

Not sure if the proton log helps you out but here it is: 
[steam-1086940.log](https://github.com/Norbyte/bg3se/files/12407284/steam-1086940.log)

**Comment by gallexme** [comment]
i run it like this(on nixos)
WINEDLLOVERRIDES='DWrite.dll=n,b' PROTON_NO_ESYNC=1 %command% 2>&1 |tee -a log.txt

and the console works
![image](https://github.com/Norbyte/bg3se/assets/1122989/72f46cee-fb52-4abf-9a71-0712d084b3ce)

**Comment by DomiStyle** [comment]
I switched from Fedoras native steam package to Flatpak and everything is working fine now, thanks!
