### ISSUE TITLE
Would you please add gui binding

### ISSUE THREAD

**Issue by czastack** [Norbyte/bg3se#93]
Would you please add gui binding like ImGui? For example reframework for ReEngine and CyberEngineTweaks for Cyberpunk 2077 can use ImGui in lua script file. Because bg3se disabled require/loadfile for security reasons, so I cannot import dll or native module by myself.

**Comment by bk0n9** [comment]
I would love to have this feature as well.

**Comment by Norbyte** [comment]
Imgui was integrated in v16, closing :P
